#![allow(unused_mut, dead_code, unused_variables)]

//! Shared scene load/save and rehydration — used by both editor and runtime.

use bevy::ecs::world::FilteredEntityRef;
use bevy::prelude::*;
use renzora::console_log::*;
use renzora::{CurrentProject, DefaultCamera, EditorCamera, HideInHierarchy, MeshColor, MeshInstanceData, MeshPrimitive, PlayModeCamera, PlayModeState, SceneCamera, ShapeRegistry, ViewportRenderTarget};
use renzora_lighting::Sun;
use serde::de::DeserializeSeed;
use std::collections::BTreeSet;
use std::path::Path;

// ============================================================================
// Scene load state + events
// ============================================================================

/// Coarse phase of the most recent scene load.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub enum SceneLoadPhase {
    #[default]
    Idle,
    Loading,
    Ready,
    Failed,
}

/// Tracks the state of scene loading so UI can reflect progress.
///
/// `progress` is 0..1. Scene loading is currently synchronous, so the value
/// jumps from 0 → 1 in a single frame; a future async split can make this a
/// true progress readout without changing this resource's shape.
#[derive(Resource, Default)]
pub struct SceneLoadState {
    pub phase: SceneLoadPhase,
    pub current_path: Option<String>,
    pub progress: f32,
}

#[derive(Event, Clone, Debug)]
pub struct SceneLoaded {
    pub path: String,
}

#[derive(Event, Clone, Debug)]
pub struct SceneLoadFailed {
    pub path: String,
    pub error: String,
}

// ============================================================================
// Save
// ============================================================================

/// Save specific entities to a RON file.
pub fn save_scene(world: &mut World, path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let type_registry = world.resource::<AppTypeRegistry>().clone();

    let mut entities: Vec<Entity> = Vec::new();
    let mut query = world.query_filtered::<Entity, (With<Name>, Without<HideInHierarchy>, Without<EditorCamera>, Without<bevy::input::gamepad::Gamepad>)>();
    for entity in query.iter(world) {
        entities.push(entity);
    }

    // Exclude descendants of SceneInstance entities — those come from the
    // referenced source scene file and live there, not here. Only the instance
    // root (with its transform + any host overrides) is saved in the host.
    {
        let instance_roots: Vec<Entity> = {
            let mut q = world.query_filtered::<Entity, With<renzora::SceneInstance>>();
            q.iter(world).collect()
        };
        if !instance_roots.is_empty() {
            let before = entities.len();
            entities.retain(|&entity| {
                let mut cursor = entity;
                loop {
                    if let Some(child_of) = world.get::<ChildOf>(cursor) {
                        let parent = child_of.parent();
                        if instance_roots.contains(&parent) {
                            return false; // descendant of a scene instance — skip
                        }
                        cursor = parent;
                    } else {
                        break;
                    }
                }
                true
            });
            let excluded = before - entities.len();
            if excluded > 0 {
                console_info("Scene", format!(
                    "Excluded {} nested-scene descendant entities from save", excluded
                ));
            }
        }
    }

    // Exclude descendants of MeshInstanceData entities — those are spawned GLTF
    // children that get regenerated by rehydration. Only the parent (which holds
    // the model_path) should be saved.
    {
        let mesh_instance_entities: Vec<Entity> = {
            let mut q = world.query_filtered::<Entity, With<MeshInstanceData>>();
            q.iter(world).collect()
        };
        if !mesh_instance_entities.is_empty() {
            let before = entities.len();
            entities.retain(|&entity| {
                // Walk up the parent chain; if we hit a MeshInstanceData entity
                // and it's not *this* entity, exclude it.
                let mut cursor = entity;
                loop {
                    if let Some(child_of) = world.get::<ChildOf>(cursor) {
                        let parent = child_of.parent();
                        if mesh_instance_entities.contains(&parent) {
                            return false; // descendant of a mesh instance — skip
                        }
                        cursor = parent;
                    } else {
                        break;
                    }
                }
                true
            });
            let excluded = before - entities.len();
            if excluded > 0 {
                console_info("Scene", format!(
                    "Excluded {} GLTF descendant entities from save", excluded
                ));
            }
        }
    }

    if entities.is_empty() {
        let content = "(entities: {}, resources: {})";
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
        console_info("Scene", format!("Saved empty scene to {}", path.display()));
        info!("Saved empty scene to {}", path.display());
        return Ok(());
    }

    let mut scene = DynamicSceneBuilder::from_world(world)
        .deny_all_resources()
        .deny_component::<Mesh3d>()
        .deny_component::<MeshMaterial3d<StandardMaterial>>()
        .deny_component::<MeshMaterial3d<renzora_shader::material::runtime::GraphMaterial>>()
        .deny_component::<renzora_shader::material::resolver::MaterialResolved>()
        .deny_component::<MeshMaterial3d<renzora_terrain::material::TerrainCheckerboardMaterial>>()
        .deny_component::<Camera3d>()
        .deny_component::<Camera>()
        .deny_component::<ViewVisibility>()
        .deny_component::<Children>()
        .deny_component::<bevy::transform::components::TransformTreeChanged>()
        .deny_component::<bevy::camera::primitives::Aabb>()
        .deny_component::<bevy::render::sync_world::SyncToRenderWorld>()
        .deny_component::<bevy::input::gamepad::Gamepad>()
        .deny_component::<bevy::input::gamepad::GamepadSettings>()
        // Animation runtime state — ephemeral, must rebuild on load.
        .deny_component::<bevy::animation::AnimationPlayer>()
        .deny_component::<bevy::animation::transition::AnimationTransitions>()
        // `AnimatedBy` stores an Entity reference that doesn't remap across
        // scene loads — must be reconstructed by the animator rehydration.
        .deny_component::<bevy::animation::AnimatedBy>()
        // AnimatorReadState is a runtime mirror — rebuilt each frame.
        .deny_component::<renzora_animation::AnimatorReadState>()
        // Networking: Lightyear internals should not persist to scene files.
        // Networked/NetworkOwner/NetworkId are runtime-only markers.
        .deny_component::<renzora_network::Networked>()
        .deny_component::<renzora_network::NetworkOwner>()
        .deny_component::<renzora_network::NetworkId>()
        // Avian runtime components are regenerated on load from our
        // serializable PhysicsBodyData + CollisionShapeData. Persisting them
        // causes duplicate-reflect-type errors during deserialization.
        .deny_component::<avian3d::prelude::Collider>()
        .deny_component::<avian3d::collision::collider::ColliderAabb>()
        .deny_component::<avian3d::prelude::RigidBody>()
        .deny_component::<avian3d::prelude::LinearVelocity>()
        .deny_component::<avian3d::prelude::AngularVelocity>()
        .deny_component::<avian3d::prelude::Mass>()
        .deny_component::<avian3d::prelude::Friction>()
        .deny_component::<avian3d::prelude::Restitution>()
        .deny_component::<avian3d::prelude::GravityScale>()
        .deny_component::<avian3d::prelude::LinearDamping>()
        .deny_component::<avian3d::prelude::AngularDamping>()
        .deny_component::<avian3d::prelude::LockedAxes>()
        .deny_component::<avian3d::prelude::Sensor>()
        .extract_entities(entities.into_iter())
        .build();

    // Strip components that can't be serialized or are editor-only.
    {
        let registry = type_registry.read();
        for entity in &mut scene.entities {
            entity.components.retain(|component| {
                // Filter editor-only types by name (not available as deps in runtime)
                let type_name = component.reflect_type_path();
                if type_name.starts_with("bevy_mod_outline::") {
                    return false;
                }
                // Never serialize avian runtime components — they're regenerated
                // on load from PhysicsBodyData + CollisionShapeData. Persisting
                // them causes duplicate-reflect-type errors on deserialize.
                if type_name.starts_with("avian3d::") {
                    return false;
                }
                let serializer = bevy::reflect::serde::TypedReflectSerializer::new(
                    component.as_partial_reflect(),
                    &registry,
                );
                // Try serializing to a throwaway RON value
                ron::ser::to_string(&serializer).is_ok()
            });
        }
    }

    let registry = type_registry.read();
    let serialized = scene
        .serialize(&registry)
        .map_err(|e| format!("Scene serialization failed: {e}"))?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, &serialized)?;
    console_info("Scene", format!("Saved scene to {} ({} entities)", path.display(), scene.entities.len()));
    info!("Saved scene to {} ({} entities)", path.display(), scene.entities.len());
    Ok(())
}

/// Serialize scene entities to a RON string (same logic as `save_scene` but returns a string).
pub fn serialize_scene_to_string(world: &mut World) -> Result<String, Box<dyn std::error::Error>> {
    let type_registry = world.resource::<AppTypeRegistry>().clone();

    let mut entities: Vec<Entity> = Vec::new();
    let mut query = world.query_filtered::<Entity, (With<Name>, Without<HideInHierarchy>, Without<EditorCamera>, Without<bevy::input::gamepad::Gamepad>)>();
    for entity in query.iter(world) {
        entities.push(entity);
    }

    // Exclude descendants of MeshInstanceData entities
    {
        let mesh_instance_entities: Vec<Entity> = {
            let mut q = world.query_filtered::<Entity, With<MeshInstanceData>>();
            q.iter(world).collect()
        };
        if !mesh_instance_entities.is_empty() {
            entities.retain(|&entity| {
                let mut cursor = entity;
                loop {
                    if let Some(child_of) = world.get::<ChildOf>(cursor) {
                        let parent = child_of.parent();
                        if mesh_instance_entities.contains(&parent) {
                            return false;
                        }
                        cursor = parent;
                    } else {
                        break;
                    }
                }
                true
            });
        }
    }

    if entities.is_empty() {
        return Ok("(entities: {}, resources: {})".to_string());
    }

    let mut scene = DynamicSceneBuilder::from_world(world)
        .deny_all_resources()
        .deny_component::<Mesh3d>()
        .deny_component::<MeshMaterial3d<StandardMaterial>>()
        .deny_component::<MeshMaterial3d<renzora_shader::material::runtime::GraphMaterial>>()
        .deny_component::<renzora_shader::material::resolver::MaterialResolved>()
        .deny_component::<MeshMaterial3d<renzora_terrain::material::TerrainCheckerboardMaterial>>()
        .deny_component::<Camera3d>()
        .deny_component::<Camera>()
        .deny_component::<ViewVisibility>()
        .deny_component::<Children>()
        .deny_component::<bevy::transform::components::TransformTreeChanged>()
        .deny_component::<bevy::camera::primitives::Aabb>()
        .deny_component::<bevy::render::sync_world::SyncToRenderWorld>()
        .deny_component::<bevy::input::gamepad::Gamepad>()
        .deny_component::<bevy::input::gamepad::GamepadSettings>()
        // Animation runtime state — ephemeral, must rebuild on load.
        .deny_component::<bevy::animation::AnimationPlayer>()
        .deny_component::<bevy::animation::transition::AnimationTransitions>()
        // `AnimatedBy` stores an Entity reference that doesn't remap across
        // scene loads — must be reconstructed by the animator rehydration.
        .deny_component::<bevy::animation::AnimatedBy>()
        // AnimatorReadState is a runtime mirror — rebuilt each frame.
        .deny_component::<renzora_animation::AnimatorReadState>()
        .deny_component::<renzora_network::Networked>()
        .deny_component::<renzora_network::NetworkOwner>()
        .deny_component::<renzora_network::NetworkId>()
        // Avian runtime components are regenerated on load from our
        // serializable PhysicsBodyData + CollisionShapeData. Persisting them
        // causes duplicate-reflect-type errors during deserialization.
        .deny_component::<avian3d::prelude::Collider>()
        .deny_component::<avian3d::collision::collider::ColliderAabb>()
        .deny_component::<avian3d::prelude::RigidBody>()
        .deny_component::<avian3d::prelude::LinearVelocity>()
        .deny_component::<avian3d::prelude::AngularVelocity>()
        .deny_component::<avian3d::prelude::Mass>()
        .deny_component::<avian3d::prelude::Friction>()
        .deny_component::<avian3d::prelude::Restitution>()
        .deny_component::<avian3d::prelude::GravityScale>()
        .deny_component::<avian3d::prelude::LinearDamping>()
        .deny_component::<avian3d::prelude::AngularDamping>()
        .deny_component::<avian3d::prelude::LockedAxes>()
        .deny_component::<avian3d::prelude::Sensor>()
        .extract_entities(entities.into_iter())
        .build();

    // Strip components that can't be serialized or are editor-only.
    {
        let registry = type_registry.read();
        for entity in &mut scene.entities {
            entity.components.retain(|component| {
                let type_name = component.reflect_type_path();
                if type_name.starts_with("bevy_mod_outline::") {
                    return false;
                }
                // Avian runtime components (e.g. ColliderMarker) are
                // regenerated on load from PhysicsBodyData + CollisionShapeData.
                // Persisting them causes duplicate-reflect-type errors on
                // deserialize — same filter as `save_scene`.
                if type_name.starts_with("avian3d::") {
                    return false;
                }
                let serializer = bevy::reflect::serde::TypedReflectSerializer::new(
                    component.as_partial_reflect(),
                    &registry,
                );
                ron::ser::to_string(&serializer).is_ok()
            });
        }
    }

    let registry = type_registry.read();
    let serialized = scene
        .serialize(&registry)
        .map_err(|e| format!("Scene serialization failed: {e}"))?;

    Ok(serialized)
}

/// Load a scene from a RON string into the world (same logic as `load_scene` but from string).
pub fn load_scene_from_string(world: &mut World, ron: &str) {
    let trimmed = ron.trim();
    if trimmed.is_empty() || trimmed == "(entities: {}, resources: {})" {
        return;
    }

    let scene = {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();

        let scene_deserializer = bevy::scene::serde::SceneDeserializer {
            type_registry: &registry,
        };

        let mut ron_deserializer = match ron::Deserializer::from_str(ron) {
            Ok(d) => d,
            Err(e) => {
                error!("Failed to parse RON string: {}", e);
                return;
            }
        };

        match scene_deserializer.deserialize(&mut ron_deserializer) {
            Ok(s) => s,
            Err(e) => {
                error!("Failed to deserialize scene from string: {}", e);
                return;
            }
        }
    };

    let mut entity_map = bevy::ecs::entity::EntityHashMap::default();
    match scene.write_to_world(world, &mut entity_map) {
        Ok(()) => {
            // Re-insert ChildOf to trigger hierarchy hooks
            let children_with_parents: Vec<(Entity, Entity)> = entity_map
                .values()
                .filter_map(|&entity| {
                    world.get_entity(entity).ok()?.get::<ChildOf>().map(|c| (entity, c.parent()))
                })
                .collect();

            for (child, parent) in children_with_parents {
                world.entity_mut(child).remove::<ChildOf>();
                world.entity_mut(child).insert(ChildOf(parent));
            }
        }
        Err(e) => {
            error!("Failed to write scene from string to world: {}", e);
        }
    }
}

/// Save the current project's main scene.
pub fn save_current_scene(world: &mut World) {
    let Some(project) = world.get_resource::<CurrentProject>() else {
        warn!("No project open — cannot save scene");
        return;
    };
    let path = project.main_scene_path();
    if let Err(e) = save_scene(world, &path) {
        error!("Failed to save scene: {}", e);
    }
}

// ============================================================================
// Load
// ============================================================================

/// Load a scene from a RON file into the world.
///
/// Tries the Vfs (rpak archive) first, then falls back to disk.
pub fn load_scene(world: &mut World, path: &Path) {
    console_info("Scene", format!("=== Loading scene from {} ===", path.display()));

    let path_str = path.to_string_lossy().to_string();
    if let Some(mut state) = world.get_resource_mut::<SceneLoadState>() {
        state.phase = SceneLoadPhase::Loading;
        state.current_path = Some(path_str.clone());
        state.progress = 0.0;
    }

    // Try reading from Vfs (rpak archive) first.
    let content = if let Some(vfs) = world.get_resource::<crate::Vfs>() {
        // Normalize to forward-slash archive-relative path, stripping leading "./" or ".\"
        let path_str = path.to_string_lossy().replace('\\', "/");
        let archive_key = path_str.strip_prefix("./").unwrap_or(&path_str);
        if let Some(s) = vfs.read_string(archive_key) {
            console_info("Scene", format!("Read {} bytes from rpak: {}", s.len(), archive_key));
            Some(s)
        } else {
            None
        }
    } else {
        None
    };

    // Fall back to disk if Vfs didn't have it.
    let content = match content {
        Some(c) => c,
        None => {
            if !path.exists() {
                console_warn("Scene", format!("Scene file does not exist: {}", path.display()));
                info!("Scene file does not exist yet: {}", path.display());
                return;
            }
            match std::fs::read_to_string(path) {
                Ok(c) => {
                    console_info("Scene", format!("Read {} bytes from {}", c.len(), path.display()));
                    c
                }
                Err(e) => {
                    console_error("Scene", format!("Failed to read scene file {}: {}", path.display(), e));
                    error!("Failed to read scene file {}: {}", path.display(), e);
                    return;
                }
            }
        }
    };

    let trimmed = content.trim();
    if trimmed.is_empty() || trimmed == "(entities: {}, resources: {})" {
        console_info("Scene", format!("Scene is empty: {}", path.display()));
        info!("Scene is empty: {}", path.display());
        if let Some(mut state) = world.get_resource_mut::<SceneLoadState>() {
            state.phase = SceneLoadPhase::Ready;
            state.progress = 1.0;
        }
        world.trigger(SceneLoaded { path: path_str.clone() });
        return;
    }

    let scene = {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();

        let scene_deserializer = bevy::scene::serde::SceneDeserializer {
            type_registry: &registry,
        };

        let mut ron_deserializer = match ron::Deserializer::from_str(&content) {
            Ok(d) => d,
            Err(e) => {
                error!("Failed to parse RON {}: {}", path.display(), e);
                return;
            }
        };

        match scene_deserializer.deserialize(&mut ron_deserializer) {
            Ok(s) => s,
            Err(e) => {
                error!("Failed to deserialize scene {}: {}", path.display(), e);
                return;
            }
        }
    };

    let mut entity_map = bevy::ecs::entity::EntityHashMap::default();
    match scene.write_to_world(world, &mut entity_map) {
        Ok(()) => {
            console_info("Scene", format!(
                "Scene written to world: {} entities mapped from {}",
                entity_map.len(), path.display()
            ));

            // Log each mapped entity
            for (&scene_entity, &world_entity) in &entity_map {
                let name = world.get::<Name>(world_entity)
                    .map(|n| n.to_string())
                    .unwrap_or_else(|| "unnamed".into());
                let has_scene_cam = world.get::<SceneCamera>(world_entity).is_some();
                let has_default = world.get::<DefaultCamera>(world_entity).is_some();
                let mut tags = Vec::new();
                if has_scene_cam { tags.push("SceneCamera"); }
                if has_default { tags.push("DefaultCamera"); }
                let tag_str = if tags.is_empty() { String::new() } else { format!(" [{}]", tags.join(", ")) };
                console_info("Scene", format!(
                    "  scene:{:?} -> world:{:?} \"{}\"{}",
                    scene_entity, world_entity, name, tag_str
                ));
            }

            info!("Loaded scene from {} ({} entities mapped)", path.display(), entity_map.len());

            // Bevy's write_to_world inserts ChildOf via reflection, which may not
            // trigger the on_insert hooks that maintain the parent's Children component.
            // Re-insert ChildOf on each child to force the hooks to fire.
            let children_with_parents: Vec<(Entity, Entity)> = entity_map
                .values()
                .filter_map(|&entity| {
                    world.get_entity(entity).ok()?.get::<ChildOf>().map(|c| (entity, c.parent()))
                })
                .collect();

            console_info("Scene", format!(
                "Re-inserting ChildOf on {} entities to trigger hierarchy hooks",
                children_with_parents.len()
            ));

            for (child, parent) in children_with_parents {
                // Remove and re-insert ChildOf to trigger hooks
                world.entity_mut(child).remove::<ChildOf>();
                world.entity_mut(child).insert(ChildOf(parent));
            }

            // Expand nested scene instances referenced from the host scene.
            expand_scene_instances(world);

            console_success("Scene", format!("=== Scene load complete: {} ===", path.display()));

            if let Some(mut state) = world.get_resource_mut::<SceneLoadState>() {
                state.phase = SceneLoadPhase::Ready;
                state.progress = 1.0;
            }
            world.trigger(SceneLoaded { path: path_str.clone() });
        }
        Err(e) => {
            console_error("Scene", format!("Failed to write scene to world {}: {}", path.display(), e));
            error!("Failed to write scene to world {}: {}", path.display(), e);

            if let Some(mut state) = world.get_resource_mut::<SceneLoadState>() {
                state.phase = SceneLoadPhase::Failed;
            }
            let err_str = e.to_string();
            world.trigger(SceneLoadFailed { path: path_str.clone(), error: err_str });
        }
    }
}

/// Expand every `SceneInstance` entity in the world that has no children yet:
/// load the referenced source scene and reparent its roots under the instance.
///
/// Re-runnable: already-expanded instances (any with children) are skipped.
pub fn expand_scene_instances(world: &mut World) {
    // Re-entrancy guard: if expand recursively triggers another load of a
    // scene that's already in the expand stack, bail out to avoid infinite
    // recursion on cyclic SceneInstance references.
    thread_local! {
        static EXPAND_STACK: std::cell::RefCell<Vec<std::path::PathBuf>> =
            const { std::cell::RefCell::new(Vec::new()) };
    }

    let project_root = world
        .get_resource::<CurrentProject>()
        .map(|p| p.path.clone());

    let mut to_expand: Vec<(Entity, std::path::PathBuf)> = Vec::new();
    {
        let mut q = world.query::<(Entity, &renzora::SceneInstance)>();
        for (entity, inst) in q.iter(world) {
            // Skip entities that already have children (already expanded, or
            // user added children before save).
            if world.get::<Children>(entity).map_or(false, |c| c.iter().count() > 0) {
                continue;
            }
            let Some(ref root) = project_root else { continue };
            let abs = root.join(&inst.source);
            // Skip if this path is already being expanded up the stack (cycle).
            let in_stack = EXPAND_STACK.with(|s| s.borrow().iter().any(|p| p == &abs));
            if in_stack {
                console_warn(
                    "Scene",
                    format!(
                        "Skipping recursive scene instance: {} (already expanding)",
                        abs.display()
                    ),
                );
                continue;
            }
            to_expand.push((entity, abs));
        }
    }

    for (instance_entity, source_path) in to_expand {
        EXPAND_STACK.with(|s| s.borrow_mut().push(source_path.clone()));

        let existing_roots: std::collections::HashSet<Entity> = {
            let mut q = world.query_filtered::<Entity, (With<Name>, Without<ChildOf>)>();
            q.iter(world).collect()
        };

        load_scene(world, &source_path);

        let mut new_roots: Vec<Entity> = Vec::new();
        {
            let mut q = world.query_filtered::<Entity, (With<Name>, Without<ChildOf>)>();
            for e in q.iter(world) {
                if !existing_roots.contains(&e) && e != instance_entity {
                    new_roots.push(e);
                }
            }
        }

        for root in new_roots {
            world.entity_mut(root).insert(ChildOf(instance_entity));
        }

        EXPAND_STACK.with(|s| { s.borrow_mut().pop(); });
    }
}

/// Spawn a new `SceneInstance` entity that references `source_path` and
/// immediately expand it by loading the source scene's entities under it.
///
/// `source_path` is absolute; it's stored as an asset-relative string.
/// Returns the newly-spawned instance root entity, or `None` if no project
/// is open (paths can't be resolved).
/// Returns `true` if `source_path` resolves to the same file as
/// `host_scene_path` — i.e. a direct self-reference. Used by drop handlers
/// to reject a scene being dropped into itself.
pub fn is_self_reference(host_scene_path: &Path, source_path: &Path) -> bool {
    paths_equal(host_scene_path, source_path)
}

fn paths_equal(a: &Path, b: &Path) -> bool {
    match (a.canonicalize(), b.canonicalize()) {
        (Ok(ca), Ok(cb)) => ca == cb,
        _ => a == b,
    }
}

/// Cache of scene → outgoing scene references, keyed by canonical path with
/// mtime validation. Populated lazily by `would_create_reference_cycle` and
/// invalidated transparently when the file on disk has been modified.
///
/// Worst-case drop cost is one disk read per changed scene in the cycle
/// graph; repeated drops and deep reference graphs reuse cached entries.
#[derive(Resource, Default)]
pub struct SceneReferenceCache {
    entries: std::collections::HashMap<std::path::PathBuf, CachedRefs>,
}

struct CachedRefs {
    mtime: Option<std::time::SystemTime>,
    sources: Vec<String>,
}

impl SceneReferenceCache {
    pub fn invalidate(&mut self, path: &Path) {
        let canon = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
        self.entries.remove(&canon);
    }

    pub fn clear(&mut self) {
        self.entries.clear();
    }

    /// Return the outgoing `SceneInstance.source` list for `path`, reading
    /// + scanning from disk only if the cache is missing or stale.
    fn references_for(&mut self, path: &Path) -> Option<&[String]> {
        let canon = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
        let fresh_mtime = std::fs::metadata(&canon).and_then(|m| m.modified()).ok();

        let needs_reload = match self.entries.get(&canon) {
            Some(e) => e.mtime != fresh_mtime,
            None => true,
        };

        if needs_reload {
            let text = std::fs::read_to_string(&canon).ok()?;
            let sources = extract_scene_instance_sources(&text);
            self.entries.insert(canon.clone(), CachedRefs { mtime: fresh_mtime, sources });
        }

        self.entries.get(&canon).map(|e| e.sources.as_slice())
    }
}

/// Returns `true` if dropping `source_path` into `host_scene_path` would
/// create a cycle — either directly (source == host) or transitively
/// (source, or any scene source references through its `SceneInstance`
/// components, references host).
///
/// `project_root` is used to resolve asset-relative `source` fields read
/// from the referenced .ron files. Backed by `SceneReferenceCache` —
/// repeated calls reuse cached parses until file mtimes change.
pub fn would_create_reference_cycle(
    cache: &mut SceneReferenceCache,
    project_root: &Path,
    host_scene_path: &Path,
    source_path: &Path,
) -> bool {
    if paths_equal(host_scene_path, source_path) {
        return true;
    }
    let mut visited: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();
    let mut stack: Vec<std::path::PathBuf> = vec![source_path.to_path_buf()];

    while let Some(current) = stack.pop() {
        let canon = current.canonicalize().unwrap_or_else(|_| current.clone());
        if !visited.insert(canon) { continue }

        let Some(sources) = cache.references_for(&current) else { continue };
        // Clone out so we can drop the borrow on `cache` before recursing.
        let sources: Vec<String> = sources.to_vec();
        for rel in sources {
            let next = project_root.join(&rel);
            if paths_equal(host_scene_path, &next) {
                return true;
            }
            stack.push(next);
        }
    }
    false
}

/// Scrape `renzora::core::SceneInstance` `source:` values out of a scene
/// .ron file's text. Intentionally avoids full RON deserialization — it's
/// faster and robust to unknown components.
fn extract_scene_instance_sources(text: &str) -> Vec<String> {
    const MARKER: &str = "\"renzora::core::SceneInstance\"";
    const KEY: &str = "source:";
    let mut out = Vec::new();
    let mut cursor = 0usize;
    while let Some(mi) = text[cursor..].find(MARKER) {
        let pos = cursor + mi;
        let Some(ki) = text[pos..].find(KEY) else { break };
        let kpos = pos + ki + KEY.len();
        // Skip whitespace until opening quote.
        let mut i = kpos;
        let bytes = text.as_bytes();
        while i < bytes.len() && (bytes[i] == b' ' || bytes[i] == b'\t') { i += 1; }
        if i >= bytes.len() || bytes[i] != b'"' { cursor = kpos; continue }
        i += 1;
        let start = i;
        while i < bytes.len() && bytes[i] != b'"' { i += 1; }
        if i <= bytes.len() {
            out.push(text[start..i].to_string());
        }
        cursor = i;
    }
    out
}

pub fn spawn_scene_instance(
    world: &mut World,
    source_path: &Path,
    parent: Option<Entity>,
    transform: Transform,
) -> Option<Entity> {
    // Convert to asset-relative for portable storage.
    let relative = world
        .get_resource::<CurrentProject>()?
        .make_relative(source_path)?;

    let name = source_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("Scene")
        .to_string();

    let mut e = world.spawn((
        Name::new(name),
        renzora::SceneInstance { source: relative },
        transform,
        Visibility::default(),
    ));
    if let Some(p) = parent {
        e.insert(ChildOf(p));
    }
    let entity = e.id();

    // Expand nested scene contents in-place.
    expand_scene_instances(world);

    Some(entity)
}

/// Save the entity tree under a `SceneInstance` back to its source `.ron`
/// file. The instance's direct children become root entities in the output
/// file; deeper descendants keep their parent-child relationships.
///
/// Returns `Ok(())` on success. Does nothing and returns `Ok(())` when the
/// instance has no descendants (empty source file is written).
pub fn save_prefab_source(
    world: &mut World,
    instance_entity: Entity,
    source_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let type_registry = world.resource::<AppTypeRegistry>().clone();

    // Collect all descendants of the instance, breadth-first.
    //
    // Two filters mirror `save_scene`:
    //   1. Skip unnamed entities.
    //   2. Do NOT descend below a `MeshInstanceData` entity. Its children are
    //      runtime gltf mount points (spawned by `rehydrate_mesh_instances`)
    //      that must NOT be serialized — if they're in source.ron on reload,
    //      the `Without<Children>` rehydration guard skips the spawn and the
    //      mesh becomes invisible.
    let mut descendants: Vec<Entity> = Vec::new();
    let mut queue: Vec<Entity> = Vec::new();
    if let Some(children) = world.get::<Children>(instance_entity) {
        queue.extend(children.iter());
    }
    while let Some(e) = queue.pop() {
        if world.get::<Name>(e).is_none() {
            continue;
        }
        descendants.push(e);
        // Stop descending into gltf-owned subtrees.
        if world.get::<renzora::core::MeshInstanceData>(e).is_some() {
            continue;
        }
        if let Some(kids) = world.get::<Children>(e) {
            queue.extend(kids.iter());
        }
    }

    if descendants.is_empty() {
        // Safety: never overwrite the source file with an empty scene. If the
        // instance has no descendants at save time (e.g. expand hadn't run,
        // or the user's query state was stale), leaving the file alone is
        // much safer than clobbering it. Users can still edit the source
        // directly by opening it.
        console_warn(
            "Scene",
            format!(
                "Skipping save for {} — instance has no descendants (not overwriting with empty scene)",
                source_path.display()
            ),
        );
        return Ok(());
    }

    let mut scene = DynamicSceneBuilder::from_world(world)
        .deny_all_resources()
        .deny_component::<Mesh3d>()
        .deny_component::<MeshMaterial3d<StandardMaterial>>()
        .deny_component::<MeshMaterial3d<renzora_shader::material::runtime::GraphMaterial>>()
        .deny_component::<renzora_shader::material::resolver::MaterialResolved>()
        .deny_component::<MeshMaterial3d<renzora_terrain::material::TerrainCheckerboardMaterial>>()
        .deny_component::<Camera3d>()
        .deny_component::<Camera>()
        .deny_component::<ViewVisibility>()
        .deny_component::<Children>()
        // Children's GlobalTransform reflects the instance root's world-space
        // position. If serialized, it would "bake in" the host's placement
        // for anyone opening car.ron standalone. Bevy recomputes it each
        // frame from Transform anyway.
        .deny_component::<GlobalTransform>()
        .deny_component::<bevy::transform::components::TransformTreeChanged>()
        .deny_component::<bevy::camera::primitives::Aabb>()
        .deny_component::<bevy::render::sync_world::SyncToRenderWorld>()
        .deny_component::<bevy::input::gamepad::Gamepad>()
        .deny_component::<bevy::input::gamepad::GamepadSettings>()
        .deny_component::<bevy::animation::AnimationPlayer>()
        .deny_component::<bevy::animation::transition::AnimationTransitions>()
        .deny_component::<bevy::animation::AnimatedBy>()
        .deny_component::<renzora_animation::AnimatorReadState>()
        .deny_component::<renzora_network::Networked>()
        .deny_component::<renzora_network::NetworkOwner>()
        .deny_component::<renzora_network::NetworkId>()
        .deny_component::<avian3d::prelude::Collider>()
        .deny_component::<avian3d::collision::collider::ColliderAabb>()
        .deny_component::<avian3d::prelude::RigidBody>()
        .deny_component::<avian3d::prelude::LinearVelocity>()
        .deny_component::<avian3d::prelude::AngularVelocity>()
        .deny_component::<avian3d::prelude::Mass>()
        .deny_component::<avian3d::prelude::Friction>()
        .deny_component::<avian3d::prelude::Restitution>()
        .deny_component::<avian3d::prelude::GravityScale>()
        .deny_component::<avian3d::prelude::LinearDamping>()
        .deny_component::<avian3d::prelude::AngularDamping>()
        .deny_component::<avian3d::prelude::LockedAxes>()
        .deny_component::<avian3d::prelude::Sensor>()
        .extract_entities(descendants.into_iter())
        .build();

    // Strip the `ChildOf` components that point at the instance entity
    // (direct children) — in the source file those become root-level
    // entities, reparented to the instance on load by
    // `expand_scene_instances`.
    let instance_entity_field = instance_entity;
    for entity in &mut scene.entities {
        entity.components.retain(|component| {
            let type_name = component.reflect_type_path();
            // Same editor-only filters as save_scene.
            if type_name.starts_with("bevy_mod_outline::") {
                return false;
            }
            if type_name.starts_with("avian3d::") {
                return false;
            }
            // Drop ChildOf components that reference the instance entity.
            if type_name.ends_with("::ChildOf") || type_name == "bevy_ecs::hierarchy::ChildOf" {
                if let Some(reflect_any) = component.as_partial_reflect().try_as_reflect() {
                    // ChildOf has a single Entity field.
                    if let Some(co) = reflect_any.downcast_ref::<ChildOf>() {
                        if co.parent() == instance_entity_field {
                            return false;
                        }
                    }
                }
            }
            let registry = type_registry.read();
            let serializer = bevy::reflect::serde::TypedReflectSerializer::new(
                component.as_partial_reflect(),
                &registry,
            );
            ron::ser::to_string(&serializer).is_ok()
        });
    }

    let registry = type_registry.read();
    let serialized = scene
        .serialize(&registry)
        .map_err(|e| format!("Prefab serialization failed: {e}"))?;

    if let Some(parent) = source_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(source_path, &serialized)?;
    console_info("Scene", format!(
        "Saved prefab source to {} ({} entities)",
        source_path.display(), scene.entities.len()
    ));
    Ok(())
}

/// Walk every `SceneInstance` in the world and write its descendant subtree
/// back to its source `.ron` file. Call this from the host scene save flow
/// so edits to nested entities propagate to their source prefab.
///
/// `host_scene_path` is the path of the scene currently being saved — used
/// to skip self-referencing instances (an instance of car.ron inside
/// car.ron would otherwise corrupt car.ron on save).
///
/// Instances that share a source path are also skipped (with a warning):
/// picking which copy's interior to push back is ambiguous, and a silent
/// last-write-wins would clobber edits made to the other copies.
pub fn save_all_scene_instances(world: &mut World, host_scene_path: &Path) {
    let project_path = match world.get_resource::<CurrentProject>() {
        Some(p) => p.path.clone(),
        None => return,
    };

    let instances: Vec<(Entity, String)> = {
        let mut q = world.query::<(Entity, &renzora::SceneInstance)>();
        q.iter(world)
            .map(|(e, inst)| (e, inst.source.clone()))
            .collect()
    };

    // Count how many instances share each source path so we can flag dupes.
    let mut source_counts: std::collections::HashMap<String, u32> =
        std::collections::HashMap::new();
    for (_, rel) in &instances {
        *source_counts.entry(rel.clone()).or_insert(0) += 1;
    }

    let host_canon = host_scene_path.canonicalize().ok();

    for (entity, source_rel) in instances {
        let source_abs = project_path.join(&source_rel);

        // Guard 1: self-reference. Saving an instance of the host scene
        // back into the host scene file would either clobber or recursively
        // inline it.
        let source_canon = source_abs.canonicalize().ok();
        if let (Some(host), Some(src)) = (&host_canon, &source_canon) {
            if host == src {
                console_warn("Scene", format!(
                    "Skipping self-referencing instance → {} (source == host scene)",
                    source_rel
                ));
                continue;
            }
        }

        // Guard 2: multiple instances with the same source in this host.
        // We can't pick which interior to propagate, so skip all of them.
        if source_counts.get(&source_rel).copied().unwrap_or(0) > 1 {
            console_warn("Scene", format!(
                "Skipping instance {} — multiple instances share this source in the host; \
                 edit the source directly or unpack to propagate changes",
                source_rel
            ));
            continue;
        }

        if let Err(e) = save_prefab_source(world, entity, &source_abs) {
            console_error("Scene", format!(
                "Failed to save prefab source {}: {e}",
                source_abs.display()
            ));
        }
    }
}

/// Load the current project's main scene.
pub fn load_current_scene(world: &mut World) {
    let Some(project) = world.get_resource::<CurrentProject>() else {
        warn!("load_current_scene: no CurrentProject resource");
        return;
    };
    let path = project.main_scene_path();
    info!("load_current_scene: loading from {}", path.display());
    load_scene(world, &path);
}

// ============================================================================
// Rehydration
// ============================================================================

/// Rehydrate mesh primitives — spawns `Mesh3d` + `MeshMaterial3d` for entities that have
/// `MeshPrimitive` but no `Mesh3d` yet (e.g. after scene deserialization).
pub fn rehydrate_meshes(
    mut commands: Commands,
    query: Query<(Entity, &MeshPrimitive, Option<&MeshColor>), Without<Mesh3d>>,
    registry: Res<ShapeRegistry>,
    mut meshes: Option<ResMut<Assets<Mesh>>>,
    mut materials: Option<ResMut<Assets<StandardMaterial>>>,
) {
    let (Some(mut meshes), Some(mut materials)) = (meshes, materials) else { return };
    for (entity, primitive, color) in &query {
        let Some(mesh) = registry.create_mesh(&primitive.0, &mut meshes) else {
            warn!("Unknown shape ID '{}' — skipping rehydration", primitive.0);
            continue;
        };

        let base_color = color.map_or(Color::WHITE, |c| c.0);
        let material = materials.add(StandardMaterial {
            base_color,
            ..default()
        });

        commands.entity(entity).try_insert((Mesh3d(mesh), MeshMaterial3d(material)));
    }
}

/// Ensure parent entities have `Visibility` so transform/visibility propagation works.
/// Fixes groups/empty parents that were saved without `Visibility`.
pub fn rehydrate_visibility(
    mut commands: Commands,
    query: Query<Entity, (With<Children>, Without<Visibility>)>,
) {
    for entity in &query {
        commands.entity(entity).try_insert(Visibility::default());
    }
}

/// Rehydrate scene cameras — spawns `Camera3d` for entities that have `SceneCamera` but no `Camera3d`.
///
/// In runtime mode (no editor), the `DefaultCamera` is active; if none is marked,
/// the first scene camera wins. All others are inactive.
/// In editor mode, all scene cameras are inactive (the editor camera renders).
/// In play mode, the default camera becomes the active play mode camera with the
/// viewport render target.
pub fn rehydrate_cameras(
    mut commands: Commands,
    query: Query<(Entity, Option<&DefaultCamera>), (With<SceneCamera>, Without<Camera3d>)>,
    editor_camera: Query<(), With<EditorCamera>>,
    play_mode: Option<Res<PlayModeState>>,
    render_target: Option<Res<ViewportRenderTarget>>,
) {
    if query.is_empty() { return; }

    let in_play_mode = play_mode.as_ref().is_some_and(|pm| pm.is_in_play_mode());
    let is_editor = !editor_camera.is_empty() && !in_play_mode;

    // Find which entity should be the active camera in runtime mode
    let default_entity = query.iter()
        .find(|(_, dc)| dc.is_some())
        .or_else(|| query.iter().next())
        .map(|(e, _)| e);

    for (entity, _) in &query {
        let is_active = !is_editor && default_entity == Some(entity);

        commands.entity(entity).try_insert((
            Camera3d::default(),
            Camera {
                is_active,
                ..default()
            },
        ));

        // During play mode, configure the default camera as the play mode camera
        // with the viewport render target (mirrors what enter_play_mode does).
        if in_play_mode && is_active {
            use renzora::console_log::*;
            let name = commands.entity(entity).id();
            console_info("Rehydration", format!(
                "Play mode active — configuring {:?} as play mode camera", name
            ));
            commands.entity(entity).try_insert(PlayModeCamera);
            if let Some(ref img) = render_target.as_ref().and_then(|rt| rt.image.as_ref()) {
                commands.entity(entity).try_insert(
                    bevy::camera::RenderTarget::Image(Handle::<Image>::clone(img).into()),
                );
            }
        }
    }
}

/// Keeps `PlayModeState.active_game_camera` in sync when a scene transition
/// during play mode spawns a new `PlayModeCamera` entity.
pub fn sync_play_mode_camera(
    query: Query<Entity, Added<PlayModeCamera>>,
    play_mode: Option<ResMut<PlayModeState>>,
) {
    let Some(mut play_mode) = play_mode else { return; };
    for entity in &query {
        if play_mode.active_game_camera != Some(entity) {
            renzora::console_log::console_info("PlayMode", format!(
                "Play mode camera updated: {:?} -> {:?}", play_mode.active_game_camera, entity
            ));
            play_mode.active_game_camera = Some(entity);
        }
    }
}

/// Ensures only the default scene camera is active in runtime mode.
///
/// Runs every frame (cheap — early-exits if no changes). Handles cameras that
/// were deserialized with `Camera3d` already present (so `rehydrate_cameras` skipped them).
pub fn enforce_single_active_camera(
    mut cameras: Query<(Entity, &mut Camera, Option<&DefaultCamera>), With<SceneCamera>>,
    editor_camera: Query<(), With<EditorCamera>>,
) {
    if !editor_camera.is_empty() { return; }
    if cameras.is_empty() { return; }

    // Find which entity should be active: DefaultCamera > first
    let default_entity = cameras.iter()
        .find(|(_, _, dc)| dc.is_some())
        .or_else(|| cameras.iter().next())
        .map(|(e, _, _)| e);

    for (entity, mut camera, _) in &mut cameras {
        let should_be_active = default_entity == Some(entity);
        if camera.is_active != should_be_active {
            camera.is_active = should_be_active;
        }
    }
}

fn should_sync(type_path: &str) -> bool {
    type_path.ends_with("Settings")
}

/// Tracks the previous sync state so we only log when something changes.
#[derive(Resource, Default)]
struct SceneCameraSyncState {
    prev_src: Option<Entity>,
    prev_synced: BTreeSet<&'static str>,
}

/// Sync post-process (and other reflected) components from the **default**
/// SceneCamera entity to the EditorCamera.
///
/// In editor mode the viewport renders through the EditorCamera, but users attach
/// effects to the SceneCamera entity. This system mirrors those components so they
/// take effect during editing.
///
/// Skipped during play mode (the play-mode camera receives effects via
/// `RenderTarget` + the individual `sync_*` systems).
pub fn sync_scene_camera_to_editor_camera(world: &mut World) {
    // Skip during play mode — effects route through RenderTarget instead.
    let is_playing = world
        .get_resource::<PlayModeState>()
        .is_some_and(|pm| pm.is_in_play_mode());
    if is_playing {
        return;
    }

    // Find the editor camera.
    let mut editor_cam = None;
    let mut q = world.query_filtered::<Entity, With<EditorCamera>>();
    for e in q.iter(world) {
        editor_cam = Some(e);
        break;
    }
    let Some(dst) = editor_cam else {
        return;
    };

    // Find the scene camera — prefer DefaultCamera, fall back to first SceneCamera.
    let mut default_cam = None;
    let mut first_cam = None;
    let mut q = world.query_filtered::<(Entity, Option<&DefaultCamera>), With<SceneCamera>>();
    for (e, dc) in q.iter(world) {
        if dc.is_some() {
            default_cam = Some(e);
            break;
        }
        if first_cam.is_none() {
            first_cam = Some(e);
        }
    }
    let scene_cam = default_cam.or(first_cam);

    // If no scene camera exists, remove all synced components from the editor camera.
    let Some(src) = scene_cam else {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();
        let mut to_remove: Vec<bevy::ecs::reflect::ReflectComponent> = Vec::new();
        let editor_ref = world.entity(dst);
        for reg in registry.iter() {
            let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
                continue;
            };
            let type_path = reg.type_info().type_path();
            if !should_sync(type_path) {
                continue;
            }
            if reflect_component.contains(FilteredEntityRef::from(editor_ref)) {
                to_remove.push(reflect_component.clone());
            }
        }
        drop(registry);
        for reflect_component in &to_remove {
            reflect_component.remove(&mut world.entity_mut(dst));
        }
        return;
    };

    if src == dst {
        return;
    }

    let type_registry = world.resource::<AppTypeRegistry>().clone();
    let registry = type_registry.read();

    // Collect reflected component data from the scene camera.
    let mut components_to_sync: Vec<(
        bevy::ecs::reflect::ReflectComponent,
        Box<dyn Reflect>,
    )> = Vec::new();
    let mut synced_type_paths: Vec<&'static str> = Vec::new();

    let entity_ref = world.entity(src);
    for reg in registry.iter() {
        let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
            continue;
        };
        let type_path = reg.type_info().type_path();
        if !should_sync(type_path) {
            continue;
        }
        if let Some(reflected) = reflect_component.reflect(FilteredEntityRef::from(entity_ref)) {
            if let Ok(cloned) = reflected.reflect_clone() {
                components_to_sync.push((reflect_component.clone(), cloned));
                synced_type_paths.push(type_path);
            }
        }
    }
    drop(registry);

    // Apply collected components to the editor camera.
    {
        let registry = type_registry.read();
        for (reflect_component, value) in &components_to_sync {
            let mut entity_mut = world.entity_mut(dst);
            if reflect_component.contains(entity_mut.as_readonly()) {
                reflect_component.apply(entity_mut, value.as_partial_reflect());
            } else {
                reflect_component.insert(&mut entity_mut, value.as_partial_reflect(), &registry);
            }
        }
    }

    // Remove components from editor camera that were removed from scene camera.
    let registry = type_registry.read();
    let mut to_remove: Vec<(bevy::ecs::reflect::ReflectComponent, &'static str)> = Vec::new();
    let editor_ref = world.entity(dst);
    for reg in registry.iter() {
        let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
            continue;
        };
        let type_path = reg.type_info().type_path();
        if !should_sync(type_path) {
            continue;
        }
        if reflect_component.contains(FilteredEntityRef::from(editor_ref))
            && !synced_type_paths.contains(&type_path)
        {
            to_remove.push((reflect_component.clone(), type_path));
        }
    }
    drop(registry);

    // Only log when the source camera or set of synced types actually changes.
    let current_set: BTreeSet<&'static str> = synced_type_paths.iter().copied().collect();
    let removed_paths: Vec<&str> = to_remove.iter().map(|(_, p)| *p).collect();

    let mut state = world
        .remove_resource::<SceneCameraSyncState>()
        .unwrap_or_default();

    let src_changed = state.prev_src != Some(src);
    let set_changed = state.prev_synced != current_set;
    let has_removals = !removed_paths.is_empty();

    if src_changed || set_changed || has_removals {
        crate::debug_log::log_scene_camera_sync(
            Some(src),
            Some(dst),
            &synced_type_paths,
            &removed_paths,
        );
        if src_changed {
            let src_name = world
                .get::<Name>(src)
                .map(|n| n.to_string())
                .unwrap_or_else(|| "unnamed".into());
            let has_default = world.get::<DefaultCamera>(src).is_some();
            renzora::console_log::console_info(
                "PostProcess",
                format!(
                    "Sync source camera: {:?} \"{}\" default={}",
                    src, src_name, has_default
                ),
            );
        }
        state.prev_src = Some(src);
        state.prev_synced = current_set;
    }

    world.insert_resource(state);

    for (reflect_component, _) in &to_remove {
        reflect_component.remove(&mut world.entity_mut(dst));
    }
}

/// Rehydrate mesh instances — loads GLTF scenes for entities with `MeshInstanceData`
/// but no children yet (i.e. the GLTF scene hasn't been spawned).
///
/// Triggers on `Added<MeshInstanceData>` (scene load). Skips entities that already
/// have children (e.g. model_drop already spawned the SceneRoot child).
pub fn rehydrate_mesh_instances(
    mut commands: Commands,
    query: Query<(Entity, &MeshInstanceData), (Without<Children>, Without<PendingMeshInstanceRehydrate>, Added<MeshInstanceData>)>,
    asset_server: Res<AssetServer>,
) {
    for (entity, instance) in &query {
        let Some(ref model_path) = instance.model_path else {
            continue;
        };

        let gltf_handle: Handle<Gltf> = asset_server.load(model_path.clone());

        // We need to wait for the GLTF to load before spawning the scene.
        // Insert a pending-load marker so a follow-up system can spawn the scene child.
        commands.entity(entity).try_insert(PendingMeshInstanceRehydrate(gltf_handle));
    }
}

/// Marker: waiting for GLTF to finish loading so we can attach the scene child.
#[derive(Component)]
pub struct PendingMeshInstanceRehydrate(pub Handle<Gltf>);

/// Finishes mesh-instance rehydration once the GLTF asset is ready.
pub fn finish_mesh_instance_rehydrate(
    mut commands: Commands,
    query: Query<(Entity, &PendingMeshInstanceRehydrate)>,
    gltf_assets: Option<Res<Assets<Gltf>>>,
) {
    let Some(gltf_assets) = gltf_assets else { return };
    for (entity, pending) in &query {
        let Some(gltf) = gltf_assets.get(&pending.0) else {
            continue;
        };

        let scene_handle = gltf
            .default_scene
            .clone()
            .or_else(|| gltf.scenes.first().cloned());

        if let Some(scene) = scene_handle {
            commands.spawn((
                Name::new("SceneRoot"),
                bevy::scene::SceneRoot(scene),
                Transform::default(),
                Visibility::default(),
                ChildOf(entity),
            ));
        }

        commands.entity(entity).remove::<PendingMeshInstanceRehydrate>();
    }
}

/// Rehydrate sun entities — syncs `DirectionalLight` + `Transform` from `Sun` on newly added entities.
pub fn rehydrate_suns(
    mut query: Query<(&Sun, &mut DirectionalLight, &mut Transform), Added<Sun>>,
) {
    for (sun, mut light, mut transform) in &mut query {
        light.color = Color::srgb(sun.color.x, sun.color.y, sun.color.z);
        light.illuminance = sun.illuminance;
        light.shadows_enabled = sun.shadows_enabled;
        *transform = Transform::from_rotation(
            Quat::from_rotation_arc(Vec3::NEG_Z, sun.direction()),
        );
    }
}
