//! Renzora Runtime — shared engine library used by every Renzora binary.
//!
//! `add_engine_plugins(app)` iterates the `inventory`-backed plugin
//! registry (populated by `renzora::add!(...)` ctors at dylib load time)
//! and adds every plugin matching the host's scope (Runtime or Editor).
//! Plugins self-register via `renzora::add!(MyPlugin, scope)` in their
//! crate root — no manual enumeration here, no `add_plugins(...)` call
//! to remember.
//!
//! Adding a new plugin:
//! - Add a new crate, write `renzora::add!(MyPlugin)` (or `, Editor` for
//!   editor-only) in its `lib.rs`.
//! - Add the crate as a `[dependencies]` entry of `renzora_runtime` so the
//!   linker pulls it into the binary. Editor-only crates go under the
//!   `editor` feature.
//! - Third-party: ship as a dylib that uses `renzora::add!` — loaded at
//!   runtime by `dynamic_plugin_loader`, no engine source edits required.

use bevy::prelude::*;

pub use renzora;

// Always compiled now. Whether it's added is decided at RUNTIME by the
// `is_editor` arg to `add_engine_plugins` (the editor renders to its own
// offscreen image, so viewport stretch only applies to a shipped game).
mod render_scale;
mod viewport_stretch;

// Dylib keepalive: `pub use` every plugin crate so cargo emits a real
// dependency edge into this rlib's metadata, which propagates to the
// final binary's DT_NEEDED entries. The plugin dylibs need to actually
// be loaded at startup so their `inventory::submit!` ctors run and
// register entries into the shared plugin registry. The lists are
// generated by build.rs from this crate's own Cargo.toml — adding a new
// plugin only requires editing Cargo.toml, never this file.
include!(concat!(env!("OUT_DIR"), "/engine_reexports.rs"));

// ── App setup (single source of truth for engine plugin registration) ────

pub fn platform_wgpu_settings() -> bevy::render::settings::WgpuSettings {
    #[cfg(target_os = "android")]
    {
        use bevy::render::settings::{Backends, WgpuSettings};
        WgpuSettings {
            backends: Some(Backends::VULKAN),
            ..default()
        }
    }

    // Web: let Bevy's wasm defaults select WebGPU/WebGL. Pinning a native
    // backend (or requesting native-only features like POLYGON_MODE_LINE) here
    // would break the browser build.
    #[cfg(all(not(target_os = "android"), target_arch = "wasm32"))]
    {
        bevy::render::settings::WgpuSettings::default()
    }

    // Desktop (Windows / macOS / Linux / BSD).
    #[cfg(all(not(target_os = "android"), not(target_arch = "wasm32")))]
    {
        use bevy::render::settings::{Backends, WgpuFeatures, WgpuSettings};
        use renzora::RendererBackend;

        // Per-OS default, used when the preference is `Auto`. Vulkan is the
        // standard backend on Windows, Linux and the BSDs — it's the one path
        // shared across most platforms and gives the best experience here (fast
        // load, clean splash, no DX12 frame-flicker). The play-mode crash that
        // once pushed us toward DX12 was never Vulkan's fault: it came from
        // Bevy's default `Backends::all()` loading the DX12/DXGI backend
        // alongside Vulkan, and DXGI's occlusion handling clobbering the Vulkan
        // surface when the runtime window took the foreground. Pinning to a
        // single backend here — which `Auto` now always does — removes that, so
        // Vulkan is both the fastest and the safe default. DX12 remains a
        // user-selectable fallback for Windows machines with weak/missing Vulkan
        // drivers (see `RendererBackend`). Metal is the first-class (and only)
        // backend on Apple platforms.
        #[cfg(target_os = "windows")]
        let default_backend = Backends::VULKAN;
        #[cfg(any(target_os = "macos", target_os = "ios"))]
        let default_backend = Backends::METAL;
        #[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))]
        let default_backend = Backends::VULKAN;

        // User override persisted under `~/.renzora/renderer.toml`. Read here
        // because wgpu selects the backend at render-plugin build time and
        // can't change it afterwards; `Auto` keeps the per-OS default above.
        let backends = match renzora::load_renderer_backend() {
            RendererBackend::Auto => default_backend,
            RendererBackend::Dx12 => Backends::DX12,
            RendererBackend::Vulkan => Backends::VULKAN,
            RendererBackend::Metal => Backends::METAL,
            RendererBackend::Gl => Backends::GL,
        };

        // Wireframe (`PolygonMode::Line`) for the editor viewport — supported on
        // DX12, Vulkan and Metal but NOT OpenGL, so requesting it as a *required*
        // feature on the GL backend would leave wgpu unable to create a device.
        // Skip it there; GL users simply don't get wireframe.
        let mut features = if backends == Backends::GL {
            WgpuFeatures::empty()
        } else {
            WgpuFeatures::POLYGON_MODE_LINE
        };

        // Request Solari's hardware ray-tracing features when the adapter
        // supports them, so the `renzora_solari` plugin (if present) can build
        // its RT pipelines. Probed once (cached). On a non-RT GPU this is a
        // no-op and the engine boots exactly as before — requesting an
        // unsupported feature here would otherwise fail device creation, since
        // Bevy ORs `features` into `required_features` without intersecting.
        #[cfg(feature = "solari")]
        if raytracing_supported() {
            features |= bevy::solari::SolariPlugins::required_wgpu_features();
        }

        WgpuSettings {
            backends: Some(backends),
            features,
            ..default()
        }
    }
}

/// Whether the GPU + selected backend support the wgpu ray-tracing features
/// `bevy_solari` (Solari) needs. Probed ONCE at startup and cached.
///
/// Why a standalone probe instead of reading the live `RenderDevice`: the device
/// is created — with its feature set frozen — *before* any dlopen plugin loads,
/// so the only way the `renzora_solari` plugin can know in time to gate
/// `SolariPlugins` in its `build()` is for the host to find out first and stash
/// it in [`renzora::GpuRaytracing`]. We spin up a throwaway wgpu adapter on the
/// same backend the renderer will use and check it reports
/// `SolariPlugins::required_wgpu_features()`. Any failure ⇒ `false` (Solari
/// stays inert; the engine boots normally on non-RT GPUs).
#[cfg(all(not(target_os = "android"), not(target_arch = "wasm32"), feature = "solari"))]
pub fn raytracing_supported() -> bool {
    use std::sync::OnceLock;
    static SUPPORTED: OnceLock<bool> = OnceLock::new();
    *SUPPORTED.get_or_init(|| {
        use renzora::RendererBackend;
        use wgpu::Backends;

        // Mirror `platform_wgpu_settings`' backend selection so the probe sees
        // the same adapter the renderer will.
        #[cfg(target_os = "windows")]
        let default_backend = Backends::VULKAN;
        #[cfg(any(target_os = "macos", target_os = "ios"))]
        let default_backend = Backends::METAL;
        #[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))]
        let default_backend = Backends::VULKAN;

        let backends = match renzora::load_renderer_backend() {
            RendererBackend::Auto => default_backend,
            RendererBackend::Dx12 => Backends::DX12,
            RendererBackend::Vulkan => Backends::VULKAN,
            RendererBackend::Metal => Backends::METAL,
            RendererBackend::Gl => Backends::GL,
        };
        // OpenGL has no ray-tracing path — skip the probe entirely.
        if backends == Backends::GL {
            return false;
        }

        let required = bevy::solari::SolariPlugins::required_wgpu_features();
        // wgpu 29's `InstanceDescriptor` has no `Default`; start from its
        // defaults constructor and override only the backend.
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends,
            ..wgpu::InstanceDescriptor::new_without_display_handle()
        });
        let adapter = bevy::tasks::block_on(instance.request_adapter(
            &wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                force_fallback_adapter: false,
                compatible_surface: None,
            },
        ));
        match adapter {
            Ok(adapter) => {
                let ok = adapter.features().contains(required);
                if ok {
                    info!("[runtime] GPU ray tracing supported — Solari can run if its plugin is present");
                } else {
                    info!("[runtime] GPU ray tracing unsupported by adapter — Solari will stay inert");
                }
                ok
            }
            Err(e) => {
                info!("[runtime] ray-tracing probe found no adapter ({e}) — Solari will stay inert");
                false
            }
        }
    })
}

/// Non-desktop targets (Android / wasm), or a build with Solari stripped, have no
/// ray-tracing path here.
#[cfg(any(target_os = "android", target_arch = "wasm32", not(feature = "solari")))]
pub fn raytracing_supported() -> bool {
    false
}

pub fn init_app() -> App {
    let mut app = App::new();
    // Commands that fail (most commonly: a queued command targeting an entity
    // another system despawned in the same frame — overlays, live-rebuilt UI,
    // chrome rebuilds on theme switch) log a WARN and keep running instead of
    // taking the whole editor down. Bevy's default handler panics.
    app.set_error_handler(bevy::ecs::error::warn);
    renzora_engine::setup_asset_reader(&mut app);
    app
}

/// Clean log formatter for the exported (standalone) game.
///
/// The editor runs in a real terminal, so it keeps Bevy's default ANSI-colored
/// formatter. The exported game's output is usually read from a piped/redirected
/// console or a log file that doesn't interpret ANSI, where the defaults dump
/// raw escape sequences (`←[2m`, `←[32m`, …) on every line instead of colors,
/// which is the bulk of the unreadability. We turn ANSI off and use the
/// `.compact()` formatter, which drops the leading `system{name="…"}:` span-name
/// prefix, leaving plain `TIMESTAMP LEVEL target: message` lines.
fn runtime_fmt_layer(_app: &mut App) -> Option<bevy::log::BoxedFmtLayer> {
    use bevy::log::tracing_subscriber::fmt;
    Some(Box::new(
        fmt::Layer::default()
            .with_writer(std::io::stderr)
            .with_ansi(false)
            .event_format(fmt::format().with_ansi(false).compact()),
    ))
}

/// Editor fmt layer: keep Bevy's default ANSI formatter (the editor runs in a
/// real terminal). `None` tells `LogPlugin` to use its built-in formatter.
fn editor_fmt_layer(_app: &mut App) -> Option<bevy::log::BoxedFmtLayer> {
    None
}

/// Pre-initialize Bevy's IO task pool with a large per-thread stack **before**
/// `DefaultPlugins` (and its `TaskPoolPlugin`) runs.
///
/// Why: Bevy's async executor runs ready tasks *nested* inside a worker
/// thread's `block_on` call stack. While an IO worker is part-way through one
/// `bevy_gltf` load and that load awaits a sub-asset (image/buffer), the
/// executor will tick *another* queued GLTF load on the same call stack — and
/// `bevy_gltf`'s scene/node builder is itself recursive. Drop a handful of
/// models and the worst case is bounded; drag in *dozens* at once and a single
/// IO worker accumulates many recursive loads on one stack and overflows the
/// default 2 MiB thread stack ("IO Task Pool (N) has overflowed its stack").
/// The main thread never hit it because Windows gives it an 8 MiB stack.
///
/// `TaskPoolPlugin`/`TaskPoolOptions` (Bevy 0.18) does not plumb `stack_size`
/// through to the pool builders, so the supported way to set it is to win the
/// `get_or_init` race: initialize the pool ourselves here, and Bevy's later
/// `IoTaskPool::get_or_init` in `create_default_pools` becomes a no-op. We
/// mirror Bevy's default IO thread count (25% of cores, clamped to 1..=4) so
/// the compute/async split is unchanged — only the stack size differs.
fn init_io_task_pool_with_large_stack() {
    use bevy::tasks::{available_parallelism, IoTaskPool, TaskPoolBuilder};

    // 32 MiB: comfortable headroom for deeply-nested concurrent GLTF loads.
    // On 64-bit this is reserved address space, committed lazily per page, so
    // the real cost is only what the loads actually touch.
    const IO_STACK_SIZE: usize = 32 * 1024 * 1024;

    let cores = available_parallelism();
    // Match Bevy's default `io` policy: 25% of cores, at least 1, at most 4.
    let io_threads = ((cores as f32 * 0.25).round() as usize).clamp(1, 4);

    IoTaskPool::get_or_init(|| {
        TaskPoolBuilder::default()
            .num_threads(io_threads)
            .stack_size(IO_STACK_SIZE)
            .thread_name("IO Task Pool".to_string())
            .build()
    });
}

pub fn add_default_rendering(app: &mut App, is_editor: bool) {
    use bevy::render::{settings::RenderCreation, RenderPlugin};
    use bevy::window::{Window, WindowPlugin};
    // Must run before `DefaultPlugins` so we win the `IoTaskPool::get_or_init`
    // race — see the function doc for why the IO workers need a larger stack.
    init_io_task_pool_with_large_stack();
    let plugins = DefaultPlugins
            .set(RenderPlugin {
                render_creation: RenderCreation::Automatic(Box::new(platform_wgpu_settings())),
                ..default()
            })
            .set(ImagePlugin {
                default_sampler: bevy::image::ImageSamplerDescriptor {
                    address_mode_u: bevy::image::ImageAddressMode::Repeat,
                    address_mode_v: bevy::image::ImageAddressMode::Repeat,
                    address_mode_w: bevy::image::ImageAddressMode::Repeat,
                    // Trilinear + 16x anisotropic filtering by default. Bevy's
                    // default sampler runs with `anisotropy_clamp = 1` which
                    // looks blocky on textures viewed at oblique angles
                    // (brick walls, ground planes). Most assets here come from
                    // Sketchfab GLBs without baked mipmaps — anisotropy alone
                    // already cleans up the worst aliasing; full mipmap
                    // generation is a separate piece of work.
                    mag_filter: bevy::image::ImageFilterMode::Linear,
                    min_filter: bevy::image::ImageFilterMode::Linear,
                    mipmap_filter: bevy::image::ImageFilterMode::Linear,
                    anisotropy_clamp: 16,
                    ..default()
                },
            })
            // Allow loading assets from absolute paths outside a registered
            // source. Bevy's default (`Deny`) blocks it as a path-traversal
            // guard, but the editor legitimately loads absolute paths (the
            // custom `EmbeddedAssetReader` resolves them) — e.g. the marketplace
            // 3D preview stages a downloaded `.glb` into a temp cache and loads
            // it by absolute path. Mirrors `renzora_xr`.
            .set(bevy::asset::AssetPlugin {
                unapproved_path_mode: bevy::asset::UnapprovedPathMode::Allow,
                ..default()
            })
            .set(WindowPlugin {
                primary_window: Some(Window {
                    title: "Renzora".into(),
                    // Initial values — `apply_window_config` overwrites these
                    // from `CurrentProject` once the project is loaded. The
                    // editor draws its own title bar so it wants
                    // `decorations: false`; the runtime uses the OS title
                    // bar and needs decorations on **at creation time** so
                    // winit sizes the inner (renderable) area correctly.
                    // Flipping decorations on after the window exists makes
                    // Windows eat the title-bar height from the existing
                    // outer size, shrinking the render surface and causing
                    // sprites authored against window.width/height to clip
                    // off the right/bottom.
                    // Editor: false (it draws its own chrome). Runtime: true
                    // (OS title bar). Decided at runtime via `is_editor`.
                    decorations: !is_editor,
                    resizable: true,
                    ..default()
                }),
                ..default()
            });
    // Log layer:
    // - Desktop ALWAYS installs the Scene Diagnostics capture layer so the
    //   editor's "Recent Runtime Warnings" feed works. In a shipped game the
    //   buffer is simply never read (negligible cost) — installing it
    //   unconditionally avoids branching the `custom_layer` fn pointer on
    //   `is_editor`. The layer lives in `renzora` core (shared dylib) so the
    //   binary's writer and the bundle's reader touch one buffer.
    // - The fmt layer is the editor's default ANSI formatter (real terminal)
    //   or the exported game's plain, span-free formatter.
    let fmt_layer: fn(&mut App) -> Option<bevy::log::BoxedFmtLayer> =
        if is_editor { editor_fmt_layer } else { runtime_fmt_layer };
    let plugins = plugins.set(bevy::log::LogPlugin {
        #[cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))]
        custom_layer: renzora::runtime_warnings::runtime_warnings_layer,
        fmt_layer,
        ..default()
    });
    app.add_plugins(plugins);
    // Record GPU ray-tracing capability so the `renzora_solari` distribution
    // plugin can gate `SolariPlugins` in its `build()`. The `RenderDevice`'s
    // feature set is frozen here (before dlopen plugins load), so the plugin
    // can't probe the device itself in time — see `renzora::GpuRaytracing`.
    app.insert_resource(renzora::GpuRaytracing {
        enabled: raytracing_supported(),
    });
    // Render recovery (Bevy 0.19): by default any `RenderError` quits the app —
    // which means a GPU device-loss (driver reset, GPU hang, or an XR headset
    // disconnect / compositor reset) hard-crashes the editor or game. Override
    // the handler so a `DeviceLost` instead *recreates* the renderer with the
    // exact settings the engine booted with (`platform_wgpu_settings()`), and
    // every other fault keeps the app alive but stops rendering rather than
    // strobing on a persistent OOM/validation error. Only the GPU client path
    // installs this; the headless server has no renderer.
    {
        use bevy::render::error_handler::RenderErrorHandler;
        app.insert_resource(RenderErrorHandler(render_error_policy));
    }
    if is_editor {
        app.add_systems(Startup, maximize_primary_window);
    } else {
        // `apply_window_config` only touches the `Window` component, so it can
        // run on Startup. `apply_window_icon` needs `WinitWindows`, which is
        // only created after winit's `resumed` event fires — well after
        // `Startup` — so it has to live on `Update` and self-disable once
        // it's applied. Editor sessions skip both: the editor owns its chrome,
        // and otherwise the open project's window config would be applied to
        // the editor's own window.
        app.add_systems(Startup, apply_window_config);
        app.add_systems(Update, apply_window_icon);
    }
}

/// The renderer error policy (Bevy 0.19 `RenderErrorHandler`). It's a bare `fn`
/// pointer (no captured state), so it rebuilds the recovery `RenderCreation`
/// from the same `platform_wgpu_settings()` the app booted with — a recovered
/// device keeps the engine's custom features (e.g. `POLYGON_MODE_LINE`) instead
/// of silently falling back to Bevy defaults.
fn render_error_policy(
    error: &bevy::render::error_handler::RenderError,
    _main_world: &mut bevy::prelude::World,
    _render_world: &mut bevy::prelude::World,
) -> bevy::render::error_handler::RenderErrorPolicy {
    use bevy::render::error_handler::{ErrorType, RenderErrorPolicy};
    use bevy::render::settings::RenderCreation;
    match error.ty {
        // Recoverable: the device went away (driver reset / GPU hang / XR
        // compositor reset). Re-create the renderer and carry on — this is the
        // one case worth surviving silently.
        ErrorType::DeviceLost => {
            RenderErrorPolicy::Recover(RenderCreation::Automatic(Box::new(platform_wgpu_settings())))
        }
        // Transient surface/swapchain faults are expected during legitimate
        // reconfiguration — entering/leaving play mode, window resize, viewport
        // render-target swaps — where the surface texture is destroyed mid-submit
        // and re-acquired next frame. Tolerate those (`Ignore` drops the bad
        // frame and carries on); crashing on them would kill the editor every
        // time you press Esc out of play mode.
        _ if is_transient_surface_error(&error.description) => RenderErrorPolicy::Ignore,
        // Anything else is treated as a real bug: panic so the engine's crash
        // hook (`renzora_engine::crash`) saves a report + shows the native crash
        // window, rather than silently freezing (the old `StopRendering`) or
        // strobing (`Ignore` on a persistent fault).
        _ => panic!(
            "Unrecoverable GPU render error ({:?}): {}",
            error.ty, error.description
        ),
    }
}

/// Heuristic: is this render-validation error a transient surface/swapchain
/// reconfiguration fault (destroyed surface texture, outdated/lost swapchain)
/// rather than a real pipeline bug? Those self-resolve on the next frame, so we
/// tolerate them instead of crashing.
fn is_transient_surface_error(description: &str) -> bool {
    let d = description.to_lowercase();
    (d.contains("surface") && d.contains("destroyed"))
        || d.contains("surface texture")
        || d.contains("outdated")
        || d.contains("has been destroyed")
}

/// Headless plugin set for the dedicated server (`renzora-runtime --server`).
///
/// Same `DefaultPlugins` as the client so every engine plugin still finds the
/// types and resources it expects, but with three changes for headless:
///
/// - `backends: None` — Bevy detects no wgpu backend and skips renderer
///   initialization entirely (no adapter request, no `RenderDevice`, no
///   `RenderApp` sub-app), so it boots on machines with no GPU.
/// - `primary_window: None` — no surface.
/// - `WinitPlugin` disabled + `ScheduleRunnerPlugin` added — winit's event loop
///   fails to initialize on a headless Linux box (no X/Wayland), even with no
///   window. Dropping it and driving the app with a fixed-rate runner is what
///   makes the server actually deployable on a bare cloud VM.
///
/// This mirrors Godot's `--headless` (full renderer present, no driver active).
/// Plugins that touch the render sub-app must guard for its absence
/// (`get_sub_app_mut(RenderApp)`), exactly as Bevy's own render plugins do.
///
/// `tick_rate` (Hz) sets the runner's loop rate; it matches the network tick so
/// the server loop runs at the simulation cadence.
/// OpenXR/VR client plugin set — the `--vr` boot path (feature `xr`).
///
/// Mirrors [`add_default_rendering`]'s asset/image/log configuration but hands
/// render-plugin ownership to `bevy_mod_openxr` via [`renzora_xr::xr_plugins`]:
/// the OpenXR runtime dictates the graphics device, spawns the per-eye stereo
/// cameras targeting its swapchain, and drives frame pacing. Differences from
/// the flat path, each deliberate:
///
/// - **No `RenderPlugin`/`platform_wgpu_settings`** — device creation goes
///   through OpenXR; requesting our custom wgpu features there would need
///   `OxrInitPlugin` plumbing (future work; POLYGON_MODE_LINE debug wireframes
///   are simply absent in VR until then).
/// - **`PipelinedRenderingPlugin` disabled** — pipelining renders poses located
///   a frame earlier; in-headset that reads as the world lagging your head.
/// - **No render-error recovery** — the flat path's `DeviceLost` recovery
///   recreates a NON-XR renderer, which would silently drop out of the
///   headset; better to exit and let the user relaunch into VR.
/// - **`GpuRaytracing` forced off** — solari + VR frame budgets don't mix, and
///   the probe in `raytracing_supported()` describes a device we didn't create.
/// - Always a game session (`--vr` implies `--no-editor`), so the runtime
///   window-config systems apply as usual to the desktop mirror window.
#[cfg(feature = "xr")]
pub fn add_xr_rendering(app: &mut App) {
    use bevy::window::{PresentMode, Window, WindowPlugin};
    init_io_task_pool_with_large_stack();
    let base = DefaultPlugins
        .build()
        .disable::<bevy::render::pipelined_rendering::PipelinedRenderingPlugin>();
    let plugins = renzora_xr::xr_plugins(base)
        .set(ImagePlugin {
            default_sampler: bevy::image::ImageSamplerDescriptor {
                address_mode_u: bevy::image::ImageAddressMode::Repeat,
                address_mode_v: bevy::image::ImageAddressMode::Repeat,
                address_mode_w: bevy::image::ImageAddressMode::Repeat,
                mag_filter: bevy::image::ImageFilterMode::Linear,
                min_filter: bevy::image::ImageFilterMode::Linear,
                mipmap_filter: bevy::image::ImageFilterMode::Linear,
                anisotropy_clamp: 16,
                ..default()
            },
        })
        .set(bevy::asset::AssetPlugin {
            unapproved_path_mode: bevy::asset::UnapprovedPathMode::Allow,
            ..default()
        })
        .set(WindowPlugin {
            primary_window: Some(Window {
                title: "Renzora (VR)".into(),
                // The desktop window only hosts the spectator mirror — never
                // block the XR frame loop on the monitor's vsync.
                present_mode: PresentMode::AutoNoVsync,
                decorations: true,
                resizable: true,
                ..default()
            }),
            ..default()
        })
        .set(bevy::log::LogPlugin {
            #[cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))]
            custom_layer: renzora::runtime_warnings::runtime_warnings_layer,
            fmt_layer: runtime_fmt_layer,
            ..default()
        });
    app.add_plugins(plugins);
    app.add_plugins(renzora_xr::XrPlugin);
    app.insert_resource(renzora::GpuRaytracing { enabled: false });
}

pub fn add_headless_rendering(app: &mut App, tick_rate: u16) {
    use bevy::app::ScheduleRunnerPlugin;
    use bevy::log::LogPlugin;
    use bevy::render::{
        settings::{RenderCreation, WgpuSettings},
        RenderPlugin,
    };
    use bevy::window::{ExitCondition, WindowPlugin};
    use core::time::Duration;

    // Same rationale as the client path: a dedicated server loading a large
    // scene fans out many concurrent GLTF loads onto the IO pool, so its
    // workers need the larger stack too. Must precede `DefaultPlugins`.
    init_io_task_pool_with_large_stack();

    app.add_plugins(
        DefaultPlugins
            .set(RenderPlugin {
                render_creation: RenderCreation::Automatic(Box::new(WgpuSettings {
                    backends: None,
                    ..default()
                })),
                ..default()
            })
            .set(WindowPlugin {
                primary_window: None,
                exit_condition: ExitCondition::DontExit,
                ..default()
            })
            // Silence the noise that's expected with no render world: Bevy's
            // render plugins log loudly when the `RenderApp` is absent. None of
            // it matters on a headless server. Keeps the rest of the default
            // INFO logging.
            .set(LogPlugin {
                filter: "wgpu=error,naga=warn,\
                         bevy_log=error,\
                         bevy_render::extract_resource=off,\
                         bevy_gizmos_render=off,\
                         bevy_render::texture=off,\
                         bevy_gltf=off"
                    .to_string(),
                ..default()
            })
            .disable::<bevy::winit::WinitPlugin>(),
    );

    let wait = Duration::from_secs_f64(1.0 / tick_rate.max(1) as f64);
    app.add_plugins(ScheduleRunnerPlugin::run_loop(wait));
}

fn maximize_primary_window(
    mut windows: Query<&mut bevy::window::Window, With<bevy::window::PrimaryWindow>>,
) {
    if let Ok(mut window) = windows.single_mut() {
        window.set_maximized(true);
    }
}

/// Apply `CurrentProject.config.window` to the primary window at runtime startup.
///
/// The runtime template ships pre-built — every project would otherwise see
/// the same hardcoded "Renzora", `decorations: false`, maximized layout. This
/// system reads the project config (loaded from the rpak by `RuntimePlugin`
/// before `Startup` runs) and applies the user's choices.
fn apply_window_config(
    project: Option<Res<renzora::CurrentProject>>,
    mut windows: Query<&mut bevy::window::Window, With<bevy::window::PrimaryWindow>>,
) {
    use bevy::window::WindowMode as BevyWindowMode;

    let Ok(mut window) = windows.single_mut() else {
        return;
    };
    let Some(project) = project else {
        warn!("[runtime] No project loaded — window config not applied");
        return;
    };

    if project.config.console_logging {
        attach_console();
    }

    let cfg = &project.config.window;
    window.title = project.config.name.clone();
    window.resizable = cfg.resizable;
    window.resolution.set(cfg.width as f32, cfg.height as f32);

    match cfg.mode {
        renzora::WindowMode::Windowed => {
            window.decorations = true;
            window.mode = BevyWindowMode::Windowed;
        }
        renzora::WindowMode::Fullscreen => {
            window.decorations = false;
            window.mode =
                BevyWindowMode::BorderlessFullscreen(bevy::window::MonitorSelection::Current);
        }
        renzora::WindowMode::Borderless => {
            window.decorations = false;
            window.mode = BevyWindowMode::Windowed;
        }
    }
}

/// Attach a console window so subsequent stdout/stderr (Bevy log output) is
/// visible. On Windows the runtime is built with `windows_subsystem = "windows"`
/// for release, so without this call there's no console at all. We try
/// `AttachConsole(ATTACH_PARENT_PROCESS)` first so launching from cmd.exe pipes
/// output to that terminal; if there's no parent console we fall back to
/// `AllocConsole`. No-op on platforms where stdout already works.
#[cfg(target_os = "windows")]
pub fn attach_console() {
    use std::sync::atomic::{AtomicBool, Ordering};
    static ATTACHED: AtomicBool = AtomicBool::new(false);
    if ATTACHED.swap(true, Ordering::SeqCst) {
        return;
    }

    const ATTACH_PARENT_PROCESS: u32 = 0xFFFF_FFFF;
    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn AttachConsole(dw_process_id: u32) -> i32;
        fn AllocConsole() -> i32;
    }

    unsafe {
        if AttachConsole(ATTACH_PARENT_PROCESS) == 0 {
            AllocConsole();
        }
    }
}

#[cfg(not(target_os = "windows"))]
pub fn attach_console() {
    // stdout is always live on Linux/macOS; no console to allocate.
}

/// Apply the icon referenced by `project.config.icon` to the primary window.
///
/// Bevy 0.18 has no public window-icon API on `Window`, so we drop down to
/// winit via `WinitWindows`. The icon is read from the VFS (rpak) so it
/// works the same whether the project ships single-binary or split.
///
/// `WinitWindows` is created lazily by `bevy_winit` after the winit `resumed`
/// event, which is past `Startup`. The system therefore runs on `Update`,
/// wraps the resource in `Option`, and a `Local<bool>` flag short-circuits
/// once the icon has been applied (or once we've decided there's nothing to
/// apply).
fn apply_window_icon(
    mut applied: Local<bool>,
    project: Option<Res<renzora::CurrentProject>>,
    primary: Query<Entity, With<bevy::window::PrimaryWindow>>,
    windows: Option<NonSend<bevy::winit::WinitWindows>>,
    vfs: Option<Res<renzora_engine::vfs::Vfs>>,
) {
    if *applied {
        return;
    }
    let Some(windows) = windows else { return };
    let Some(project) = project else { return };
    let Some(icon_rel) = project.config.icon.as_deref() else {
        // No icon configured — nothing to do, but mark as applied so we stop
        // re-running this every frame.
        *applied = true;
        return;
    };

    // Try the VFS first (rpak), then fall back to disk for `--project` runs.
    let bytes = vfs
        .as_ref()
        .and_then(|v| v.read(icon_rel))
        .or_else(|| std::fs::read(project.path.join(icon_rel)).ok());
    let Some(bytes) = bytes else {
        warn!("[runtime] Window icon not found: {}", icon_rel);
        *applied = true;
        return;
    };

    let img = match image::load_from_memory(&bytes) {
        Ok(i) => i.into_rgba8(),
        Err(e) => {
            warn!("[runtime] Failed to decode icon {}: {}", icon_rel, e);
            *applied = true;
            return;
        }
    };
    let (w, h) = img.dimensions();
    let icon = match winit::window::Icon::from_rgba(img.into_raw(), w, h) {
        Ok(i) => i,
        Err(e) => {
            warn!("[runtime] Invalid icon dimensions {}x{}: {}", w, h, e);
            *applied = true;
            return;
        }
    };

    let Ok(entity) = primary.single() else {
        // Window entity not yet spawned — try again next frame.
        return;
    };
    let Some(window) = windows.get_window(entity) else {
        // WinitWindow not yet bound to entity — try again next frame.
        return;
    };
    window.set_window_icon(Some(icon));
    *applied = true;
}

/// Adds every engine plugin to the App.
///
/// Foundation plugins are listed explicitly here in dependency order —
/// each one initializes a resource (or otherwise sets up state) that
/// other plugins read during their own `Plugin::build()`. They have to
/// run first, in this exact order. Then the rest of the workspace
/// plugins are auto-discovered via the `inventory` registry — those
/// don't care about ordering and just self-register through
/// `renzora::add!(MyPlugin)` in their crate.
pub fn add_engine_plugins(app: &mut App, is_editor: bool) {
    // Runtime editor-vs-game signal for the dual-mode crates (they're compiled
    // without an `editor` cargo feature now, so they branch on this at runtime).
    // Must exist BEFORE the foundation plugins build — RuntimePlugin reads it.
    app.insert_resource(renzora::EditorSession(is_editor));

    // ── Foundation (explicit, ordered) ─────────────────────────────────
    info!("[runtime] foundation: RuntimePlugin");
    app.add_plugins(renzora_engine::RuntimePlugin);
    info!("[runtime] foundation: GlobalsPlugin");
    app.add_plugins(renzora_globals::GlobalsPlugin);
    info!("[runtime] foundation: InputPlugin");
    app.add_plugins(renzora_input::InputPlugin);
    info!("[runtime] foundation: ScriptingPlugin");
    app.add_plugins(renzora_scripting::ScriptingPlugin::default());
    #[cfg(feature = "physics")]
    {
        info!("[runtime] foundation: PhysicsPlugin");
        app.add_plugins(renzora_physics::PhysicsPlugin);
    }

    // Font scripting: `action("set_ui_font"/"set_font", {name=...})`.
    app.add_observer(handle_font_script_actions);
    // Shipped game adopts the project's default UI font.
    app.add_systems(Update, apply_game_ui_font);

    // Viewport stretch: pixel-art game scaling. Only meaningful in
    // runtime builds (the editor renders to its own offscreen image
    // via `ViewportRenderTarget`, separate concern). The plugin is
    // a no-op when `project.viewport.stretch_mode == Disabled`.
    if !is_editor {
        info!("[runtime] foundation: ViewportStretchPlugin");
        app.add_plugins(viewport_stretch::ViewportStretchPlugin);
        info!("[runtime] foundation: RenderScalePlugin");
        app.add_plugins(render_scale::RenderScalePlugin);
    }

    // ── Auto-discovered (any order) ────────────────────────────────────
    renzora::for_each_static_plugin(renzora::PluginScope::Runtime, |plugin| {
        info!("[runtime] static plugin: {}", plugin.name);
        (plugin.install)(app);
    });
}

/// Resolve a font name to a render source for scripting. Prefers the editor's
/// `FontRegistry` (named built-ins + project fonts); otherwise treats a value
/// ending in `.ttf`/`.otf` or containing `/` as a project asset path and
/// anything else as a system family name — so it also works in a shipped game.
fn resolve_script_font(
    name: &str,
    registry: Option<&renzora_ember::font::FontRegistry>,
    asset: &AssetServer,
) -> bevy::text::FontSource {
    use bevy::text::{Font, FontSource};
    if let Some(r) = registry {
        if let Some(src) = r.resolve(name) {
            return src;
        }
    }
    let lower = name.to_ascii_lowercase();
    if lower.ends_with(".ttf") || lower.ends_with(".otf") || name.contains('/') {
        FontSource::Handle(asset.load::<Font>(name.to_string()))
    } else {
        FontSource::Family(name.into())
    }
}

/// Apply font script actions. Scripts call them via the always-available
/// generic action helper:
/// - `action("set_ui_font", {name="Inter"})` — swap the global UI font.
/// - `action("set_font", {name="Inter"})` — set the script's own entity's font.
///
/// `name` resolves through [`resolve_script_font`] (registry / asset path /
/// system family). Runs in the editor and shipped games.
fn handle_font_script_actions(
    trigger: On<renzora::ScriptAction>,
    registry: Option<Res<renzora_ember::font::FontRegistry>>,
    asset: Res<AssetServer>,
    mut fonts: Option<ResMut<renzora_ember::font::EmberFonts>>,
    mut text_q: Query<&mut bevy::text::TextFont>,
) {
    let action = trigger.event();
    if !matches!(action.name.as_str(), "set_ui_font" | "set_font") {
        return;
    }
    let name = match action.args.get("name") {
        Some(renzora::ScriptActionValue::String(s)) => s.clone(),
        _ => return,
    };
    let src = resolve_script_font(&name, registry.as_deref(), &asset);

    match action.name.as_str() {
        "set_ui_font" => {
            if let Some(fonts) = fonts.as_mut() {
                if src != fonts.ui {
                    let old = std::mem::replace(&mut fonts.ui, src.clone());
                    for mut tf in &mut text_q {
                        if tf.font == old {
                            tf.font = src.clone();
                        }
                    }
                }
            }
        }
        "set_font" => {
            if let Ok(mut tf) = text_q.get_mut(action.entity) {
                tf.font = src;
            }
        }
        _ => {}
    }
}

/// Apply the project's default UI font (`ProjectConfig.ui_font`) at game
/// startup. Editor sessions use the per-user editor font (EditorSettings) and
/// are skipped; only the shipped game adopts the project default. Runs once,
/// after the project + fonts are ready.
fn apply_game_ui_font(
    mut done: Local<bool>,
    session: Option<Res<renzora::EditorSession>>,
    project: Option<Res<renzora::CurrentProject>>,
    registry: Option<Res<renzora_ember::font::FontRegistry>>,
    asset: Res<AssetServer>,
    fonts: Option<ResMut<renzora_ember::font::EmberFonts>>,
    mut text_q: Query<&mut bevy::text::TextFont>,
) {
    if *done {
        return;
    }
    // Editor uses EditorSettings.ui_font — only the shipped game adopts the
    // project default.
    if session.map(|s| s.0).unwrap_or(false) {
        *done = true;
        return;
    }
    let Some(project) = project else {
        return; // wait for the project to load
    };
    let Some(name) = project.config.ui_font.clone() else {
        *done = true; // no project default → keep the embedded font
        return;
    };
    let Some(mut fonts) = fonts else {
        return; // fonts not ready
    };
    let src = resolve_script_font(&name, registry.as_deref(), &asset);
    if src != fonts.ui {
        let old = std::mem::replace(&mut fonts.ui, src.clone());
        for mut tf in &mut text_q {
            if tf.font == old {
                tf.font = src.clone();
            }
        }
    }
    *done = true;
}

/// Build the full runtime app (rendering + all engine plugins).
pub fn build_runtime_app() -> App {
    let mut app = init_app();
    // mobile/wasm entry point — always a shipped game, never the editor.
    add_default_rendering(&mut app, false);
    add_engine_plugins(&mut app, false);
    app
}

// Editor plugins are NOT installed here. They live in the separate
// `renzora_editor` bundle dll (loaded at startup beside the exe) and are
// installed via its `plugin_install_scope` FFI entry with `host_scope = Editor`.
// `renzora_runtime` is purely the runtime foundation.
