//! Renzora Runtime — shared engine library used by every Renzora binary.
//!
//! `add_engine_plugins(app)` iterates the `inventory`-backed plugin
//! registry (populated by `renzora::add!(...)` ctors at dylib load time)
//! and adds every plugin matching the host's scope (Runtime or Editor).
//! Plugins self-register via `renzora::add!(MyPlugin, scope)` in their
//! crate root — no manual enumeration here, no `add_plugins(...)` call
//! to remember.
//!
//! Adding a new plugin:
//! - Add a new crate, write `renzora::add!(MyPlugin)` (or `, Editor` for
//!   editor-only) in its `lib.rs`.
//! - Add the crate as a `[dependencies]` entry of `renzora_runtime` so the
//!   linker pulls it into the binary. Editor-only crates go under the
//!   `editor` feature.
//! - Third-party: ship as a dylib that uses `renzora::add!` — loaded at
//!   runtime by `dynamic_plugin_loader`, no engine source edits required.

use bevy::prelude::*;

pub use renzora;

// Dylib keepalive: `pub use` every plugin crate so cargo emits a real
// dependency edge into this rlib's metadata, which propagates to the
// final binary's DT_NEEDED entries. The plugin dylibs need to actually
// be loaded at startup so their `inventory::submit!` ctors run and
// register entries into the shared plugin registry. The lists are
// generated by build.rs from this crate's own Cargo.toml — adding a new
// plugin only requires editing Cargo.toml, never this file.
include!(concat!(env!("OUT_DIR"), "/engine_reexports.rs"));

#[cfg(feature = "editor")]
mod editor_reexports {
    include!(concat!(env!("OUT_DIR"), "/editor_reexports.rs"));
}
#[cfg(feature = "editor")]
pub use editor_reexports::*;

// ── App setup (single source of truth for engine plugin registration) ────

pub fn platform_wgpu_settings() -> bevy::render::settings::WgpuSettings {
    #[cfg(target_os = "android")]
    {
        use bevy::render::settings::{Backends, WgpuSettings};
        WgpuSettings {
            backends: Some(Backends::VULKAN),
            ..default()
        }
    }

    #[cfg(not(target_os = "android"))]
    {
        use bevy::render::settings::{WgpuFeatures, WgpuSettings};
        WgpuSettings {
            features: WgpuFeatures::POLYGON_MODE_LINE,
            ..default()
        }
    }
}

pub fn init_app() -> App {
    let mut app = App::new();
    renzora_engine::setup_asset_reader(&mut app);
    app
}

pub fn add_default_rendering(app: &mut App) {
    use bevy::render::{settings::RenderCreation, RenderPlugin};
    use bevy::window::{Window, WindowPlugin};
    app.add_plugins(
        DefaultPlugins
            .set(RenderPlugin {
                render_creation: RenderCreation::Automatic(platform_wgpu_settings()),
                ..default()
            })
            .set(ImagePlugin {
                default_sampler: bevy::image::ImageSamplerDescriptor {
                    address_mode_u: bevy::image::ImageAddressMode::Repeat,
                    address_mode_v: bevy::image::ImageAddressMode::Repeat,
                    address_mode_w: bevy::image::ImageAddressMode::Repeat,
                    // Trilinear + 16x anisotropic filtering by default. Bevy's
                    // default sampler runs with `anisotropy_clamp = 1` which
                    // looks blocky on textures viewed at oblique angles
                    // (brick walls, ground planes). Most assets here come from
                    // Sketchfab GLBs without baked mipmaps — anisotropy alone
                    // already cleans up the worst aliasing; full mipmap
                    // generation is a separate piece of work.
                    mag_filter: bevy::image::ImageFilterMode::Linear,
                    min_filter: bevy::image::ImageFilterMode::Linear,
                    mipmap_filter: bevy::image::ImageFilterMode::Linear,
                    anisotropy_clamp: 16,
                    ..default()
                },
                ..default()
            })
            .set(WindowPlugin {
                primary_window: Some(Window {
                    title: "Renzora".into(),
                    // Initial values — `apply_window_config` overwrites these
                    // from `CurrentProject` once the project is loaded. The
                    // editor draws its own title bar so it wants
                    // `decorations: false`; the runtime uses the OS title
                    // bar and needs decorations on **at creation time** so
                    // winit sizes the inner (renderable) area correctly.
                    // Flipping decorations on after the window exists makes
                    // Windows eat the title-bar height from the existing
                    // outer size, shrinking the render surface and causing
                    // sprites authored against window.width/height to clip
                    // off the right/bottom.
                    #[cfg(feature = "editor")]
                    decorations: false,
                    #[cfg(not(feature = "editor"))]
                    decorations: true,
                    resizable: true,
                    ..default()
                }),
                ..default()
            }),
    );
    #[cfg(feature = "editor")]
    app.add_systems(Startup, maximize_primary_window);
    #[cfg(not(feature = "editor"))]
    {
        // `apply_window_config` only touches the `Window` component, so it can
        // run on Startup. `apply_window_icon` needs `WinitWindows`, which is
        // only created after winit's `resumed` event fires — well after
        // `Startup` — so it has to live on `Update` and self-disable once
        // it's applied.
        app.add_systems(Startup, apply_window_config);
        app.add_systems(Update, apply_window_icon);
    }
}

#[cfg(feature = "editor")]
fn maximize_primary_window(
    mut windows: Query<&mut bevy::window::Window, With<bevy::window::PrimaryWindow>>,
) {
    if let Ok(mut window) = windows.single_mut() {
        window.set_maximized(true);
    }
}

/// Apply `CurrentProject.config.window` to the primary window at runtime startup.
///
/// The runtime template ships pre-built — every project would otherwise see
/// the same hardcoded "Renzora", `decorations: false`, maximized layout. This
/// system reads the project config (loaded from the rpak by `RuntimePlugin`
/// before `Startup` runs) and applies the user's choices.
#[cfg(not(feature = "editor"))]
fn apply_window_config(
    project: Option<Res<renzora::CurrentProject>>,
    mut windows: Query<&mut bevy::window::Window, With<bevy::window::PrimaryWindow>>,
) {
    use bevy::window::WindowMode as BevyWindowMode;

    let Ok(mut window) = windows.single_mut() else {
        return;
    };
    let Some(project) = project else {
        warn!("[runtime] No project loaded — window config not applied");
        return;
    };

    if project.config.console_logging {
        attach_console();
    }

    let cfg = &project.config.window;
    window.title = project.config.name.clone();
    window.resizable = cfg.resizable;
    window.resolution.set(cfg.width as f32, cfg.height as f32);

    match cfg.mode {
        renzora::WindowMode::Windowed => {
            window.decorations = true;
            window.mode = BevyWindowMode::Windowed;
        }
        renzora::WindowMode::Fullscreen => {
            window.decorations = false;
            window.mode = BevyWindowMode::BorderlessFullscreen(
                bevy::window::MonitorSelection::Current,
            );
        }
        renzora::WindowMode::Borderless => {
            window.decorations = false;
            window.mode = BevyWindowMode::Windowed;
        }
    }
}

/// Attach a console window so subsequent stdout/stderr (Bevy log output) is
/// visible. On Windows the runtime is built with `windows_subsystem = "windows"`
/// for release, so without this call there's no console at all. We try
/// `AttachConsole(ATTACH_PARENT_PROCESS)` first so launching from cmd.exe pipes
/// output to that terminal; if there's no parent console we fall back to
/// `AllocConsole`. No-op on platforms where stdout already works.
#[cfg(all(target_os = "windows", not(feature = "editor")))]
fn attach_console() {
    use std::sync::atomic::{AtomicBool, Ordering};
    static ATTACHED: AtomicBool = AtomicBool::new(false);
    if ATTACHED.swap(true, Ordering::SeqCst) {
        return;
    }

    const ATTACH_PARENT_PROCESS: u32 = 0xFFFF_FFFF;
    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn AttachConsole(dw_process_id: u32) -> i32;
        fn AllocConsole() -> i32;
    }

    unsafe {
        if AttachConsole(ATTACH_PARENT_PROCESS) == 0 {
            AllocConsole();
        }
    }
}

#[cfg(all(
    not(feature = "editor"),
    not(all(target_os = "windows", not(feature = "editor")))
))]
fn attach_console() {
    // stdout is always live on Linux/macOS; no console to allocate.
}

/// Apply the icon referenced by `project.config.icon` to the primary window.
///
/// Bevy 0.18 has no public window-icon API on `Window`, so we drop down to
/// winit via `WinitWindows`. The icon is read from the VFS (rpak) so it
/// works the same whether the project ships single-binary or split.
///
/// `WinitWindows` is created lazily by `bevy_winit` after the winit `resumed`
/// event, which is past `Startup`. The system therefore runs on `Update`,
/// wraps the resource in `Option`, and a `Local<bool>` flag short-circuits
/// once the icon has been applied (or once we've decided there's nothing to
/// apply).
#[cfg(not(feature = "editor"))]
fn apply_window_icon(
    mut applied: Local<bool>,
    project: Option<Res<renzora::CurrentProject>>,
    primary: Query<Entity, With<bevy::window::PrimaryWindow>>,
    windows: Option<NonSend<bevy::winit::WinitWindows>>,
    vfs: Option<Res<renzora_engine::vfs::Vfs>>,
) {
    if *applied {
        return;
    }
    let Some(windows) = windows else { return };
    let Some(project) = project else { return };
    let Some(icon_rel) = project.config.icon.as_deref() else {
        // No icon configured — nothing to do, but mark as applied so we stop
        // re-running this every frame.
        *applied = true;
        return;
    };

    // Try the VFS first (rpak), then fall back to disk for `--project` runs.
    let bytes = vfs
        .as_ref()
        .and_then(|v| v.read(icon_rel))
        .or_else(|| std::fs::read(project.path.join(icon_rel)).ok());
    let Some(bytes) = bytes else {
        warn!("[runtime] Window icon not found: {}", icon_rel);
        *applied = true;
        return;
    };

    let img = match image::load_from_memory(&bytes) {
        Ok(i) => i.into_rgba8(),
        Err(e) => {
            warn!("[runtime] Failed to decode icon {}: {}", icon_rel, e);
            *applied = true;
            return;
        }
    };
    let (w, h) = img.dimensions();
    let icon = match winit::window::Icon::from_rgba(img.into_raw(), w, h) {
        Ok(i) => i,
        Err(e) => {
            warn!("[runtime] Invalid icon dimensions {}x{}: {}", w, h, e);
            *applied = true;
            return;
        }
    };

    let Ok(entity) = primary.single() else {
        // Window entity not yet spawned — try again next frame.
        return;
    };
    let Some(window) = windows.get_window(entity) else {
        // WinitWindow not yet bound to entity — try again next frame.
        return;
    };
    window.set_window_icon(Some(icon));
    *applied = true;
}

/// Adds every engine plugin to the App.
///
/// Foundation plugins are listed explicitly here in dependency order —
/// each one initializes a resource (or otherwise sets up state) that
/// other plugins read during their own `Plugin::build()`. They have to
/// run first, in this exact order. Then the rest of the workspace
/// plugins are auto-discovered via the `inventory` registry — those
/// don't care about ordering and just self-register through
/// `renzora::add!(MyPlugin)` in their crate.
pub fn add_engine_plugins(app: &mut App) {
    // ── Foundation (explicit, ordered) ─────────────────────────────────
    info!("[runtime] foundation: RuntimePlugin");
    app.add_plugins(renzora_engine::RuntimePlugin);
    info!("[runtime] foundation: GlobalsPlugin");
    app.add_plugins(renzora_globals::GlobalsPlugin::default());
    info!("[runtime] foundation: InputPlugin");
    app.add_plugins(renzora_input::InputPlugin::default());
    info!("[runtime] foundation: ScriptingPlugin");
    app.add_plugins(renzora_scripting::ScriptingPlugin::default());
    info!("[runtime] foundation: PhysicsPlugin");
    app.add_plugins(renzora_physics::PhysicsPlugin::default());

    // ── Auto-discovered (any order) ────────────────────────────────────
    renzora::for_each_static_plugin(renzora::PluginScope::Runtime, |plugin| {
        info!("[runtime] static plugin: {}", plugin.name);
        (plugin.install)(app);
    });
}

/// Build the full runtime app (rendering + all engine plugins).
pub fn build_runtime_app() -> App {
    let mut app = init_app();
    add_default_rendering(&mut app);
    add_engine_plugins(&mut app);
    app
}

// ── Editor plugin registration (only present when `editor` feature is on) ─

/// Adds every editor-scope plugin to the App.
///
/// Foundation plugins are listed explicitly here — they initialize the
/// editor's shared registries (`ViewportOverlayRegistry`,
/// `ToolOptionsRegistry`, `ShortcutRegistry`, `KeyBindings`, ...) that
/// downstream editor plugins read during their own `Plugin::build()`.
/// The rest are auto-discovered through `inventory`.
#[cfg(feature = "editor")]
pub fn add_editor_plugins(app: &mut App) {
    // ── Foundation (explicit, ordered) ─────────────────────────────────
    info!("[editor] foundation: AssetRegistryPlugin");
    app.add_plugins(renzora_asset_registry::AssetRegistryPlugin::default());
    info!("[editor] foundation: RenzoraEditorPlugin");
    app.add_plugins(renzora_editor::RenzoraEditorPlugin::default());
    info!("[editor] foundation: KeybindingsPlugin");
    app.add_plugins(renzora_keybindings::KeybindingsPlugin::default());

    // ── Auto-discovered (any order) ────────────────────────────────────
    renzora::for_each_static_plugin(renzora::PluginScope::Editor, |plugin| {
        info!("[editor] static plugin: {}", plugin.name);
        (plugin.install)(app);
    });
}
