//! Write what the editor created back into the project, as Rust.
//!
//! The editor is not a viewer. Place a rock in the viewport of a Bevy project
//! and it has to end up in the repository, in the language the repository is
//! written in, compiled by `cargo run` like everything else. Otherwise the
//! placement lives only in a running process and is gone at the next restart.
//!
//! So Save writes `<project>/src/renzora_authored.rs`: an ordinary Bevy plugin
//! that spawns what you placed.
//!
//! ```ignore
//! // src/renzora_authored.rs: generated by Renzora. Do not edit.
//! pub struct AuthoredScenePlugin;
//!
//! impl Plugin for AuthoredScenePlugin {
//!     fn build(&self, app: &mut App) {
//!         app.add_systems(Startup, spawn);
//!     }
//! }
//!
//! fn spawn(mut commands: Commands, assets: Res<AssetServer>) {
//!     commands.spawn((
//!         Name::new("Rock"),
//!         Transform::from_xyz(4.0, 0.0, -2.0),
//!         WorldAssetRoot(assets.load("models/nature/rock_largeA.glb#Scene0")),
//!     ));
//! }
//! ```
//!
//! That is code you could read, diff, and paste into your own file if you
//! decided to take ownership of it. It is deliberately plain: no engine types,
//! no macros, nothing that stops it compiling in a checkout that has never seen
//! Renzora.
//!
//! # What it will not do, and why
//!
//! **It does not touch a line you wrote.** The generated module is the only file
//! it writes, and the only file it will ever write.
//!
//! That is not timidity, it is the shape of the problem. A Bevy project's world
//! is *computed*: the grove this was built against places its trees from a
//! seeded PCG inside a loop, so the tree you just dragged two metres has no line
//! of source to edit: it has an iteration index and a random number. Writing an
//! edit back into that code would mean either rewriting the generator (which
//! changes every other tree) or appending an override that contradicts it. There
//! is no honest third option, so entities from your own code are shown, are live,
//! and are not persisted; only what the editor created is written.
//!
//! [`renzora::core::bevy_project::AuthoredByEditor`] is the line between the two,
//! and it is decided when an entity appears rather than here, because by then
//! there is nothing left to tell them apart by.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use bevy::asset::UntypedAssetId;
use bevy::prelude::*;
use renzora::core::bevy_project::AuthoredByEditor;
use renzora::core::{HideInHierarchy, Persistent};

/// The generated module's file name, without the extension.
///
/// Lives in `src/` and not in `.renzora/` because the whole point is that it is
/// part of the crate: `cargo run` has to compile it, and a build directory is
/// the one place that would never happen.
pub const MODULE: &str = "renzora_authored";

/// The plugin type the generated module exports.
pub const PLUGIN: &str = "AuthoredScenePlugin";

/// Everything the writer knows how to put into Rust, read off one entity.
///
/// Deliberately a small, closed set. A generator that tries to serialise every
/// component it finds produces code referring to types the project has never
/// heard of, and the first a user hears about it is their crate not compiling,
/// so this handles what the editor actually creates and skips the rest, saying
/// what it skipped.
struct Authored {
    name: String,
    transform: Transform,
    /// The model's asset path, for a glTF dropped into the viewport.
    ///
    /// Bevy 0.19 instantiates a glTF scene through
    /// `bevy::world_serialization::WorldAssetRoot(Handle<WorldAsset>)`; the
    /// `SceneRoot` this was first written against belongs to 0.18 and no longer
    /// exists.
    scene_asset: Option<String>,
    light: Option<Light>,
}

enum Light {
    Point { color: [f32; 3], intensity: f32, range: f32 },
    Directional { color: [f32; 3], illuminance: f32 },
}

/// Read every editor-authored entity out of the world.
///
/// Exclusions mirror the scene saver's: chrome opts out with `HideInHierarchy`,
/// and a `Persistent` entity belongs to a global scene rather than to this one.
#[allow(clippy::type_complexity)]
pub fn collect(world: &mut World) -> Vec<String> {
    let mut query = world.query_filtered::<
        (
            &Name,
            &Transform,
            Option<&bevy::world_serialization::WorldAssetRoot>,
            Option<&PointLight>,
            Option<&DirectionalLight>,
        ),
        (With<AuthoredByEditor>, Without<HideInHierarchy>, Without<Persistent>),
    >();

    // Asset paths are resolved through the server rather than stored, because a
    // `Handle` is an id: the path it was loaded from lives in the `AssetServer`
    // and nowhere else.
    type Rows = Vec<(String, Transform, Option<UntypedAssetId>, Option<Light>)>;
    let rows: Rows = query
        .iter(world)
        .map(|(name, transform, scene, point, directional)| {
            let light = point
                .map(|p| Light::Point {
                    color: p.color.to_srgba().to_f32_array_no_alpha(),
                    intensity: p.intensity,
                    range: p.range,
                })
                .or_else(|| {
                    directional.map(|d| Light::Directional {
                        color: d.color.to_srgba().to_f32_array_no_alpha(),
                        illuminance: d.illuminance,
                    })
                });
            (
                name.as_str().to_string(),
                *transform,
                scene.map(|s| s.0.id().untyped()),
                light,
            )
        })
        .collect();

    let server = world.get_resource::<AssetServer>().cloned();
    let entities: Vec<Authored> = rows
        .into_iter()
        .map(|(name, transform, scene, light)| Authored {
            name,
            transform,
            scene_asset: scene.and_then(|id| {
                server
                    .as_ref()
                    .and_then(|s| s.get_path(id))
                    .map(|p| p.to_string())
            }),
            light,
        })
        .collect();

    entities.iter().map(render_spawn).collect()
}

/// One entity, as a `commands.spawn((...))` call.
fn render_spawn(entity: &Authored) -> String {
    let t = &entity.transform;
    let mut out = String::new();
    let _ = writeln!(out, "    commands.spawn((");
    let _ = writeln!(out, "        Name::new({:?}),", entity.name);

    // `from_xyz` plus the rotation and scale only when they are not the
    // identity, so a placed object reads as one line rather than nine.
    let _ = write!(
        out,
        "        Transform::from_xyz({:?}, {:?}, {:?})",
        t.translation.x, t.translation.y, t.translation.z
    );
    if t.rotation != Quat::IDENTITY {
        let _ = write!(
            out,
            "\n            .with_rotation(Quat::from_xyzw({:?}, {:?}, {:?}, {:?}))",
            t.rotation.x, t.rotation.y, t.rotation.z, t.rotation.w
        );
    }
    if t.scale != Vec3::ONE {
        let _ = write!(
            out,
            "\n            .with_scale(Vec3::new({:?}, {:?}, {:?}))",
            t.scale.x, t.scale.y, t.scale.z
        );
    }
    let _ = writeln!(out, ",");

    if let Some(path) = &entity.scene_asset {
        let _ = writeln!(out, "        WorldAssetRoot(assets.load({path:?})),");
    }
    match &entity.light {
        Some(Light::Point { color, intensity, range }) => {
            let _ = writeln!(out, "        PointLight {{");
            let _ = writeln!(
                out,
                "            color: Color::srgb({:?}, {:?}, {:?}),",
                color[0], color[1], color[2]
            );
            let _ = writeln!(out, "            intensity: {intensity:?},");
            let _ = writeln!(out, "            range: {range:?},");
            let _ = writeln!(out, "            ..default()");
            let _ = writeln!(out, "        }},");
        }
        Some(Light::Directional { color, illuminance }) => {
            let _ = writeln!(out, "        DirectionalLight {{");
            let _ = writeln!(
                out,
                "            color: Color::srgb({:?}, {:?}, {:?}),",
                color[0], color[1], color[2]
            );
            let _ = writeln!(out, "            illuminance: {illuminance:?},");
            let _ = writeln!(out, "            ..default()");
            let _ = writeln!(out, "        }},");
        }
        None => {}
    }
    let _ = writeln!(out, "    ));");
    out
}

/// The generated module, whole.
pub fn render_module(spawns: &[String]) -> String {
    let mut out = String::new();
    out.push_str(
        "//! Everything placed in the Renzora editor, as ordinary Bevy code.\n\
         //!\n\
         //! **Generated. Do not edit.** This file is rewritten from the world every\n\
         //! time the project is saved, and anything added here by hand is lost on the\n\
         //! next save.\n\
         //!\n\
         //! It is deliberately plain Bevy: no engine types and no macros, so it\n\
         //! compiles in a checkout that has never seen Renzora. To take ownership of\n\
         //! something in here, move it into one of your own files and delete it from\n\
         //! the editor: a line in both places spawns the object twice.\n\
         \n\
         use bevy::prelude::*;\n\
         \n\
         /// Spawns what the editor placed.\n\
         pub struct ",
    );
    out.push_str(PLUGIN);
    out.push_str(
        ";\n\
         \n\
         impl Plugin for ",
    );
    out.push_str(PLUGIN);
    out.push_str(
        " {\n    fn build(&self, app: &mut App) {\n        app.add_systems(Startup, spawn);\n    }\n}\n\n",
    );

    if spawns.is_empty() {
        // An empty generated file rather than no file: the module is declared by
        // the crate root, and a declared module with no file does not compile.
        out.push_str(
            "/// Nothing has been placed in the editor yet.\n\
             fn spawn() {}\n",
        );
        return out;
    }

    // `assets` is only a parameter when something needs it, or the compiler
    // warns about an unused one in generated code the user cannot fix.
    let needs_assets = spawns.iter().any(|s| s.contains("assets.load("));
    if needs_assets {
        out.push_str("fn spawn(mut commands: Commands, assets: Res<AssetServer>) {\n");
    } else {
        out.push_str("fn spawn(mut commands: Commands) {\n");
    }
    for spawn in spawns {
        out.push_str(spawn);
    }
    out.push_str("}\n");
    out
}

/// Where the generated module goes for a crate rooted at `crate_root`.
///
/// Beside the crate root rather than at a fixed `src/`, because a crate is free
/// to put its root somewhere else with `[lib] path` and the module has to be its
/// sibling either way.
pub fn module_path(crate_root: &Path) -> PathBuf {
    crate_root
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("{MODULE}.rs"))
}

/// Write the module, and report whether anything changed.
///
/// Compares before writing so that saving a project nobody has edited does not
/// touch the file: an unchanged mtime keeps it out of the project watcher, out
/// of a rebuild, and out of `git status`.
pub fn write(crate_root: &Path, spawns: &[String]) -> Result<bool, std::io::Error> {
    let path = module_path(crate_root);
    let contents = render_module(spawns);
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == contents) {
        return Ok(false);
    }
    std::fs::write(&path, contents)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_placed_model_becomes_a_spawn_call() {
        let spawn = render_spawn(&Authored {
            name: "Rock".to_string(),
            transform: Transform::from_xyz(4.0, 0.0, -2.0),
            scene_asset: Some("models/nature/rock_largeA.glb#Scene0".to_string()),
            light: None,
        });
        assert!(spawn.contains("Name::new(\"Rock\")"));
        assert!(spawn.contains("Transform::from_xyz(4.0, 0.0, -2.0)"));
        assert!(
            spawn.contains("WorldAssetRoot(assets.load(\"models/nature/rock_largeA.glb#Scene0\"))")
        );
        // An identity rotation and scale are left out, or every placed object
        // reads as nine lines instead of three.
        assert!(!spawn.contains("with_rotation"));
        assert!(!spawn.contains("with_scale"));
    }

    #[test]
    fn a_rotated_and_scaled_entity_keeps_both() {
        let spawn = render_spawn(&Authored {
            name: "Tilted".to_string(),
            transform: Transform::from_xyz(0.0, 1.0, 0.0)
                .with_rotation(Quat::from_rotation_y(0.5))
                .with_scale(Vec3::splat(2.0)),
            scene_asset: None,
            light: None,
        });
        assert!(spawn.contains("with_rotation"));
        assert!(spawn.contains("with_scale"));
    }

    /// The parameter list has to match what the body uses: generated code the
    /// user cannot edit must not warn.
    #[test]
    fn the_asset_server_is_a_parameter_only_when_something_loads() {
        let with_model = render_module(&[render_spawn(&Authored {
            name: "Rock".into(),
            transform: Transform::IDENTITY,
            scene_asset: Some("models/rock.glb#Scene0".into()),
            light: None,
        })]);
        assert!(with_model.contains("fn spawn(mut commands: Commands, assets: Res<AssetServer>)"));

        let without = render_module(&[render_spawn(&Authored {
            name: "Light".into(),
            transform: Transform::IDENTITY,
            scene_asset: None,
            light: Some(Light::Point { color: [1.0, 1.0, 1.0], intensity: 800.0, range: 20.0 }),
        })]);
        assert!(without.contains("fn spawn(mut commands: Commands)"));
    }

    /// A declared module with no file does not compile, so an empty world still
    /// writes a module.
    #[test]
    fn an_empty_world_still_writes_a_compilable_module() {
        let module = render_module(&[]);
        assert!(module.contains("pub struct AuthoredScenePlugin"));
        assert!(module.contains("fn spawn() {}"));
    }

    #[test]
    fn the_module_sits_beside_the_crate_root() {
        let path = module_path(Path::new("/games/grove/src/main.rs"));
        assert_eq!(path, Path::new("/games/grove/src/renzora_authored.rs"));
    }
}
