//! Component identity across the boundary.
//!
//! A plugin and the host share no `TypeId` — nothing links — so **the type path
//! string is the identity**. A typo in one is silent on both sides and presents
//! as a query that matches nothing, forever.
//!
//! [`Component`] covers two quite different things, which is why `descriptor()`
//! is an `Option`: a *host* component the engine already owns (looked up by
//! path) and a *plugin* component the engine has never heard of (whose layout
//! the host allocates storage for).

use crate::sys;

/// A type that can appear in a plugin query.
///
/// Implemented for two quite different things, which is why [`descriptor`] is an
/// `Option`:
///
/// * **Host components** ([`Transform`](crate::sys::Transform) and friends) —
///   the engine already owns these. `descriptor()` is `None` and the id is
///   looked up by type path.
/// * **Plugin components** — the engine has never heard of them. `descriptor()`
///   returns a layout and the host allocates storage for it.
///
/// The plugin's `Transform` *is* the `#[repr(C)]` mirror the host marshals into,
/// so both kinds are fetched from a cell the same way and this trait needs no
/// further distinction.
///
/// [`descriptor`]: Component::descriptor
pub trait Component: Sized + 'static {
    /// Fully-qualified type path. This is the shared identity between host and
    /// plugin — neither side has a `TypeId` the other could use.
    const TYPE_PATH: &'static str;

    /// `None` for host components; `Some` for plugin-owned ones.
    fn descriptor() -> Option<sys::ComponentDesc> {
        None
    }

    /// Name shown in the editor's "Add Component" list. Defaults to
    /// [`TYPE_PATH`](Component::TYPE_PATH)'s last segment.
    fn display_name() -> &'static str {
        ""
    }

    /// Per-type cache for the id the host assigned this component.
    ///
    /// Filled in at registration so a *running* system can name a component
    /// without calling back into the host — during a system the world is
    /// borrowed by the query, so there is no safe handle to ask through.
    /// Generated by `#[derive(Component)]`; you never write this.
    fn id_cell() -> &'static core::sync::atomic::AtomicU32;

    /// Inspectable fields, so the editor can show and edit this component.
    ///
    /// Empty is valid and means "addable but with nothing to edit" — correct for
    /// a marker. A plugin component with no schema at all would be storable but
    /// unreachable from the UI, which is the state this whole mechanism exists
    /// to fix.
    fn fields() -> &'static [sys::FieldDesc] {
        &[]
    }

    /// Editing ranges, as `(index into `fields()`, range)`.
    ///
    /// Separate from [`fields`](Self::fields) because a range cannot ride in
    /// `FieldDesc` — that crosses as an array the host walks at its own stride, so
    /// widening it would misread every plugin built before the change. Sent through
    /// `set_field_range` after registration instead.
    fn field_ranges() -> &'static [(usize, sys::FieldRange)] {
        &[]
    }
}

/// Declares a host component the engine already owns.
///
/// The path must match the engine's registered type path exactly — it is the
/// only thing tying the two sides together. Nothing links: the host resolves the
/// string through its reflection registry, so a typo is silent on both sides and
/// presents as a query that matches nothing, forever.
///
/// **Exported, because the pattern is not ours alone.** The engine's own
/// components use it below, but so does any in-tree Bevy plugin that wants
/// standalone plugins to read its state: make the component `#[repr(C)]` plain
/// data, register it, and give plugin authors its type path.
///
/// ```ignore
/// // Mirrors an engine component. Field order and types must match the
/// // engine-side struct exactly — a mismatch is a wrong-offset read, not a
/// // compile error.
/// #[repr(C)]
/// #[derive(Clone, Copy, Default)]
/// pub struct Health { pub current: f32, pub max: f32 }
///
/// renzora_plugin::host_component!(Health, "my_game::health::Health");
/// ```
///
/// The type must be `#[repr(C)]` and plain data. Query cells for a host
/// component are a byte copy of the engine's own value, so a mirror containing a
/// `String`, `Vec` or `Handle` would hand the plugin a pointer into the engine's
/// heap — which is why the engine's own `Transform` is a hand-written
/// [`sys::Transform`] rather than a memcpy of `bevy::Transform`.
#[macro_export]
macro_rules! host_component {
    ($ty:ty, $path:literal) => {
        impl $crate::ecs::Bundle for $ty {
            fn write(self, e: &mut $crate::ecs::EntityCommands) {
                e.insert_one(self);
            }
        }
        impl $crate::ecs::Component for $ty {
            const TYPE_PATH: &'static str = $path;
            fn id_cell() -> &'static core::sync::atomic::AtomicU32 {
                static CELL: core::sync::atomic::AtomicU32 =
                    core::sync::atomic::AtomicU32::new(u32::MAX);
                &CELL
            }
        }
    };
}

crate::host_component!(Transform, "bevy_transform::components::transform::Transform");
crate::host_component!(Mesh3d, "bevy_mesh::components::Mesh3d");
crate::host_component!(Visibility, "bevy_camera::visibility::Visibility");
// Nothing else belongs here. A domain's mirror — `renzora_anim`'s `AnimState`,
// say — declares itself with the same exported macro from its own crate, so this
// file never learns an engine crate's name. It used to, and that was backwards:
// the frozen mechanism does not get to know that animation exists.

/// Marker for the host's `Mesh3d`. Opaque: the handle inside it is not a layout
/// a plugin may depend on, so this is filter-only — usable in
/// [`With`](super::With) but never as data.
pub struct Mesh3d(());

/// Marker for the host's `Visibility`. Filter-only for the same reason.
pub struct Visibility(());

pub use crate::sys::{Entity, Quat, Str256, Transform, Vec3};
