//! Bakes the plugin ABI hash into `renzora` as a compile-time constant.
//!
//! The host and every in-tree plugin compile `renzora`, so this script runs for
//! all of them and — reading the same `Cargo.lock`, the same workspace
//! `Cargo.toml`, and the same `rustc` — produces the *same* `RENZORA_ABI_HASH`
//! for each. That identity is what makes the loader's compatibility check
//! meaningful, and it is what eliminates the spurious drift the old
//! `TypeId`-derived tag suffered (see `abi_hash` crate docs).
//!
//! The value is computed here rather than read from a checked-in file so it can
//! never go stale relative to the actual build: change bevy, rustc, or the bevy
//! feature set and the hash moves on the very next build. `abi.lock` + the
//! `abi_hash` CLI exist only to *report* and *verify* that value for humans/CI.

use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let root = abi_hash::find_workspace_root(&manifest_dir)
        .expect("locate the engine workspace root (Cargo.lock + [workspace] Cargo.toml)");
    let inputs = abi_hash::gather(&root).expect("gather ABI inputs");
    let hash = inputs.hash();

    let generated = format!(
        "// @generated by renzora/build.rs — see the `abi_hash` crate.\n\
         /// The plugin ABI hash: a function of EXACTLY bevy version + rust\n\
         /// toolchain + the curated bevy feature set. The dynamic plugin loader\n\
         /// rejects any plugin whose `plugin_bevy_hash()` differs from this.\n\
         pub const RENZORA_ABI_HASH: [u64; 2] = [{}, {}];\n\
         \n\
         /// Human-readable form of the three ABI inputs (the same text the\n\
         /// `abi_hash` CLI prints), embedded for runtime diagnostics so a\n\
         /// rejected plugin can be diffed field-by-field against the host.\n\
         pub const RENZORA_ABI_INPUTS: &str = {:?};\n\
         \n\
         /// NUL-terminated copy of [`RENZORA_ABI_INPUTS`] for the `extern \"C\"`\n\
         /// `plugin_abi_info()` export.\n\
         pub const RENZORA_ABI_INPUTS_CSTR: &str = {:?};\n",
        hash[0],
        hash[1],
        inputs.canonical(),
        format!("{}\0", inputs.canonical()),
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"))
        .join("abi_hash.rs");
    std::fs::write(&out, generated).expect("write generated abi_hash.rs");

    // Re-run whenever an input can change. A rustc swap forces a full rebuild
    // anyway (so this re-runs), but flag the env var explicitly for clarity.
    println!("cargo:rerun-if-changed={}", root.join("Cargo.lock").display());
    println!("cargo:rerun-if-changed={}", root.join("Cargo.toml").display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=RUSTC");
}
