//! Editor bundle — a single loadable cdylib that statically links every
//! editor-only plugin crate (as rlibs) and exposes them through ONE FFI entry
//! point (`plugin_install_scope`) via [`renzora::export_plugin_bundle!`].
//!
//! This is the "editor as a removable dylib" half of Operation Merge: present
//! beside the host → the binary is the editor; remove the dll → the same
//! binary is the exported game. Both share one `bevy_dylib` (built in one
//! `--workspace` invocation), so a community plugin built once loads in both.
//!
//! Step B (this): the bundle is POPULATED — its `editor` feature mirrors
//! `renzora_runtime`'s, the keepalive `build.rs` forces every bundled crate's
//! `inventory::submit!` ctors into the cdylib, and the macro installs the
//! editor SDK foundation in order before replaying the Editor-scope fan-out.
//! Until Step C flips the binary runtime-only and wires the loader, NOTHING
//! dlopens this bundle — it is inert (built but never loaded).
//!
//! ## Hard preconditions (from the Step-A adversarial review)
//!
//! - **Build via `--workspace` only** (never `cargo build -p renzora_editor`).
//!   `dynamic_linking` reaches this crate's `bevy` solely through resolver-2
//!   feature unification with `renzora_app` under one `--workspace` build. Built
//!   in isolation it would link a *separate, static* bevy → a different
//!   `World` TypeId → `plugin_bevy_hash` mismatch → the loader silently rejects
//!   the bundle ("incompatible bevy version"). The user must verify the built
//!   bundle's hash equals the host's.
//! - **Deployment contract:** the inventory `plugin_install_scope` replays is the
//!   ONE global registry in the shared `renzora` dylib. So a build either
//!   statically links the editor plugins (`add_editor_plugins`) OR ships them as
//!   this bundle — *never both*, or they install twice and Bevy panics. The
//!   runtime-shaped host (Step C) must stop statically registering editor-scope
//!   plugins. Until Step C, this bundle is not safe to drop into a current
//!   *editor* build's `plugins/` (or beside an editor-shaped exe).
//! - **Editor-scope filter is the second line of defence:** the dual-mode crates
//!   re-link here with their `editor` code, so their `EditorAndRuntime`/`Runtime`
//!   ctors are submitted into the global registry a second time. But the bundle
//!   is driven with `host_scope = Editor`, and `PluginScope::matches` installs
//!   only Editor-scope plugins — the duplicated dual-mode entries are never
//!   installed by the bundle (the host installs them). The duplication is inert.

// Dylib keepalive: force every bundled crate into the cdylib's link graph so
// its `inventory::submit!` ctor runs (otherwise dead-stripped → empty bundle).
// Generated by build.rs from Cargo.toml. Gated on `editor` because the
// editor-only `pub use`s only resolve when their optional deps are active.
#[cfg(feature = "editor")]
include!(concat!(env!("OUT_DIR"), "/bundle_reexports.rs"));

/// Install the whole editor into `app`.
///
/// Called directly by the `renzora-editor` binary, which links this crate as an
/// rlib. It replaces the old `plugin_install_scope` FFI door: with Bevy
/// statically linked there is no second `bevy_dylib` for a loadable bundle to
/// share, so the editor is a *binary*, not a `dlopen`'d file.
///
/// Ordering is load-bearing and matches what `export_plugin_bundle!` did: the
/// foundation plugins init the shared registries (AssetRegistry → editor
/// registries → KeyBindings) that every Editor-scope plugin reads inside its own
/// `build()`. Call this AFTER `add_engine_plugins`, so the editor layers on top
/// of the runtime foundation.
#[cfg(feature = "editor")]
pub fn install(app: &mut renzora::bevy::app::App) {
    app.add_plugins(renzora_asset_registry::AssetRegistryPlugin);
    app.add_plugins(renzora_editor_framework::RenzoraEditorPlugin);
    app.add_plugins(renzora_keybindings::KeybindingsPlugin);

    // Dedup by name, kept from the bundle version. An editor-only crate can end
    // up linked twice (e.g. a dual-mode crate like `renzora_hanabi` depends on
    // `renzora_inspector`), running its `add!()` ctor twice and submitting two
    // entries for one plugin. The install fn pointers differ between linkage
    // copies, so key on the stable `name` — installing both panics Bevy with
    // "plugin was already added".
    let mut seen: std::collections::HashSet<&'static str> = std::collections::HashSet::new();
    renzora::for_each_static_plugin(renzora::PluginScope::Editor, |plugin| {
        if !seen.insert(plugin.name) {
            return;
        }
        (plugin.install)(app);
    });
}
