//! UI events generated by widget interactions.
//!
//! When users interact with widgets, events are generated and can be
//! polled by plugins to respond to user actions.

use super::types::UiId;

/// UI events that plugins can respond to.
/// These are generated by the renderer when users interact with widgets.
#[derive(Clone, Debug)]
pub enum UiEvent {
    /// Button was clicked
    ButtonClicked(UiId),

    /// Checkbox was toggled
    CheckboxToggled {
        id: UiId,
        checked: bool,
    },

    /// Slider value changed
    SliderChanged {
        id: UiId,
        value: f32,
    },

    /// Integer slider value changed
    SliderIntChanged {
        id: UiId,
        value: i32,
    },

    /// Text input content changed
    TextInputChanged {
        id: UiId,
        value: String,
    },

    /// Text input submitted (Enter pressed)
    TextInputSubmitted {
        id: UiId,
        value: String,
    },

    /// Dropdown selection changed
    DropdownSelected {
        id: UiId,
        index: u32,
    },

    /// Color picker value changed
    ColorChanged {
        id: UiId,
        color: [f32; 4],
    },

    /// Tree node expand/collapse toggled
    TreeNodeToggled {
        id: UiId,
        expanded: bool,
    },

    /// Tree node was selected
    TreeNodeSelected(UiId),

    /// Tab was selected
    TabSelected {
        id: UiId,
        index: u32,
    },

    /// Tab close button was clicked
    TabClosed {
        id: UiId,
        index: u32,
    },

    /// Table row was selected
    TableRowSelected {
        id: UiId,
        row: u32,
    },

    /// Table row was double-clicked
    TableRowActivated {
        id: UiId,
        row: u32,
    },

    /// Table sort column changed
    TableSortChanged {
        id: UiId,
        column: u32,
        ascending: bool,
    },

    /// Context menu was requested on a widget
    ContextMenuRequested {
        id: UiId,
        position: [f32; 2],
    },

    /// Drag started on a widget
    DragStarted {
        id: UiId,
    },

    /// Drag ended
    DragEnded {
        id: UiId,
        target: Option<UiId>,
    },

    /// Item was dropped on a widget
    ItemDropped {
        target_id: UiId,
        source_id: UiId,
    },

    /// Custom event from a custom widget
    CustomEvent {
        type_id: String,
        data: Vec<u8>,
    },

    /// Panel tab was selected (for plugin tabs in panel areas)
    /// location: 0=Left, 1=Right, 2=Bottom
    /// tab_id: empty string means built-in tab (Hierarchy/Inspector/Assets)
    PanelTabSelected {
        location: u8,
        tab_id: String,
    },
}

impl UiEvent {
    /// Get the UiId associated with this event, if any
    pub fn id(&self) -> Option<UiId> {
        match self {
            UiEvent::ButtonClicked(id) => Some(*id),
            UiEvent::CheckboxToggled { id, .. } => Some(*id),
            UiEvent::SliderChanged { id, .. } => Some(*id),
            UiEvent::SliderIntChanged { id, .. } => Some(*id),
            UiEvent::TextInputChanged { id, .. } => Some(*id),
            UiEvent::TextInputSubmitted { id, .. } => Some(*id),
            UiEvent::DropdownSelected { id, .. } => Some(*id),
            UiEvent::ColorChanged { id, .. } => Some(*id),
            UiEvent::TreeNodeToggled { id, .. } => Some(*id),
            UiEvent::TreeNodeSelected(id) => Some(*id),
            UiEvent::TabSelected { id, .. } => Some(*id),
            UiEvent::TabClosed { id, .. } => Some(*id),
            UiEvent::TableRowSelected { id, .. } => Some(*id),
            UiEvent::TableRowActivated { id, .. } => Some(*id),
            UiEvent::TableSortChanged { id, .. } => Some(*id),
            UiEvent::ContextMenuRequested { id, .. } => Some(*id),
            UiEvent::DragStarted { id } => Some(*id),
            UiEvent::DragEnded { id, .. } => Some(*id),
            UiEvent::ItemDropped { target_id, .. } => Some(*target_id),
            UiEvent::CustomEvent { .. } => None,
            UiEvent::PanelTabSelected { .. } => None,
        }
    }
}

/// Event queue for collecting UI events during a frame
#[derive(Default)]
pub struct UiEventQueue {
    events: Vec<UiEvent>,
}

impl UiEventQueue {
    /// Create a new empty event queue
    pub fn new() -> Self {
        Self { events: Vec::new() }
    }

    /// Push an event to the queue
    pub fn push(&mut self, event: UiEvent) {
        self.events.push(event);
    }

    /// Drain all events from the queue
    pub fn drain(&mut self) -> impl Iterator<Item = UiEvent> + '_ {
        self.events.drain(..)
    }

    /// Get all events without draining
    pub fn iter(&self) -> impl Iterator<Item = &UiEvent> {
        self.events.iter()
    }

    /// Check if queue is empty
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Get number of events in queue
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// Clear all events
    pub fn clear(&mut self) {
        self.events.clear();
    }
}
