//! The ergonomic layer: Bevy-shaped types over the raw `sys` calls.
//!
//! Everything here exists to make plugin source **identical to Bevy source**.
//! Names and signatures mirror `bevy_ecs` deliberately — a "better" name is a
//! name nobody already knows, and the whole value of this crate is that existing
//! Bevy knowledge transfers without a translation step.
//!
//! ## How a system becomes a C function
//!
//! `App::add_systems` takes any zero-sized callable. Two things are derived from
//! its signature at compile time:
//!
//! * the [`sys::QueryDesc`] — which components, and how they're accessed
//! * an `extern "C"` thunk, monomorphised per signature, that unpacks
//!   [`sys::SystemCall`] into typed arguments and calls the function
//!
//! Because the thunk is generic over the callable's *type*, the function needs
//! no runtime representation at all — see `materialize`. That is why a capturing
//! closure is rejected: its captures would need storage the host cannot own.

use crate::sys;
use core::marker::PhantomData;

// ── Component identity ───────────────────────────────────────────────────────

/// A type that can appear in a plugin query.
///
/// Implemented for two quite different things, which is why [`descriptor`] is an
/// `Option`:
///
/// * **Host components** ([`Transform`] and friends) — the engine already owns
///   these. `descriptor()` is `None` and the id is looked up by type path.
/// * **Plugin components** — the engine has never heard of them. `descriptor()`
///   returns a layout and the host allocates storage for it.
///
/// The plugin's `Transform` *is* the `#[repr(C)]` mirror the host marshals into,
/// so both kinds are fetched from a cell the same way and this trait needs no
/// further distinction.
///
/// [`descriptor`]: Component::descriptor
pub trait Component: Sized + 'static {
    /// Fully-qualified type path. This is the shared identity between host and
    /// plugin — neither side has a `TypeId` the other could use.
    const TYPE_PATH: &'static str;

    /// `None` for host components; `Some` for plugin-owned ones.
    fn descriptor() -> Option<sys::ComponentDesc> {
        None
    }

    /// Name shown in the editor's "Add Component" list. Defaults to
    /// [`TYPE_PATH`](Component::TYPE_PATH)'s last segment.
    fn display_name() -> &'static str {
        ""
    }

    /// Per-type cache for the id the host assigned this component.
    ///
    /// Filled in at registration so a *running* system can name a component
    /// without calling back into the host — during a system the world is
    /// borrowed by the query, so there is no safe handle to ask through.
    /// Generated by `#[derive(Component)]`; you never write this.
    fn id_cell() -> &'static core::sync::atomic::AtomicU32;

    /// Inspectable fields, so the editor can show and edit this component.
    ///
    /// Empty is valid and means "addable but with nothing to edit" — correct for
    /// a marker. A plugin component with no schema at all would be storable but
    /// unreachable from the UI, which is the state this whole mechanism exists
    /// to fix.
    fn fields() -> &'static [sys::FieldDesc] {
        &[]
    }
}

/// Declares a host component the engine already owns.
///
/// The path must match the engine's registered type path exactly — it is the
/// only thing tying the two sides together.
macro_rules! host_component {
    ($ty:ty, $path:literal) => {
        impl Bundle for $ty {
            fn write(self, e: &mut EntityCommands) {
                e.insert_one(self);
            }
        }
        impl Component for $ty {
            const TYPE_PATH: &'static str = $path;
            fn id_cell() -> &'static core::sync::atomic::AtomicU32 {
                static CELL: core::sync::atomic::AtomicU32 =
                    core::sync::atomic::AtomicU32::new(u32::MAX);
                &CELL
            }
        }
    };
}

host_component!(Transform, "bevy_transform::components::transform::Transform");
host_component!(Mesh3d, "bevy_mesh::components::Mesh3d");
host_component!(Visibility, "bevy_camera::visibility::Visibility");

/// Marker for the host's `Mesh3d`. Opaque: the handle inside it is not a layout
/// a plugin may depend on, so this is filter-only — usable in [`With`] but never
/// as data.
pub struct Mesh3d(());

/// Marker for the host's `Visibility`. Filter-only for the same reason.
pub struct Visibility(());

pub use crate::sys::{Entity, Quat, Transform, Vec3};

impl Vec3 {
    pub const ZERO: Vec3 = Vec3 { x: 0.0, y: 0.0, z: 0.0 };
    pub const ONE: Vec3 = Vec3 { x: 1.0, y: 1.0, z: 1.0 };
    pub const X: Vec3 = Vec3 { x: 1.0, y: 0.0, z: 0.0 };
    pub const Y: Vec3 = Vec3 { x: 0.0, y: 1.0, z: 0.0 };
    pub const Z: Vec3 = Vec3 { x: 0.0, y: 0.0, z: 1.0 };

    pub const fn new(x: f32, y: f32, z: f32) -> Vec3 {
        Vec3 { x, y, z }
    }
    pub const fn splat(v: f32) -> Vec3 {
        Vec3 { x: v, y: v, z: v }
    }
    pub fn dot(self, o: Vec3) -> f32 {
        self.x * o.x + self.y * o.y + self.z * o.z
    }
    pub fn cross(self, o: Vec3) -> Vec3 {
        Vec3::new(
            self.y * o.z - self.z * o.y,
            self.z * o.x - self.x * o.z,
            self.x * o.y - self.y * o.x,
        )
    }
    pub fn length(self) -> f32 {
        self.dot(self).sqrt()
    }
    pub fn length_squared(self) -> f32 {
        self.dot(self)
    }
    pub fn distance(self, o: Vec3) -> f32 {
        (self - o).length()
    }
    /// Returns `ZERO` for a zero-length vector rather than `NaN` — a normalise
    /// in a loop over positions will hit coincident points sooner or later, and
    /// a silent NaN poisons everything downstream.
    pub fn normalize_or_zero(self) -> Vec3 {
        let len = self.length();
        if len > 1e-6 {
            self / len
        } else {
            Vec3::ZERO
        }
    }
    pub fn normalize(self) -> Vec3 {
        self / self.length()
    }
    pub fn lerp(self, o: Vec3, t: f32) -> Vec3 {
        self + (o - self) * t
    }
    pub fn clamp_length_max(self, max: f32) -> Vec3 {
        let len = self.length();
        if len > max && len > 1e-6 {
            self * (max / len)
        } else {
            self
        }
    }
}

impl core::ops::Add for Vec3 {
    type Output = Vec3;
    fn add(self, o: Vec3) -> Vec3 {
        Vec3::new(self.x + o.x, self.y + o.y, self.z + o.z)
    }
}
impl core::ops::Sub for Vec3 {
    type Output = Vec3;
    fn sub(self, o: Vec3) -> Vec3 {
        Vec3::new(self.x - o.x, self.y - o.y, self.z - o.z)
    }
}
impl core::ops::Mul<f32> for Vec3 {
    type Output = Vec3;
    fn mul(self, s: f32) -> Vec3 {
        Vec3::new(self.x * s, self.y * s, self.z * s)
    }
}
impl core::ops::Mul<Vec3> for Vec3 {
    type Output = Vec3;
    fn mul(self, o: Vec3) -> Vec3 {
        Vec3::new(self.x * o.x, self.y * o.y, self.z * o.z)
    }
}
impl core::ops::Div<f32> for Vec3 {
    type Output = Vec3;
    fn div(self, s: f32) -> Vec3 {
        Vec3::new(self.x / s, self.y / s, self.z / s)
    }
}
impl core::ops::Neg for Vec3 {
    type Output = Vec3;
    fn neg(self) -> Vec3 {
        Vec3::new(-self.x, -self.y, -self.z)
    }
}
impl core::ops::AddAssign for Vec3 {
    fn add_assign(&mut self, o: Vec3) {
        *self = *self + o;
    }
}
impl core::ops::SubAssign for Vec3 {
    fn sub_assign(&mut self, o: Vec3) {
        *self = *self - o;
    }
}
impl core::ops::MulAssign<f32> for Vec3 {
    fn mul_assign(&mut self, s: f32) {
        *self = *self * s;
    }
}

impl Quat {
    pub const IDENTITY: Quat = Quat { x: 0.0, y: 0.0, z: 0.0, w: 1.0 };

    pub fn from_axis_angle(axis: Vec3, angle: f32) -> Quat {
        let (s, c) = (angle * 0.5).sin_cos();
        let a = axis.normalize_or_zero();
        Quat { x: a.x * s, y: a.y * s, z: a.z * s, w: c }
    }
    pub fn from_rotation_x(angle: f32) -> Quat {
        let (s, c) = (angle * 0.5).sin_cos();
        Quat { x: s, y: 0.0, z: 0.0, w: c }
    }
    pub fn from_rotation_y(angle: f32) -> Quat {
        let (s, c) = (angle * 0.5).sin_cos();
        Quat { x: 0.0, y: s, z: 0.0, w: c }
    }
    pub fn from_rotation_z(angle: f32) -> Quat {
        let (s, c) = (angle * 0.5).sin_cos();
        Quat { x: 0.0, y: 0.0, z: s, w: c }
    }
}

impl core::ops::Mul for Quat {
    type Output = Quat;
    fn mul(self, r: Quat) -> Quat {
        Quat {
            x: self.w * r.x + self.x * r.w + self.y * r.z - self.z * r.y,
            y: self.w * r.y - self.x * r.z + self.y * r.w + self.z * r.x,
            z: self.w * r.z + self.x * r.y - self.y * r.x + self.z * r.w,
            w: self.w * r.w - self.x * r.x - self.y * r.y - self.z * r.z,
        }
    }
}

impl core::ops::Mul<Vec3> for Quat {
    type Output = Vec3;
    /// Rotate a vector. `v + 2w(q x v) + 2(q x (q x v))`.
    fn mul(self, v: Vec3) -> Vec3 {
        let q = Vec3::new(self.x, self.y, self.z);
        let t = q.cross(v) * 2.0;
        v + t * self.w + q.cross(t)
    }
}

impl Default for Quat {
    fn default() -> Self {
        Quat::IDENTITY
    }
}

impl Transform {
    pub const IDENTITY: Transform = Transform {
        translation: Vec3::ZERO,
        rotation: Quat::IDENTITY,
        scale: Vec3::ONE,
    };

    pub const fn from_xyz(x: f32, y: f32, z: f32) -> Transform {
        Transform {
            translation: Vec3::new(x, y, z),
            rotation: Quat::IDENTITY,
            scale: Vec3::ONE,
        }
    }
    pub const fn from_translation(translation: Vec3) -> Transform {
        Transform {
            translation,
            rotation: Quat::IDENTITY,
            scale: Vec3::ONE,
        }
    }
    pub const fn with_scale(mut self, scale: Vec3) -> Transform {
        self.scale = scale;
        self
    }
    pub const fn with_translation(mut self, translation: Vec3) -> Transform {
        self.translation = translation;
        self
    }

    pub fn rotate(&mut self, q: Quat) {
        self.rotation = q * self.rotation;
    }
    pub fn rotate_x(&mut self, angle: f32) {
        self.rotation = self.rotation * Quat::from_rotation_x(angle);
    }
    pub fn rotate_y(&mut self, angle: f32) {
        self.rotation = self.rotation * Quat::from_rotation_y(angle);
    }
    pub fn rotate_z(&mut self, angle: f32) {
        self.rotation = self.rotation * Quat::from_rotation_z(angle);
    }

    pub fn forward(&self) -> Vec3 {
        self.rotation * -Vec3::Z
    }
    pub fn back(&self) -> Vec3 {
        self.rotation * Vec3::Z
    }
    pub fn right(&self) -> Vec3 {
        self.rotation * Vec3::X
    }
    pub fn left(&self) -> Vec3 {
        self.rotation * -Vec3::X
    }
    pub fn up(&self) -> Vec3 {
        self.rotation * Vec3::Y
    }
    pub fn down(&self) -> Vec3 {
        self.rotation * -Vec3::Y
    }
}

impl Default for Transform {
    fn default() -> Self {
        Transform::IDENTITY
    }
}

// ── Init context ─────────────────────────────────────────────────────────────

/// Resolves component ids during `Plugin::build`, caching so a type is
/// registered or looked up once regardless of how many systems name it.
pub struct InitCtx {
    iface: *const sys::Interface,
    host: *mut sys::Host,
    cache: alloc::vec::Vec<(&'static str, sys::ComponentId)>,
    /// Type path of the first component that failed to resolve, if any.
    ///
    /// A plugin naming a component the host does not expose must refuse to load.
    /// Carrying on would register a system whose query can never match, which
    /// presents as "my plugin loaded but does nothing" — far harder to diagnose
    /// than a refusal at startup.
    unresolved: Option<&'static str>,
}

impl InitCtx {
    /// Register `T` as a resource and cache the id on the type.
    ///
    /// Registration is idempotent host-side (a second call returns the same id
    /// and leaves the existing value alone), so two systems both taking
    /// `ResMut<Score>` do not reset it between them.
    fn resource_id_of<T: Resource>(&mut self) -> sys::ComponentId {
        // Cached on the `InitCtx`, not on the type. The type's cell is the
        // *runtime* lookup key and is only correct for the world this plugin was
        // loaded into; short-circuiting on it would let one world's id leak into
        // another and silently skip registration there.
        if let Some((_, id)) = self.cache.iter().find(|(p, _)| *p == T::TYPE_PATH) {
            return *id;
        }
        let desc = T::descriptor();
        // SAFETY: `iface`/`host` are valid for the whole init call.
        let id = unsafe { ((*self.iface).register_resource)(self.host, &desc) };
        if !id.is_valid() && self.unresolved.is_none() {
            self.unresolved = Some(T::TYPE_PATH);
        }
        T::id_cell().store(id.0, core::sync::atomic::Ordering::Relaxed);
        self.cache.push((T::TYPE_PATH, id));
        id
    }

    fn id_of<T: Component>(&mut self) -> sys::ComponentId {
        if let Some((_, id)) = self.cache.iter().find(|(p, _)| *p == T::TYPE_PATH) {
            return *id;
        }
        // SAFETY: `iface`/`host` are valid for the whole init call.
        let id = unsafe {
            match T::descriptor() {
                Some(desc) => ((*self.iface).register_component)(self.host, &desc),
                None => ((*self.iface).component_id_by_name)(
                    self.host,
                    sys::StrRef::new(T::TYPE_PATH),
                ),
            }
        };
        if !id.is_valid() && self.unresolved.is_none() {
            self.unresolved = Some(T::TYPE_PATH);
        }
        // Cache on the type itself, so systems can reach it later.
        T::id_cell().store(id.0, core::sync::atomic::Ordering::Relaxed);
        self.cache.push((T::TYPE_PATH, id));
        id
    }
}

/// The id the host assigned `T`, or `INVALID` if it was never registered.
///
/// Registration happens during `Plugin::build`; a system naming a component the
/// plugin never registered gets `INVALID`, and the host ignores commands
/// carrying it rather than guessing.
pub fn component_id_of<T: Component>() -> sys::ComponentId {
    sys::ComponentId(T::id_cell().load(core::sync::atomic::Ordering::Relaxed))
}

// ── Query data ───────────────────────────────────────────────────────────────

/// What a query reads or writes. Implemented for `&T`, `&mut T`, and tuples.
///
/// # Safety
/// `CELLS` must equal the number of terms `terms` pushes, and `fetch` must read
/// exactly that many cells. The host lays cells out row-major on that promise.
pub unsafe trait QueryData {
    type Item<'a>;
    /// Cells this contributes per row. Zero for terms that read something other
    /// than component data, like [`Entity`].
    const CELLS: usize;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>);
    /// # Safety
    /// `cells` points at this item's first cell in the row `row`, and `view` is
    /// live. `'a` is unbounded: the item borrows the host's staging buffers,
    /// which outlive the call but are not reachable from any argument, so
    /// nothing in the types can express the real bound. The caller is
    /// responsible for not letting an item escape the system body.
    unsafe fn fetch<'a>(
        view: *const sys::QueryView,
        row: usize,
        cells: *mut *mut u8,
    ) -> Self::Item<'a>;
}

/// Yields the entity being iterated. Mirrors Bevy's `Entity` query term.
///
/// Contributes no cell and no term — the host already sends an entity id per
/// row alongside the component data, so this costs nothing beyond reading it.
/// Without it a system cannot act on the entity it is looking at, which makes
/// "do this once, then mark it done" unwritable.
unsafe impl QueryData for sys::Entity {
    type Item<'a> = sys::Entity;
    const CELLS: usize = 0;
    fn terms(_: &mut InitCtx, _: &mut alloc::vec::Vec<sys::Term>) {}
    unsafe fn fetch<'a>(
        view: *const sys::QueryView,
        row: usize,
        _cells: *mut *mut u8,
    ) -> Self::Item<'a> {
        if (*view).entities.is_null() {
            return sys::Entity(u64::MAX);
        }
        *(*view).entities.add(row)
    }
}

unsafe impl<T: Component> QueryData for &T {
    type Item<'a> = &'a T;
    const CELLS: usize = 1;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::Read });
    }
    unsafe fn fetch<'a>(_: *const sys::QueryView, _: usize, cells: *mut *mut u8) -> &'a T {
        &*(*cells as *const T)
    }
}

unsafe impl<T: Component> QueryData for &mut T {
    type Item<'a> = &'a mut T;
    const CELLS: usize = 1;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::Write });
    }
    unsafe fn fetch<'a>(_: *const sys::QueryView, _: usize, cells: *mut *mut u8) -> &'a mut T {
        &mut *(*cells as *mut T)
    }
}

/// Reads `T` when the entity has it. Mirrors Bevy's `Option<&T>`.
///
/// The term does not filter, so the entity matches either way and the cell is
/// null when the component is absent — which is what makes "every entity, plus
/// this extra data if it happens to be there" a single query instead of two.
unsafe impl<T: Component> QueryData for Option<&T> {
    type Item<'a> = Option<&'a T>;
    const CELLS: usize = 1;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::ReadOptional });
    }
    unsafe fn fetch<'a>(_: *const sys::QueryView, _: usize, cells: *mut *mut u8) -> Option<&'a T> {
        (*cells).cast::<T>().as_ref()
    }
}

unsafe impl<T: Component> QueryData for Option<&mut T> {
    type Item<'a> = Option<&'a mut T>;
    const CELLS: usize = 1;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::WriteOptional });
    }
    unsafe fn fetch<'a>(
        _: *const sys::QueryView,
        _: usize,
        cells: *mut *mut u8,
    ) -> Option<&'a mut T> {
        (*cells).cast::<T>().as_mut()
    }
}

unsafe impl<A: QueryData, B: QueryData, C: QueryData> QueryData for (A, B, C) {
    type Item<'a> = (A::Item<'a>, B::Item<'a>, C::Item<'a>);
    const CELLS: usize = A::CELLS + B::CELLS + C::CELLS;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        A::terms(ctx, out);
        B::terms(ctx, out);
        C::terms(ctx, out);
    }
    unsafe fn fetch<'a>(
        view: *const sys::QueryView,
        row: usize,
        cells: *mut *mut u8,
    ) -> Self::Item<'a> {
        (
            A::fetch(view, row, cells),
            B::fetch(view, row, cells.add(A::CELLS)),
            C::fetch(view, row, cells.add(A::CELLS + B::CELLS)),
        )
    }
}

unsafe impl<A: QueryData, B: QueryData> QueryData for (A, B) {
    type Item<'a> = (A::Item<'a>, B::Item<'a>);
    const CELLS: usize = A::CELLS + B::CELLS;
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        A::terms(ctx, out);
        B::terms(ctx, out);
    }
    unsafe fn fetch<'a>(
        view: *const sys::QueryView,
        row: usize,
        cells: *mut *mut u8,
    ) -> Self::Item<'a> {
        (
            A::fetch(view, row, cells),
            B::fetch(view, row, cells.add(A::CELLS)),
        )
    }
}

// ── Query filters ────────────────────────────────────────────────────────────

/// Filter terms. Contribute no cells — see [`sys::Access::With`].
pub trait QueryFilter {
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>);
}

impl QueryFilter for () {
    fn terms(_: &mut InitCtx, _: &mut alloc::vec::Vec<sys::Term>) {}
}

/// Matches entities that have `T`.
pub struct With<T>(PhantomData<T>);

impl<T: Component> QueryFilter for With<T> {
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::With });
    }
}

/// Matches entities that do not have `T`.
pub struct Without<T>(PhantomData<T>);

impl<T: Component> QueryFilter for Without<T> {
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        out.push(sys::Term { component: ctx.id_of::<T>(), access: sys::Access::Without });
    }
}

impl<A: QueryFilter, B: QueryFilter> QueryFilter for (A, B) {
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        A::terms(ctx, out);
        B::terms(ctx, out);
    }
}

impl<A: QueryFilter, B: QueryFilter, C: QueryFilter> QueryFilter for (A, B, C) {
    fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
        A::terms(ctx, out);
        B::terms(ctx, out);
        C::terms(ctx, out);
    }
}

/// Matches entities satisfying any branch. Mirrors `bevy::Or<(..)>`.
///
/// Encoded as a bracketed run of terms — [`sys::Access::OrBegin`], one branch
/// per [`sys::Access::OrNext`] separator, then [`sys::Access::OrEnd`] — rather
/// than as a nested descriptor, so a query stays one flat term list at the
/// boundary no matter how the filter is spelled.
pub struct Or<T>(PhantomData<T>);

macro_rules! or_filters {
    ($(($first:ident $(, $rest:ident)*))+) => {
        $(
            impl<$first: QueryFilter $(, $rest: QueryFilter)*> QueryFilter
                for Or<($first, $($rest,)*)>
            {
                fn terms(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>) {
                    out.push(sys::Term::marker(sys::Access::OrBegin));
                    $first::terms(ctx, out);
                    $(
                        out.push(sys::Term::marker(sys::Access::OrNext));
                        $rest::terms(ctx, out);
                    )*
                    out.push(sys::Term::marker(sys::Access::OrEnd));
                }
            }
        )+
    };
}

or_filters! {
    (A, B)
    (A, B, C)
    (A, B, C, D)
}

// ── Query ────────────────────────────────────────────────────────────────────

/// A view over the entities this system matched. Mirrors `bevy_ecs::Query`.
pub struct Query<'a, D: QueryData, F: QueryFilter = ()> {
    view: sys::QueryView,
    _p: PhantomData<(&'a (), D, F)>,
}

impl<'a, D: QueryData, F: QueryFilter> Query<'a, D, F> {
    /// # Safety
    /// `view` must index a live [`sys::QueryView`] whose terms were declared by
    /// this exact `D`/`F` pair.
    unsafe fn new(call: *const sys::SystemCall, view: usize) -> Self {
        // Copied, not borrowed. A `QueryView` is four words and `Copy`, so this
        // is free — and it keeps the whole lifetime and `Sync` question out of
        // the type, which a `&'static` fallback for the out-of-range case would
        // otherwise drag in.
        let view = if view < (*call).view_count {
            *(*call).views.add(view)
        } else {
            // Unreachable if the host honoured the descriptor. A query that
            // yields nothing still beats one that reads a wild pointer.
            EMPTY_VIEW
        };
        Self {
            view,
            _p: PhantomData,
        }
    }

    pub fn iter(&self) -> QueryIter<'_, D, F> {
        QueryIter {
            view: self.view,
            row: 0,
            _p: PhantomData,
        }
    }

    pub fn iter_mut(&mut self) -> QueryIter<'_, D, F> {
        self.iter()
    }

    pub fn len(&self) -> usize {
        self.view.entity_count
    }

    pub fn is_empty(&self) -> bool {
        self.view.entity_count == 0
    }
}

/// Stands in when a view index is out of range. Empty, so iterating it is a
/// no-op rather than a fault.
const EMPTY_VIEW: sys::QueryView = sys::QueryView {
    cells: core::ptr::null_mut(),
    entities: core::ptr::null(),
    entity_count: 0,
    cell_count: 0,
};

pub struct QueryIter<'a, D: QueryData, F: QueryFilter> {
    view: sys::QueryView,
    row: usize,
    _p: PhantomData<(&'a (), D, F)>,
}

impl<'a, D: QueryData, F: QueryFilter> Iterator for QueryIter<'a, D, F> {
    type Item = D::Item<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.row >= self.view.entity_count {
            return None;
        }
        // SAFETY: row < entity_count, and the host laid out `cell_count` cells
        // per row in declaration order.
        let item = unsafe {
            D::fetch(
                &self.view as *const sys::QueryView,
                self.row,
                self.view.cells.add(self.row * self.view.cell_count),
            )
        };
        self.row += 1;
        Some(item)
    }
}

impl<'a, D: QueryData, F: QueryFilter> IntoIterator for &'a Query<'_, D, F> {
    type Item = D::Item<'a>;
    type IntoIter = QueryIter<'a, D, F>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<'a, D: QueryData, F: QueryFilter> IntoIterator for &'a mut Query<'_, D, F> {
    type Item = D::Item<'a>;
    type IntoIter = QueryIter<'a, D, F>;
    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

// ── Resources ────────────────────────────────────────────────────────────────

/// A single global value, one per world. Mirrors `bevy::Resource`.
///
/// Emitted by `#[derive(Resource)]`. Registration and layout work exactly like a
/// component's, because in Bevy a resource *is* a component on a hidden entity —
/// the same descriptor, the same field schema, the same default constructor.
pub trait Resource: Sized + 'static {
    const TYPE_PATH: &'static str;
    fn display_name() -> &'static str;
    fn id_cell() -> &'static core::sync::atomic::AtomicU32;
    fn fields() -> &'static [sys::FieldDesc];
    fn descriptor() -> sys::ComponentDesc;
}

/// The id the host assigned `T`, or `INVALID` if it was never registered.
pub fn resource_id_of<T: Resource>() -> sys::ComponentId {
    sys::ComponentId(T::id_cell().load(core::sync::atomic::Ordering::Relaxed))
}

/// What can sit inside [`Res`] / [`ResMut`].
///
/// Two kinds satisfy this and they resolve differently, which is why it is its
/// own trait rather than folded into [`Resource`]: a plugin's own resource lives
/// in the host world and arrives as a pointer in
/// [`sys::SystemCall::resources`], while [`Time`] is read straight out of the
/// call's frame context and never round-trips through the world at all.
///
/// # Safety
/// `res_ptr` must return a pointer valid for the duration of the call, or null.
pub unsafe trait ResourceParam: Sized {
    fn res_term(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>, access: sys::Access);
    /// # Safety
    /// `call` must be live.
    unsafe fn res_ptr(call: *const sys::SystemCall) -> *mut Self;
}

unsafe impl<T: Resource> ResourceParam for T {
    fn res_term(ctx: &mut InitCtx, out: &mut alloc::vec::Vec<sys::Term>, access: sys::Access) {
        out.push(sys::Term { component: ctx.resource_id_of::<T>(), access });
    }
    unsafe fn res_ptr(call: *const sys::SystemCall) -> *mut T {
        let want = resource_id_of::<T>();
        let slots = core::slice::from_raw_parts((*call).resources, (*call).resource_count);
        slots
            .iter()
            .find(|s| s.id == want)
            .map_or(core::ptr::null_mut(), |s| s.ptr.cast())
    }
}

/// The frame clock. Mirrors `bevy::Time` for the parts a plugin can reach.
///
/// `#[repr(transparent)]` over the frame context so [`ResourceParam::res_ptr`]
/// can hand back a pointer to the live call's own field rather than to a
/// temporary — a `Res<Time>` borrows the call, exactly like every other param.
#[repr(transparent)]
pub struct Time(sys::FrameCtx);

impl Time {
    pub fn delta_secs(&self) -> f32 {
        self.0.delta_secs
    }
    pub fn elapsed_secs(&self) -> f32 {
        self.0.elapsed_secs
    }
}

unsafe impl ResourceParam for Time {
    // Declares nothing: the host sends the frame context with every call, so
    // there is no access to negotiate and no scheduling conflict to create.
    fn res_term(_: &mut InitCtx, _: &mut alloc::vec::Vec<sys::Term>, _: sys::Access) {}
    unsafe fn res_ptr(call: *const sys::SystemCall) -> *mut Time {
        core::ptr::addr_of!((*call).frame) as *mut Time
    }
}

/// Shared access to a resource. Mirrors `bevy::Res`.
pub struct Res<'a, T>(*mut T, PhantomData<&'a T>);

impl<T> Res<'_, T> {
    /// Whether the resource exists. Bevy would have skipped the whole system;
    /// here it runs and the plugin decides, which keeps a missing resource a
    /// local question rather than a silent scheduling puzzle.
    pub fn is_present(&self) -> bool {
        !self.0.is_null()
    }
    pub fn get(&self) -> Option<&T> {
        unsafe { self.0.as_ref() }
    }
}

impl<T> core::ops::Deref for Res<'_, T> {
    type Target = T;
    fn deref(&self) -> &T {
        self.get()
            .expect("resource not present — check `is_present()` first")
    }
}

/// Mutable access to a resource. Mirrors `bevy::ResMut`.
pub struct ResMut<'a, T>(*mut T, PhantomData<&'a mut T>);

impl<T> ResMut<'_, T> {
    pub fn is_present(&self) -> bool {
        !self.0.is_null()
    }
    pub fn get(&self) -> Option<&T> {
        unsafe { self.0.as_ref() }
    }
    pub fn get_mut(&mut self) -> Option<&mut T> {
        unsafe { self.0.as_mut() }
    }
}

impl<T> core::ops::Deref for ResMut<'_, T> {
    type Target = T;
    fn deref(&self) -> &T {
        self.get()
            .expect("resource not present — check `is_present()` first")
    }
}

impl<T> core::ops::DerefMut for ResMut<'_, T> {
    fn deref_mut(&mut self) -> &mut T {
        self.get_mut()
            .expect("resource not present — check `is_present()` first")
    }
}

// ── Commands ─────────────────────────────────────────────────────────────────

/// A group of components to insert together. Mirrors `bevy::Bundle`.
///
/// Implemented for any single component (emitted by `#[derive(Component)]`) and
/// for tuples of them, so `spawn((A, B, C))` reads exactly as it does in Bevy.
///
/// There is no blanket `impl<T: Component> Bundle for T` because it would
/// overlap with the tuple impls — Rust cannot prove a tuple is not a component.
/// The derive emitting it per-type sidesteps that.
pub trait Bundle {
    fn write(self, e: &mut EntityCommands);
}

/// A scene, ready to spawn. Produced by the [`bsn!`](crate::bsn) macro.
///
/// Named to match `bevy_scene::Scene`, and spawned the same way — through
/// [`Commands::spawn_scene`], not `spawn`. Bevy keeps them separate because a
/// scene is not a bundle: it describes a whole tree, and `spawn` takes the
/// components of one entity.
///
/// The source names components rather than carrying their bytes, which is why
/// one syntax reaches both the engine's components and the plugin's own: the
/// host resolves a name against the type registry first and the plugin schema
/// registry second, and the author never has to know which side a component is
/// on.
#[derive(Clone, Copy)]
pub struct Scene(pub &'static str);

impl Bundle for Scene {
    fn write(self, e: &mut EntityCommands) {
        if e.sink.is_null() {
            return;
        }
        let cmd = sys::Command {
            kind: sys::CommandKind::SpawnBsn,
            entity: e.id,
            component: sys::ComponentId::INVALID,
            data: self.0.as_ptr(),
            data_len: self.0.len(),
        };
        // SAFETY: the sink copies the bytes before returning, and the source is
        // `'static` regardless.
        unsafe { ((*e.sink).push)(e.sink, &cmd) };
    }
}

macro_rules! bundle_tuples {
    ($(($($p:ident),+))+) => {
        $(
            #[allow(non_snake_case)]
            impl<$($p: Bundle),+> Bundle for ($($p,)+) {
                fn write(self, e: &mut EntityCommands) {
                    let ($($p,)+) = self;
                    $($p.write(e);)+
                }
            }
        )+
    };
}

bundle_tuples! {
    (A)
    (A, B)
    (A, B, C)
    (A, B, C, D)
    (A, B, C, D, E)
    (A, B, C, D, E, F)
    (A, B, C, D, E, F, G)
    (A, B, C, D, E, F, G, H)
}

/// Queue structural changes. Mirrors `bevy::Commands`.
///
/// Deferred, like Bevy's: everything queued here is applied after the system
/// finishes. Spawning mid-iteration would invalidate the rows being walked.
pub struct Commands<'a> {
    sink: *mut sys::CommandSink,
    _p: PhantomData<&'a ()>,
}

impl<'a> Commands<'a> {
    /// Spawn an entity carrying `bundle`. Mirrors `bevy::Commands::spawn`.
    pub fn spawn<B: Bundle>(&mut self, bundle: B) -> EntityCommands<'_> {
        let mut e = self.spawn_empty();
        bundle.write(&mut e);
        e
    }

    /// Spawn a visible entity: mesh, material and transform in one go.
    ///
    /// Returns [`EntityCommands`] so plugin components can be attached to it in
    /// the same breath.
    pub fn spawn_mesh(
        &mut self,
        mesh: sys::AssetHandle,
        material: sys::AssetHandle,
        transform: Transform,
    ) -> EntityCommands<'_> {
        let mut e = self.spawn_empty();
        e.make_renderable(mesh, material, transform);
        e
    }

    /// Spawn a scene. Mirrors `bevy::Commands::spawn_scene`.
    ///
    /// ```ignore
    /// commands.spawn_scene(bsn! {
    ///     #Light
    ///     Transform { translation: Vec3(0.0, 6.0, 0.0) }
    ///     PointLight { intensity: 400000.0 }
    ///     Children [
    ///         Marker,
    ///     ]
    /// });
    /// ```
    ///
    /// The returned id is the scene's root. It is valid immediately, even though
    /// the tree materialises when commands are applied — the same reservation
    /// `spawn_empty` uses.
    pub fn spawn_scene(&mut self, scene: Scene) -> EntityCommands<'_> {
        self.spawn(scene)
    }

    /// Reserve an entity with nothing on it. The id is usable immediately — for
    /// parenting, for storing in a component — even though the entity itself
    /// appears when commands are applied.
    pub fn spawn_empty(&mut self) -> EntityCommands<'_> {
        let id = if self.sink.is_null() {
            sys::Entity(u64::MAX)
        } else {
            unsafe { ((*self.sink).reserve_entity)(self.sink) }
        };
        EntityCommands {
            id,
            sink: self.sink,
            _p: PhantomData,
        }
    }

    /// Queue changes for an existing entity.
    pub fn entity(&mut self, entity: sys::Entity) -> EntityCommands<'_> {
        EntityCommands {
            id: entity,
            sink: self.sink,
            _p: PhantomData,
        }
    }
}

/// Queued changes for one entity. Mirrors `bevy::EntityCommands`.
pub struct EntityCommands<'a> {
    id: sys::Entity,
    sink: *mut sys::CommandSink,
    /// Ties this to its `Commands`, so it cannot outlive the sink it writes to.
    _p: PhantomData<&'a ()>,
}

impl<'a> EntityCommands<'a> {
    pub fn id(&self) -> sys::Entity {
        self.id
    }

    /// Insert a bundle. Mirrors `bevy::EntityCommands::insert`.
    pub fn insert<B: Bundle>(&mut self, bundle: B) -> &mut Self {
        bundle.write(self);
        self
    }

    /// Queue one component, copying its bytes.
    ///
    /// Takes the value by move and forgets it: the host now owns those bytes and
    /// will run the component's destructor if it has one. Dropping here too
    /// would free twice.
    pub fn insert_one<T: Component>(&mut self, value: T) -> &mut Self {
        if self.sink.is_null() {
            return self;
        }
        let bytes = &value as *const T as *const u8;
        let cmd = sys::Command {
            kind: sys::CommandKind::Insert,
            entity: self.id,
            component: sys::ComponentId::INVALID,
            data: bytes,
            data_len: core::mem::size_of::<T>(),
        };
        // The host resolves the component from the descriptor rather than an id,
        // because a plugin has no way to know the id it was assigned without
        // asking — and asking mid-system is exactly what the sink exists to
        // avoid.
        let mut cmd = cmd;
        cmd.component = component_id_of::<T>();
        unsafe { ((*self.sink).push)(self.sink, &cmd) };
        core::mem::forget(value);
        self
    }

    /// Attach mesh, material and transform. Used by [`Commands::spawn_mesh`].
    pub fn make_renderable(
        &mut self,
        mesh: sys::AssetHandle,
        material: sys::AssetHandle,
        transform: Transform,
    ) -> &mut Self {
        if self.sink.is_null() {
            return self;
        }
        let desc = sys::SpawnMeshDesc {
            mesh,
            material,
            transform,
        };
        let cmd = sys::Command {
            kind: sys::CommandKind::SpawnMesh,
            entity: self.id,
            component: sys::ComponentId::INVALID,
            data: (&desc as *const sys::SpawnMeshDesc).cast(),
            data_len: core::mem::size_of::<sys::SpawnMeshDesc>(),
        };
        unsafe { ((*self.sink).push)(self.sink, &cmd) };
        self
    }

    pub fn remove<T: Component>(&mut self) -> &mut Self {
        if self.sink.is_null() {
            return self;
        }
        let cmd = sys::Command {
            kind: sys::CommandKind::Remove,
            entity: self.id,
            component: component_id_of::<T>(),
            data: core::ptr::null(),
            data_len: 0,
        };
        unsafe { ((*self.sink).push)(self.sink, &cmd) };
        self
    }

    /// Despawn this entity and its descendants.
    pub fn despawn(&mut self) {
        if self.sink.is_null() {
            return;
        }
        let cmd = sys::Command {
            kind: sys::CommandKind::Despawn,
            entity: self.id,
            component: sys::ComponentId::INVALID,
            data: core::ptr::null(),
            data_len: 0,
        };
        unsafe { ((*self.sink).push)(self.sink, &cmd) };
    }
}

// ── Systems ──────────────────────────────────────────────────────────────────

/// One argument a system can take. Mirrors `bevy::SystemParam`.
///
/// Systems used to be enumerated by parameter shape — `Query`, `Query + Time`,
/// `Query + Commands`, and so on — which needs a new impl for every combination
/// and explodes the moment a resource joins in. This is the same fix Bevy uses:
/// describe one parameter, derive every combination from tuples.
///
/// `fetch` takes a **raw pointer**, not a reference, and that is load-bearing
/// rather than sloppy. The obvious signature — `fn fetch<'a>(&'a SystemCall) ->
/// Self::Item<'a>` — makes the parameter type an associated type, and the
/// compiler cannot run an associated type backwards: given `fn spin(Query<..>,
/// Res<Time>)` it has no way to work out which `SystemParam` produced those
/// items, so every `add_systems` call fails with "type annotations needed".
/// Returning `Self` makes the parameter type *the* type in the signature, which
/// unifies directly. The lifetime inside `Self` is then unchecked, which is why
/// this trait is `unsafe`: the call outlives the system body, so borrowing from
/// it is sound, but nothing in the types enforces that.
///
/// # Safety
/// `terms` must declare every component `fetch` reads, or the host will build a
/// query that does not match what the system touches. `fetch` must not retain
/// anything past the call.
pub unsafe trait SystemParam: Sized {
    /// Declare what this parameter needs.
    ///
    /// A `Query` pushes its own term list as a **separate** query; everything
    /// else pushes resource terms, which are per-system rather than per-query. A
    /// single merged list was what limited a system to one query: two `Query`
    /// parameters had nowhere to be separate, so their terms AND-ed together and
    /// both read the same cells.
    fn declare(ctx: &mut InitCtx, out: &mut SystemBuilder);

    /// # Safety
    /// `call` must be live for at least as long as the returned value is used.
    /// `views` is the running index of query parameters seen so far, and must be
    /// advanced by exactly the number this parameter declared — the host returns
    /// one view per declared query, in declaration order, and the two walks have
    /// to stay in step.
    unsafe fn fetch(call: *const sys::SystemCall, views: &mut usize) -> Self;
}

/// Collects what a system's parameters declare, before it is registered.
#[derive(Default)]
pub struct SystemBuilder {
    pub(crate) queries: alloc::vec::Vec<alloc::vec::Vec<sys::Term>>,
    pub(crate) resources: alloc::vec::Vec<sys::Term>,
}

unsafe impl<D: QueryData, F: QueryFilter> SystemParam for Query<'_, D, F> {
    fn declare(ctx: &mut InitCtx, out: &mut SystemBuilder) {
        let mut terms = alloc::vec::Vec::new();
        D::terms(ctx, &mut terms);
        F::terms(ctx, &mut terms);
        out.queries.push(terms);
    }
    unsafe fn fetch(call: *const sys::SystemCall, views: &mut usize) -> Self {
        let index = *views;
        *views += 1;
        Query::new(call, index)
    }
}

unsafe impl<T: ResourceParam> SystemParam for Res<'_, T> {
    fn declare(ctx: &mut InitCtx, out: &mut SystemBuilder) {
        T::res_term(ctx, &mut out.resources, sys::Access::ResRead);
    }
    unsafe fn fetch(call: *const sys::SystemCall, _: &mut usize) -> Self {
        Res(T::res_ptr(call), PhantomData)
    }
}

unsafe impl<T: ResourceParam> SystemParam for ResMut<'_, T> {
    fn declare(ctx: &mut InitCtx, out: &mut SystemBuilder) {
        T::res_term(ctx, &mut out.resources, sys::Access::ResWrite);
    }
    unsafe fn fetch(call: *const sys::SystemCall, _: &mut usize) -> Self {
        ResMut(T::res_ptr(call), PhantomData)
    }
}

unsafe impl SystemParam for Commands<'_> {
    fn declare(_: &mut InitCtx, _: &mut SystemBuilder) {}
    unsafe fn fetch(call: *const sys::SystemCall, _: &mut usize) -> Self {
        Commands {
            sink: (*call).commands,
            _p: PhantomData,
        }
    }
}

macro_rules! param_tuples {
    ($(($($p:ident),+))+) => {
        $(
            unsafe impl<$($p: SystemParam),+> SystemParam for ($($p,)+) {
                fn declare(ctx: &mut InitCtx, out: &mut SystemBuilder) {
                    $($p::declare(ctx, out);)+
                }
                unsafe fn fetch(call: *const sys::SystemCall, views: &mut usize) -> Self {
                    // Declaration order and fetch order are the same walk over
                    // the same tuple, which is what keeps view indices aligned.
                    ($($p::fetch(call, views),)+)
                }
            }
        )+
    };
}

param_tuples! {
    (A)
    (A, B)
    (A, B, C)
    (A, B, C, D)
    (A, B, C, D, E)
    (A, B, C, D, E, F)
}

/// A function that can be registered as a system.
///
/// Implemented for the *callable* rather than for `fn(..)` pointer types, which
/// matters for ergonomics: a bare `spin` is a fn **item**, a distinct
/// zero-sized type that only coerces to a pointer at a coercion site. Impl'ing
/// on the pointer would force every call to read `add_systems(Update, spin as
/// fn(_, _))`, and "identical to Bevy source" is the whole point.
///
/// The callable must be zero-sized — fn items and non-capturing closures
/// qualify, capturing closures do not. Enforced at compile time in
/// [`materialize`]; a capturing closure would need storage the host has no way
/// to own, so rejecting it is correct rather than a limitation to lift later.
pub trait IntoSystem<Marker> {
    fn build(self, ctx: &mut InitCtx) -> (SystemBuilder, sys::SystemEntry, *mut core::ffi::c_void);
}

/// Reconstruct a zero-sized callable from nothing.
///
/// Sound because a ZST has exactly one value and no bytes to be wrong about; the
/// const assertion is what keeps it that way if someone passes a capturing
/// closure.
#[inline(always)]
unsafe fn materialize<T>() -> T {
    const {
        assert!(
            core::mem::size_of::<T>() == 0,
            "a system must be a plain fn or a non-capturing closure — a capturing              closure has state the host cannot own",
        );
    }
    // Reading a zero-sized value through a dangling-but-aligned, non-null
    // pointer is the sanctioned way to materialise a ZST — it touches no memory,
    // because there is none to touch. `MaybeUninit::assume_init` would express
    // the same thing but is deny-by-default under clippy, which cannot see the
    // const assertion above that makes it sound.
    core::ptr::NonNull::<T>::dangling().as_ptr().read()
}

/// Marker distinguishing one parameter-tuple impl from another, so they don't
/// overlap.
pub struct ParamsMarker<P>(PhantomData<P>);

/// Run a system body, converting a panic into a status the host can act on.
///
/// A panic unwinding out of an `extern "C"` function aborts the process, so
/// without this one bad index in a half-written system takes the editor down.
/// `AssertUnwindSafe` is required because the call carries raw pointers; that is
/// sound here because a panic leaves host memory in whatever state the partial
/// loop wrote — data the host owns and re-reads next frame, with no plugin-side
/// invariants to break.
unsafe fn guard(call: &sys::SystemCall, body: impl FnOnce()) -> sys::SystemStatus {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(body)) {
        Ok(()) => sys::SystemStatus::Ok,
        Err(e) => {
            let msg = e
                .downcast_ref::<&str>()
                .map(alloc::string::ToString::to_string)
                .or_else(|| e.downcast_ref::<alloc::string::String>().cloned())
                .unwrap_or_else(|| alloc::string::String::from("panic"));
            if !call.iface.is_null() {
                ((*call.iface).log)(
                    call.host,
                    sys::LogLevel::Error,
                    sys::StrRef {
                        ptr: msg.as_ptr(),
                        len: msg.len(),
                    },
                );
            }
            sys::SystemStatus::Panicked
        }
    }
}

/// One `IntoSystem` impl per arity. The thunk lives inside the expansion because
/// calling the function needs the parameters spread, not tupled — there is no
/// variadic form to write it once.
///
/// The bound is `Fn($($p),+)` over the *parameter* types rather than over fetched
/// item types, so inference runs the right way: the compiler matches `spin`'s
/// signature against it and reads `P = Query<..>, Res<Time>` straight off, then
/// looks up each one's `SystemParam` impl.
macro_rules! into_system {
    ($(($($p:ident),+))+) => {
        $(
            impl<$($p,)+ Func> IntoSystem<ParamsMarker<($($p,)+)>> for Func
            where
                $($p: SystemParam,)+
                Func: Fn($($p),+) + 'static,
            {
                fn build(
                    self,
                    ctx: &mut InitCtx,
                ) -> (SystemBuilder, sys::SystemEntry, *mut core::ffi::c_void) {
                    unsafe extern "C" fn thunk<$($p,)+ Fun>(
                        call: *const sys::SystemCall,
                    ) -> sys::SystemStatus
                    where
                        $($p: SystemParam,)+
                        Fun: Fn($($p),+) + 'static,
                    {
                        // Rust does not order argument evaluation across a call,
                        // so the view counter is advanced in a `let` chain first
                        // and the results handed over already fetched. Left to
                        // the call site, two `Query` params could take each
                        // other's view.
                        let mut views = 0usize;
                        $(#[allow(non_snake_case)] let $p = $p::fetch(call, &mut views);)+
                        guard(&*call, move || materialize::<Fun>()($($p),+))
                    }

                    let mut builder = SystemBuilder::default();
                    $($p::declare(ctx, &mut builder);)+
                    (builder, thunk::<$($p,)+ Func>, core::ptr::null_mut())
                }
            }
        )+
    };
}

into_system! {
    (A)
    (A, B)
    (A, B, C)
    (A, B, C, D)
    (A, B, C, D, E)
    (A, B, C, D, E, F)
}

// ── Rendering ────────────────────────────────────────────────────────────────

/// The interface, stashed so a render callback can reach it.
///
/// A `sys::RenderCtx` deliberately carries no interface pointer — it is an
/// opaque handle to host state, and widening it would tie the render ABI to the
/// system ABI. So the plugin keeps its own copy, set once at init.
static IFACE: core::sync::atomic::AtomicPtr<sys::Interface> =
    core::sync::atomic::AtomicPtr::new(core::ptr::null_mut());

/// Write a line to the engine log.
///
/// A plugin has no stdout worth using and no `tracing` subscriber of its own, so
/// this is the only way its output reaches the console panel. Silently a no-op
/// before `Plugin::build` has been entered — there is no host to log to yet.
pub fn log(level: sys::LogLevel, msg: &str) {
    let iface = IFACE.load(core::sync::atomic::Ordering::Relaxed);
    if iface.is_null() {
        return;
    }
    // SAFETY: set once at init from the host's `'static` table.
    unsafe {
        ((*iface).log)(
            core::ptr::null_mut(),
            level,
            sys::StrRef {
                ptr: msg.as_ptr(),
                len: msg.len(),
            },
        );
    }
}

pub fn info(msg: &str) {
    log(sys::LogLevel::Info, msg);
}

pub fn warn(msg: &str) {
    log(sys::LogLevel::Warn, msg);
}

pub fn error(msg: &str) {
    log(sys::LogLevel::Error, msg);
}

/// Records draw commands for one view. Mirrors `TrackedRenderPass`.
pub struct RenderPass {
    ctx: sys::RenderCtx,
}

impl RenderPass {
    /// Bind this pass's pipeline and its bind group (view texture at 0, sampler
    /// at 1 — the fullscreen contract).
    pub fn set_pipeline(&mut self) {
        let iface = IFACE.load(core::sync::atomic::Ordering::Relaxed);
        if iface.is_null() {
            return;
        }
        unsafe { ((*iface).render_set_pipeline)(self.ctx, sys::PipelineId(0)) };
    }

    /// Issue a draw. A fullscreen pass is `draw(0..3, 0..1)` — the engine's
    /// fullscreen vertex shader builds a covering triangle from the vertex
    /// index, so there is no vertex buffer.
    pub fn draw(&mut self, vertices: core::ops::Range<u32>, instances: core::ops::Range<u32>) {
        let iface = IFACE.load(core::sync::atomic::Ordering::Relaxed);
        if iface.is_null() {
            return;
        }
        unsafe {
            ((*iface).render_draw)(
                self.ctx,
                vertices.end - vertices.start,
                instances.end - instances.start,
            )
        };
    }
}

unsafe extern "C" fn render_thunk<F>(ctx: sys::RenderCtx, _p: sys::PipelineId) -> sys::SystemStatus
where
    F: Fn(&mut RenderPass) + 'static,
{
    let mut pass = RenderPass { ctx };
    // A panic inside the render graph would take the editor down mid-frame.
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        materialize::<F>()(&mut pass)
    })) {
        Ok(()) => sys::SystemStatus::Ok,
        Err(_) => sys::SystemStatus::Panicked,
    }
}

// ── App / Plugin ─────────────────────────────────────────────────────────────

/// Which schedule a system runs in. Mirrors Bevy's schedule labels.
pub use crate::sys::Schedule;

// Bevy spells its schedule labels `Update`, `PostUpdate` and so on, and that
// spelling is the point of this whole layer — so they are re-exported as
// constants under exactly those names. They used to be enum variants, which
// `use` could import directly; associated constants cannot be, hence the
// explicit list.
#[allow(non_upper_case_globals)]
pub const First: Schedule = Schedule::First;
#[allow(non_upper_case_globals)]
pub const PreUpdate: Schedule = Schedule::PreUpdate;
#[allow(non_upper_case_globals)]
pub const Update: Schedule = Schedule::Update;
#[allow(non_upper_case_globals)]
pub const PostUpdate: Schedule = Schedule::PostUpdate;
#[allow(non_upper_case_globals)]
pub const Last: Schedule = Schedule::Last;

/// Mirrors `bevy::App` for the surface a plugin can reach.
pub struct App {
    ctx: InitCtx,
    /// The first system the host refused, if any. Kept so `add!` can fail the
    /// whole load rather than let a plugin come up half-wired.
    rejected: Option<sys::RegisterStatus>,
}

impl App {
    /// # Safety
    /// `iface` and `host` must be the values the host passed to init.
    pub unsafe fn new(iface: *const sys::Interface, host: *mut sys::Host) -> Self {
        IFACE.store(iface as *mut sys::Interface, core::sync::atomic::Ordering::Relaxed);
        Self {
            ctx: InitCtx {
                iface,
                host,
                cache: alloc::vec::Vec::new(),
                unresolved: None,
            },
            rejected: None,
        }
    }

    /// The type path of the first component that could not be resolved.
    ///
    /// `add!` turns this into [`sys::InitResult::Failed`]; it is exposed so a
    /// plugin hand-writing its own entry point can do the same.
    pub fn unresolved_component(&self) -> Option<&'static str> {
        self.ctx.unresolved
    }

    pub fn add_systems<M, S: IntoSystem<M>>(&mut self, schedule: Schedule, system: S) -> &mut Self {
        let (builder, entry, user) = system.build(&mut self.ctx);
        let descs: alloc::vec::Vec<sys::QueryDesc> = builder
            .queries
            .iter()
            .map(|terms| sys::QueryDesc {
                terms: terms.as_ptr(),
                term_count: terms.len(),
            })
            .collect();
        let desc = sys::SystemDesc {
            entry,
            schedule,
            queries: descs.as_ptr(),
            query_count: descs.len(),
            resources: builder.resources.as_ptr(),
            resource_count: builder.resources.len(),
            user,
            flags: 0,
        };
        // SAFETY: every pointer in `desc` outlives the call; the host copies
        // what it needs into its own plan.
        let status = unsafe { ((*self.ctx.iface).add_system)(self.ctx.host, &desc) };
        if status != sys::RegisterStatus::Ok && self.rejected.is_none() {
            self.rejected = Some(status);
        }
        self
    }

    /// Why the first refused system was refused, if any was.
    ///
    /// Worth checking in `build` alongside
    /// [`unresolved_component`](Self::unresolved_component): a system the host
    /// declined is a plugin that loads and silently does less than it says.
    pub fn rejected_system(&self) -> Option<sys::RegisterStatus> {
        self.rejected
    }

    /// Add a full-screen render pass.
    ///
    /// `fragment_wgsl` is shader **source**, not a path: a plugin has no
    /// `AssetServer` and no asset root the engine could resolve against. The
    /// host compiles it and pairs it with the engine's fullscreen vertex shader.
    ///
    /// The callback runs inside the render graph, once per view, in phase +
    /// `order` sequence.
    pub fn add_render_pass<F>(
        &mut self,
        id: &'static str,
        fragment_wgsl: &'static str,
        phase: sys::RenderPhase,
        order: f32,
        _callback: F,
    ) -> &mut Self
    where
        F: Fn(&mut RenderPass) + 'static,
    {
        let desc = sys::RenderPassDesc {
            id: sys::StrRef::new(id),
            fragment_wgsl: sys::StrRef::new(fragment_wgsl),
            phase,
            order,
            callback: render_thunk::<F>,
        };
        unsafe { ((*self.ctx.iface).add_render_pass)(self.ctx.host, &desc) };
        self
    }

    /// Register a parameterised full-screen effect.
    ///
    /// `T` is an ordinary plugin component: put one on a camera to enable the
    /// effect there, and its fields become the shader's uniform *and* the
    /// inspector's controls — one declaration, both jobs.
    ///
    /// The shader receives:
    ///
    /// ```wgsl
    /// @group(0) @binding(0) var screen_texture: texture_2d<f32>;
    /// @group(0) @binding(1) var texture_sampler: sampler;
    /// @group(0) @binding(2) var<uniform> settings: MySettings;
    /// ```
    ///
    /// `T` must be `#[repr(C)]` and its layout must match the shader's struct
    /// **exactly**. The trap to know about: WGSL aligns `vec3<f32>` to 16 bytes
    /// and Rust's `[f32; 3]` to 4, so
    ///
    /// ```ignore
    /// struct S { a: f32, pad: [f32; 3] }   // Rust: 16 bytes
    /// struct S { a: f32, pad: vec3<f32> }  // WGSL: 32 bytes
    /// ```
    ///
    /// disagree. Pad with scalars on both sides. wgpu rejects a mismatch and the
    /// engine escalates that to an unrecoverable GPU panic — it is not a warning
    /// you can ignore.
    ///
    /// Prefer this over [`App::add_render_pass`] for anything shaped like a
    /// screen effect: the host does extraction, the uniform upload, the bind
    /// group and the draw, so the plugin writes no render code at all.
    pub fn add_post_process<T: Component>(
        &mut self,
        id: &'static str,
        fragment_wgsl: &'static str,
        phase: sys::RenderPhase,
        order: f32,
    ) -> &mut Self {
        let settings = self.ctx.id_of::<T>();
        let desc = sys::PostProcessDesc {
            id: sys::StrRef::new(id),
            fragment_wgsl: sys::StrRef::new(fragment_wgsl),
            settings,
            settings_size: core::mem::size_of::<T>() as u64,
            phase,
            order,
        };
        unsafe { ((*self.ctx.iface).add_post_process)(self.ctx.host, &desc) };
        self
    }

    /// Create a mesh from a built-in primitive.
    ///
    /// Init-only, so build what you need in `Plugin::build` and keep the handle.
    /// One primitive spawned a thousand times shares a single asset.
    pub fn add_mesh(&mut self, primitive: sys::Primitive, size: Vec3) -> sys::AssetHandle {
        let desc = sys::MeshDesc { primitive, size };
        unsafe { ((*self.ctx.iface).add_mesh)(self.ctx.host, &desc) }
    }

    /// Create a standard PBR material. Init-only, like [`App::add_mesh`].
    pub fn add_material(&mut self, color: [f32; 4]) -> sys::AssetHandle {
        let desc = sys::MaterialDesc {
            color,
            metallic: 0.0,
            roughness: 0.5,
            emissive: [0.0, 0.0, 0.0, 1.0],
        };
        unsafe { ((*self.ctx.iface).add_material)(self.ctx.host, &desc) }
    }

    /// Full control over the material's PBR parameters.
    pub fn add_material_pbr(
        &mut self,
        color: [f32; 4],
        metallic: f32,
        roughness: f32,
        emissive: [f32; 4],
    ) -> sys::AssetHandle {
        let desc = sys::MaterialDesc {
            color,
            metallic,
            roughness,
            emissive,
        };
        unsafe { ((*self.ctx.iface).add_material)(self.ctx.host, &desc) }
    }

    /// Register a plugin-owned component ahead of first use. Optional — a
    /// component named in a query is registered automatically.
    pub fn register_component<T: Component>(&mut self) -> &mut Self {
        self.ctx.id_of::<T>();
        self
    }

    /// Register `T` and insert its `Default` value. Mirrors `bevy::App::init_resource`.
    pub fn init_resource<T: Resource>(&mut self) -> &mut Self {
        self.ctx.resource_id_of::<T>();
        self
    }

    /// Register `T` and insert `value`. Mirrors `bevy::App::insert_resource`.
    pub fn insert_resource<T: Resource>(&mut self, value: T) -> &mut Self {
        let id = self.ctx.resource_id_of::<T>();
        if id.is_valid() {
            // The host copies the bytes out and takes ownership of them, so this
            // side must not also run the destructor.
            let value = core::mem::ManuallyDrop::new(value);
            unsafe {
                ((*self.ctx.iface).insert_resource)(
                    self.ctx.host,
                    id,
                    (&*value as *const T).cast(),
                    core::mem::size_of::<T>(),
                );
            }
        }
        self
    }

    /// Register an editor panel from markup. See [`sys::PanelDesc`] for the
    /// grammar.
    ///
    /// `handler` runs when an action widget fires and may be a plain fn or a
    /// non-capturing closure, the same rule systems follow and for the same
    /// reason: the host has nowhere to put a capture.
    pub fn add_panel<H: PanelHandler>(&mut self, panel: Panel<H>) -> &mut Self {
        let desc = sys::PanelDesc {
            id: sys::StrRef::new(panel.id),
            title: sys::StrRef::new(panel.title),
            icon: sys::StrRef::new(panel.icon),
            category: sys::StrRef::new(panel.category),
            markup: sys::StrRef::new(panel.scene.0),
            on_action: H::ENTRY,
            user: core::ptr::null_mut(),
        };
        // SAFETY: every `StrRef` points at a `'static` str, and the host copies
        // the markup before returning.
        let status = unsafe { ((*self.ctx.iface).add_panel)(self.ctx.host, &desc) };
        if status != sys::RegisterStatus::Ok && self.rejected.is_none() {
            self.rejected = Some(status);
        }
        self
    }
}

/// An editor panel, before registration.
///
/// A struct rather than seven positional arguments — a call site reading
/// `add_panel("flock", "Flock", "wind", "Plugins", MARKUP, on_action)` is a
/// puzzle at every future edit.
pub struct Panel<H> {
    pub id: &'static str,
    pub title: &'static str,
    pub icon: &'static str,
    pub category: &'static str,
    /// The panel's contents, as a [`Scene`] — write it inline with
    /// [`bsn!`](crate::bsn) rather than parking it in a `const`.
    pub scene: Scene,
    pub on_action: H,
}

impl Panel<()> {
    /// A panel with no action widgets.
    ///
    /// ```ignore
    /// app.add_panel(Panel::new("flock", "Flock", bsn! {
    ///     Node { flex_direction: Column, row_gap: Px(6.0) }
    ///     Children [
    ///         Text("Flocking"),
    ///     ]
    /// }));
    /// ```
    pub fn new(id: &'static str, title: &'static str, scene: Scene) -> Self {
        Self {
            id,
            title,
            icon: "",
            category: "",
            scene,
            on_action: (),
        }
    }
}

impl<H> Panel<H> {
    pub fn icon(mut self, icon: &'static str) -> Self {
        self.icon = icon;
        self
    }

    pub fn category(mut self, category: &'static str) -> Self {
        self.category = category;
        self
    }

    /// Attach the handler for clicks on this panel's `PanelActionId` widgets.
    pub fn on_action<F: Fn(Action)>(self, handler: F) -> Panel<F> {
        Panel {
            id: self.id,
            title: self.title,
            icon: self.icon,
            category: self.category,
            scene: self.scene,
            on_action: handler,
        }
    }
}

/// What a fired action tells the plugin.
pub struct Action<'a> {
    name: &'a str,
    /// A toggle's 0 or 1, a slider's position, 0 for a button.
    pub value: f32,
    /// Structural changes, same queue a system gets.
    pub commands: Commands<'a>,
}

impl Action<'_> {
    /// The name after `->` on the widget that fired.
    pub fn name(&self) -> &str {
        self.name
    }

    /// Convenience for the usual `match`-free single-action panel.
    pub fn is(&self, name: &str) -> bool {
        self.name == name
    }
}

/// Supplies the `extern "C"` entry point for a panel's actions.
///
/// Implemented for `()` — no handler — and for any zero-sized `Fn(Action)`. The
/// ZST bound is the same one systems carry: the thunk reconstructs the callable
/// from nothing, so there is nothing for the host to own or free.
pub trait PanelHandler {
    const ENTRY: Option<sys::PanelActionEntry>;
}

impl PanelHandler for () {
    const ENTRY: Option<sys::PanelActionEntry> = None;
}

impl<F: Fn(Action) + 'static> PanelHandler for F {
    const ENTRY: Option<sys::PanelActionEntry> = Some(panel_thunk::<F>);
}

unsafe extern "C" fn panel_thunk<F: Fn(Action) + 'static>(
    action: *const sys::PanelAction,
) -> sys::SystemStatus {
    let a = &*action;
    let payload = Action {
        name: a.name.as_str(),
        value: a.value,
        commands: Commands {
            sink: a.commands,
            _p: PhantomData,
        },
    };
    // A panic here would unwind out of an `extern "C"` call made from inside the
    // editor's own UI systems, which aborts the process — a bad button taking
    // the editor down with it.
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(move || {
        materialize::<F>()(payload)
    })) {
        Ok(()) => sys::SystemStatus::Ok,
        Err(e) => {
            let msg = e
                .downcast_ref::<&str>()
                .map(alloc::string::ToString::to_string)
                .or_else(|| e.downcast_ref::<alloc::string::String>().cloned())
                .unwrap_or_else(|| alloc::string::String::from("panic"));
            if !a.iface.is_null() {
                ((*a.iface).log)(
                    core::ptr::null_mut(),
                    sys::LogLevel::Error,
                    sys::StrRef {
                        ptr: msg.as_ptr(),
                        len: msg.len(),
                    },
                );
            }
            sys::SystemStatus::Panicked
        }
    }
}

/// Mirrors `bevy::Plugin`.
pub trait Plugin {
    fn build(&self, app: &mut App);
}

extern crate alloc;
