# Renzora Server Configuration Example
# Copy this file to 'renzora.toml' and customize as needed

[server]
# Server port (default: 3002)
port = 3002

# Server host (default: 127.0.0.1) 
host = "127.0.0.1"

# Number of workers (default: auto-detect CPU cores)
# Uncomment to override:
# workers = 8

[paths]
# Base path for the engine (default: auto-detect)
# Examples:
# base_path = "C:\\Users\\YourName\\engine"
# base_path = "/home/user/engine"
# base_path = "D:\\GameDev\\renzora"

# Projects directory (default: base_path/projects)  
# Examples:
# projects_path = "C:\\Users\\YourName\\MyProjects"
# projects_path = "/home/user/game-projects"
# projects_path = "E:\\GameProjects"

[logging]
# Log level: error, warn, info, debug, trace (default: info)
level = "info"

# Enable file watching logs (default: true)
file_watching = true

# Enable WebSocket connection logs (default: true)  
connections = true

[features]
# Enable file watching (default: true)
file_watching = true

# Enable project auto-creation (default: true)
auto_create_projects = true

# Enable system stats reporting (default: true)
system_stats = true

[performance]
# File change notification buffer size (default: 1000)
file_change_buffer = 1000

# WebSocket message timeout in seconds (default: 30)
message_timeout = 30

# Reconnection settings
max_reconnect_attempts = 5
reconnect_delay = 2000