//! The Theme page — the active-theme picker, the semantic colour palette, and a
//! per-widget style editor generated by reflection.
//!
//! Two different theme models are edited here. The `ThemeManager` palette is the
//! semantic one (accent, surfaces, text, syntax); the per-widget section below
//! it walks ember's `Theme` by reflect path, so adding a widget or an element to
//! that struct makes a row appear here with no code change. They also save to
//! different places, which is why there are two save buttons.

use bevy::prelude::*;
use bevy::window::SystemCursorIcon;

use renzora::CurrentProject;
use renzora_ember::cursor_icon::HoverCursor;
use renzora_ember::font::{ui_font, EmberFonts};
use renzora_ember::inspector::color_field;
use renzora_ember::reactive::tracked::bind_2way;
use renzora_ember::theme::*;
use renzora_ember::widgets::{section, toggle_switch};
use renzora_theme::{Theme, ThemeColor, ThemeManager};

use crate::lang::tr;
use crate::rows::{ctl_drag, ctl_dropdown, settings_row};
use crate::state::A_VIOLET;

#[derive(Component)]
pub(crate) struct ThemeSaveBtn;

#[derive(Component)]
pub(crate) struct EmberThemeSaveBtn;

pub(crate) fn tab_theme(commands: &mut Commands, fonts: &EmberFonts, col: Entity, themes: &[String]) {
    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.active_theme"), A_VIOLET);
    commands.entity(col).add_child(sec);

    let opts: Vec<&str> = themes.iter().map(|s| s.as_str()).collect();
    let th1 = themes.to_vec();
    let th2 = themes.to_vec();
    let dd = ctl_dropdown(
        commands,
        fonts,
        &opts,
        0,
        move |w| {
            let name = &w.resource::<ThemeManager>().active_theme_name;
            th1.iter().position(|n| n == name).unwrap_or(0)
        },
        move |w, &i| {
            if let Some(name) = th2.get(i).cloned() {
                w.resource_mut::<ThemeManager>().load_theme(&name);
            }
        },
    );
    settings_row(commands, fonts, body, 0, &tr("settings.tab.theme"), dd);

    // Save button row.
    let save_lbl = commands
        .spawn((
            Text::new(tr("common.save")),
            ui_font(&fonts.ui, 12.0),
            TextColor(rgb(text_primary())),
        ))
        .id();
    let save = commands
        .spawn((
            Node {
                padding: UiRect::axes(Val::Px(12.0), Val::Px(5.0)),
                align_items: AlignItems::Center,
                justify_content: JustifyContent::Center,
                border_radius: BorderRadius::all(Val::Px(4.0)),
                ..default()
            },
            BackgroundColor(rgb(tab_active())),
            Interaction::default(),
            ThemeSaveBtn,
            HoverCursor(SystemCursorIcon::Pointer),
            Name::new("theme-save"),
        ))
        .id();
    commands.entity(save).add_child(save_lbl);
    settings_row(commands, fonts, body, 1, "", save);

    // Color-editing sections.
    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.semantic_colors"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.accent"), |t| t.semantic.accent, |t, c| t.semantic.accent = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.success"), |t| t.semantic.success, |t, c| t.semantic.success = c);
    theme_color_row(commands, fonts, body, 2, &tr("common.warning"), |t| t.semantic.warning, |t, c| t.semantic.warning = c);
    theme_color_row(commands, fonts, body, 3, &tr("common.error"), |t| t.semantic.error, |t, c| t.semantic.error = c);
    theme_color_row(commands, fonts, body, 4, &tr("settings.row.selection"), |t| t.semantic.selection, |t, c| t.semantic.selection = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.sel_stroke"), |t| t.semantic.selection_stroke, |t, c| t.semantic.selection_stroke = c);

    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.surfaces"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.cat.window"), |t| t.surfaces.window, |t, c| t.surfaces.window = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.window_stroke"), |t| t.surfaces.window_stroke, |t, c| t.surfaces.window_stroke = c);
    theme_color_row(commands, fonts, body, 2, &tr("settings.row.panel"), |t| t.surfaces.panel, |t, c| t.surfaces.panel = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.popup"), |t| t.surfaces.popup, |t, c| t.surfaces.popup = c);
    theme_color_row(commands, fonts, body, 4, &tr("settings.row.faint"), |t| t.surfaces.faint, |t, c| t.surfaces.faint = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.extreme"), |t| t.surfaces.extreme, |t, c| t.surfaces.extreme = c);

    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.text"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.primary"), |t| t.text.primary, |t, c| t.text.primary = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.secondary"), |t| t.text.secondary, |t, c| t.text.secondary = c);
    theme_color_row(commands, fonts, body, 2, &tr("settings.row.muted"), |t| t.text.muted, |t, c| t.text.muted = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.heading"), |t| t.text.heading, |t, c| t.text.heading = c);
    theme_color_row(commands, fonts, body, 4, &tr("common.disabled"), |t| t.text.disabled, |t, c| t.text.disabled = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.hyperlink"), |t| t.text.hyperlink, |t, c| t.text.hyperlink = c);

    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.widgets"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.inactive_bg"), |t| t.widgets.inactive_bg, |t, c| t.widgets.inactive_bg = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.inactive_fg"), |t| t.widgets.inactive_fg, |t, c| t.widgets.inactive_fg = c);
    theme_color_row(commands, fonts, body, 2, &tr("settings.row.hovered_bg"), |t| t.widgets.hovered_bg, |t, c| t.widgets.hovered_bg = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.hovered_fg"), |t| t.widgets.hovered_fg, |t, c| t.widgets.hovered_fg = c);
    theme_color_row(commands, fonts, body, 4, &tr("settings.row.active_bg"), |t| t.widgets.active_bg, |t, c| t.widgets.active_bg = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.active_fg"), |t| t.widgets.active_fg, |t, c| t.widgets.active_fg = c);
    theme_color_row(commands, fonts, body, 6, &tr("settings.row.border"), |t| t.widgets.border, |t, c| t.widgets.border = c);

    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.panels"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.tree_line"), |t| t.panels.tree_line, |t, c| t.panels.tree_line = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.drop_line"), |t| t.panels.drop_line, |t, c| t.panels.drop_line = c);
    theme_color_row(commands, fonts, body, 2, &tr("settings.row.tab_active"), |t| t.panels.tab_active, |t, c| t.panels.tab_active = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.tab_inactive"), |t| t.panels.tab_inactive, |t, c| t.panels.tab_inactive = c);

    // Code-editor syntax token colors. Edits route through `ThemeManager` →
    // the shell theme bridge → ember's `SyntaxPalette`, so the open code editor
    // recolors live.
    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.syntax_tokens"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.normal"), |t| t.syntax.normal, |t, c| t.syntax.normal = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.keyword"), |t| t.syntax.keyword, |t, c| t.syntax.keyword = c);
    theme_color_row(commands, fonts, body, 2, &tr("common.type"), |t| t.syntax.r#type, |t, c| t.syntax.r#type = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.function"), |t| t.syntax.function, |t, c| t.syntax.function = c);
    theme_color_row(commands, fonts, body, 4, &tr("settings.row.number"), |t| t.syntax.number, |t, c| t.syntax.number = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.string"), |t| t.syntax.string, |t, c| t.syntax.string = c);
    theme_color_row(commands, fonts, body, 6, &tr("settings.row.comment"), |t| t.syntax.comment, |t, c| t.syntax.comment = c);
    theme_color_row(commands, fonts, body, 7, &tr("settings.row.operator"), |t| t.syntax.operator, |t, c| t.syntax.operator = c);
    theme_color_row(commands, fonts, body, 8, &tr("settings.row.constant"), |t| t.syntax.constant, |t, c| t.syntax.constant = c);
    theme_color_row(commands, fonts, body, 9, &tr("settings.row.punctuation"), |t| t.syntax.punctuation, |t, c| t.syntax.punctuation = c);

    let (sec, body) = section(commands, fonts, "palette", &tr("settings.section.editor_chrome"), A_VIOLET);
    commands.entity(col).add_child(sec);
    theme_color_row(commands, fonts, body, 0, &tr("settings.row.line_number"), |t| t.syntax.line_number, |t, c| t.syntax.line_number = c);
    theme_color_row(commands, fonts, body, 1, &tr("settings.row.active_line_no"), |t| t.syntax.line_number_active, |t, c| t.syntax.line_number_active = c);
    theme_color_row(commands, fonts, body, 2, &tr("settings.row.current_line"), |t| t.syntax.current_line, |t, c| t.syntax.current_line = c);
    theme_color_row(commands, fonts, body, 3, &tr("settings.row.selection"), |t| t.syntax.selection, |t, c| t.syntax.selection = c);
    theme_color_row(commands, fonts, body, 4, &tr("settings.row.cursor"), |t| t.syntax.cursor, |t, c| t.syntax.cursor = c);
    theme_color_row(commands, fonts, body, 5, &tr("settings.row.indent_guide"), |t| t.syntax.indent_guide, |t, c| t.syntax.indent_guide = c);
    theme_color_row(commands, fonts, body, 6, &tr("settings.row.bracket_match"), |t| t.syntax.bracket_match, |t, c| t.syntax.bracket_match = c);
    theme_color_row(commands, fonts, body, 7, &tr("settings.row.find_match"), |t| t.syntax.find_match, |t, c| t.syntax.find_match = c);

    // ── Per-widget style editor ──────────────────────────────────────────────
    // Walk the ember `Theme` via reflection: every widget type → a section, every
    // element → a color picker (Rgba) or number field (f32), bound by reflect
    // path. Editing repaints the live `Styled` widgets immediately. Adding a
    // widget/element to the Theme makes it appear here automatically.
    let hdr = commands
        .spawn((
            Node {
                width: Val::Percent(100.0),
                flex_direction: FlexDirection::Row,
                align_items: AlignItems::Center,
                column_gap: Val::Px(10.0),
                margin: UiRect::new(Val::Px(4.0), Val::Px(0.0), Val::Px(10.0), Val::Px(4.0)),
                ..default()
            },
            Name::new("widget-styles-header"),
        ))
        .id();
    let hdr_lbl = commands
        .spawn((
            Text::new(tr("settings.section.widget_styles")),
            ui_font(&fonts.ui, 12.0),
            TextColor(rgb(text_muted())),
            Node {
                flex_grow: 1.0,
                ..default()
            },
        ))
        .id();
    let save_lbl = commands
        .spawn((
            Text::new(tr("settings.btn.save_to_theme_toml")),
            ui_font(&fonts.ui, 11.0),
            TextColor(rgb(text_primary())),
        ))
        .id();
    let save = commands
        .spawn((
            Node {
                padding: UiRect::axes(Val::Px(10.0), Val::Px(4.0)),
                border_radius: BorderRadius::all(Val::Px(4.0)),
                ..default()
            },
            BackgroundColor(rgb(tab_active())),
            Interaction::default(),
            EmberThemeSaveBtn,
            HoverCursor(SystemCursorIcon::Pointer),
            Name::new("ember-theme-save"),
        ))
        .id();
    commands.entity(save).add_child(save_lbl);
    commands.entity(hdr).add_children(&[hdr_lbl, save]);
    commands.entity(col).add_child(hdr);

    for (widget, elems) in theme_schema() {
        let (sec, body) = section(commands, fonts, "stack", &prettify(&widget), A_VIOLET);
        commands.entity(col).add_child(sec);
        for (i, (elem, kind)) in elems.into_iter().enumerate() {
            let path = format!("{widget}.{elem}");
            let label = prettify(&elem);
            match kind {
                0 => widget_color_row(commands, fonts, body, i, &label, path),
                1 => widget_num_row(commands, fonts, body, i, &label, path),
                _ => widget_bool_row(commands, fonts, body, i, &label, path),
            }
        }
    }
}

/// `button_accent` → `Button Accent`.
fn prettify(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Reflect-walk the ember `Theme`: `[(widget, [(element, kind)])]` where kind is
/// 0 = color (Rgba), 1 = number (f32), 2 = bool. Read from `Theme::default()`
/// (the structure is static), so no world needed.
fn theme_schema() -> Vec<(String, Vec<(String, u8)>)> {
    use bevy::reflect::{PartialReflect, ReflectRef};
    let theme = renzora_ember::style::Theme::default();
    let mut out = Vec::new();
    let ReflectRef::Struct(s) = theme.reflect_ref() else {
        return out;
    };
    for i in 0..s.field_len() {
        let wname = s.name_at(i).unwrap_or_default().to_string();
        let Some(wfield) = s.field_at(i) else { continue };
        let ReflectRef::Struct(ws) = wfield.reflect_ref() else {
            continue;
        };
        let mut elems = Vec::new();
        for j in 0..ws.field_len() {
            let ename = ws.name_at(j).unwrap_or_default().to_string();
            let Some(ef) = ws.field_at(j) else { continue };
            let kind = if ef.try_downcast_ref::<renzora_ember::style::Rgba>().is_some() {
                0u8
            } else if ef.try_downcast_ref::<f32>().is_some() {
                1u8
            } else if ef.try_downcast_ref::<bool>().is_some() {
                2u8
            } else {
                continue;
            };
            elems.push((ename, kind));
        }
        if !elems.is_empty() {
            out.push((wname, elems));
        }
    }
    out
}

/// A toggle row bound to one ember-`Theme` bool element (e.g. dock.shadow).
fn widget_bool_row(commands: &mut Commands, fonts: &EmberFonts, body: Entity, idx: usize, label: &str, path: String) {
    use bevy::reflect::GetPath;
    use renzora_ember::style::Theme as EmberTheme;
    let p = path.clone();
    let sw = toggle_switch(commands, false);
    bind_2way(
        commands,
        sw,
        move |w| w.resource::<EmberTheme>().path::<bool>(p.as_str()).ok().copied().unwrap_or(false),
        move |w, v: &bool| {
            if let Ok(b) = w.resource_mut::<EmberTheme>().path_mut::<bool>(path.as_str()) {
                *b = *v;
            }
        },
    );
    settings_row(commands, fonts, body, idx, label, sw);
}

/// A color row bound to one ember-`Theme` element by reflect `path`
/// (e.g. `button.bg`, `node_graph.cable`). Editing repaints live.
fn widget_color_row(commands: &mut Commands, fonts: &EmberFonts, body: Entity, idx: usize, label: &str, path: String) {
    use bevy::reflect::GetPath;
    use renzora_ember::style::{Rgba, Theme as EmberTheme};
    let p = path.clone();
    let cf = color_field(
        commands,
        move |w| {
            let r = w
                .resource::<EmberTheme>()
                .path::<Rgba>(p.as_str())
                .ok()
                .copied()
                .unwrap_or(Rgba::NONE);
            [r.r as f32 / 255.0, r.g as f32 / 255.0, r.b as f32 / 255.0]
        },
        move |w, rgb| {
            let mut t = w.resource_mut::<EmberTheme>();
            if let Ok(r) = t.path_mut::<Rgba>(path.as_str()) {
                r.r = (rgb[0] * 255.0).round() as u8;
                r.g = (rgb[1] * 255.0).round() as u8;
                r.b = (rgb[2] * 255.0).round() as u8;
            }
        },
    );
    settings_row(commands, fonts, body, idx, label, cf);
}

/// A number row bound to one ember-`Theme` f32 element (radius/padding/border).
fn widget_num_row(commands: &mut Commands, fonts: &EmberFonts, body: Entity, idx: usize, label: &str, path: String) {
    use bevy::reflect::GetPath;
    use renzora_ember::style::Theme as EmberTheme;
    let p = path.clone();
    // Typography fields need bespoke ranges; geometry (border/radius/pad) is 0..64.
    let (min, max, step) = match path.rsplit('.').next().unwrap_or("") {
        "weight" => (100.0, 900.0, 25.0),
        "letter_spacing" => (-20.0, 50.0, 0.1),
        "line_height" => (0.5, 4.0, 0.05),
        _ => (0.0, 64.0, 0.5),
    };
    let dv = ctl_drag(
        commands,
        fonts,
        0.0,
        min,
        max,
        step,
        move |w| {
            w.resource::<EmberTheme>()
                .path::<f32>(p.as_str())
                .ok()
                .copied()
                .unwrap_or(0.0)
        },
        move |w, &v| {
            let mut t = w.resource_mut::<EmberTheme>();
            if let Ok(f) = t.path_mut::<f32>(path.as_str()) {
                *f = v;
            }
        },
    );
    settings_row(commands, fonts, body, idx, label, dv);
}

/// A theme color row: a swatch/picker two-way bound to one `Theme` color,
/// updating the live `ThemeManager.active_theme` (+ `mark_modified`) on edit.
fn theme_color_row(
    commands: &mut Commands,
    fonts: &EmberFonts,
    body: Entity,
    idx: usize,
    label: &str,
    get: fn(&Theme) -> ThemeColor,
    set: fn(&mut Theme, ThemeColor),
) {
    let cf = color_field(
        commands,
        move |w| {
            let [r, g, b, _] = get(&w.resource::<ThemeManager>().active_theme).0;
            [r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0]
        },
        move |w, rgb| {
            let mut tm = w.resource_mut::<ThemeManager>();
            let a = get(&tm.active_theme).0[3];
            let col = ThemeColor::with_alpha(
                (rgb[0] * 255.0).round() as u8,
                (rgb[1] * 255.0).round() as u8,
                (rgb[2] * 255.0).round() as u8,
                a,
            );
            set(&mut tm.active_theme, col);
            tm.mark_modified();
        },
    );
    settings_row(commands, fonts, body, idx, label, cf);
}

pub(crate) fn theme_save_click(
    btns: Query<&Interaction, (Changed<Interaction>, With<ThemeSaveBtn>)>,
    mut tm: ResMut<ThemeManager>,
) {
    for interaction in &btns {
        if *interaction == Interaction::Pressed {
            let name = tm.active_theme_name.clone();
            tm.save_theme(&name);
        }
    }
}

/// Write the live ember `Theme`'s per-widget style sections into the active
/// theme's `themes/<name>.toml`, preserving any existing (e.g. egui color)
/// sections. The bridge / runtime reloads these via `Theme::from_toml`.
pub(crate) fn ember_theme_save_click(world: &mut World) {
    let pressed = {
        let mut q = world
            .query_filtered::<&Interaction, (Changed<Interaction>, With<EmberThemeSaveBtn>)>();
        q.iter(world).any(|i| *i == Interaction::Pressed)
    };
    if !pressed {
        return;
    }
    let Some(project) = world.get_resource::<CurrentProject>().cloned() else {
        return;
    };
    let name = world
        .get_resource::<ThemeManager>()
        .map(|t| t.active_theme_name.clone())
        .unwrap_or_default();
    let theme = world.resource::<renzora_ember::style::Theme>().clone();

    let dir = project.path.join("themes");
    let path = dir.join(format!("{name}.toml"));
    // Preserve existing sections; overwrite the per-widget style tables.
    let mut doc: toml::value::Table = std::fs::read_to_string(&path)
        .ok()
        .and_then(|c| toml::from_str(&c).ok())
        .unwrap_or_default();
    if let Ok(toml::Value::Table(t)) = toml::Value::try_from(&theme) {
        for (k, v) in t {
            doc.insert(k, v);
        }
    }
    if let Ok(out) = toml::to_string_pretty(&toml::Value::Table(doc)) {
        let _ = std::fs::create_dir_all(&dir);
        let _ = std::fs::write(&path, out);
    }
}
