//! Shared UI building blocks for editor panels and game UI.

mod accordion;
mod alert;
mod badge;
mod breadcrumbs;
mod buttons;
mod card;
mod category;
mod code_block;
mod color_picker;
mod color_wheel;
mod colors;
mod combobox;
mod curve_editor;
mod drop_highlight;
mod drop_zone;
mod empty_state;
mod fader;
mod gradient_editor;
mod histogram;
mod image_viewer;
mod knob;
mod mixer_strip;
mod multi_combobox;
mod number_stepper;
mod overlay;
mod progress;
mod property;
mod radio_group;
mod range_edit;
mod rect_edit;
mod reorderable_list;
mod ruler;
mod section;
mod segmented;
mod shortcut_recorder;
mod slider;
mod split_pane;
mod stepper;
mod swatch_palette;
mod table;
mod tabs;
mod tag_input;
mod timeline;
mod toggle;
mod utils;
mod vector_edit;
mod virtual_list;
mod vu_meter;
mod waveform;
mod xy_pad;
pub mod node_graph;
pub mod search_overlay;
pub mod tile_grid;
pub mod tree;

pub use buttons::icon_button;
pub use category::{
    category_colors, collapsible_section, collapsible_section_removable, CategoryHeaderAction,
};
pub use colors::{checkerboard, dim_color, get_theme_colors, set_theme_colors, ThemeColors};
pub use drop_zone::{file_drop_zone, FileDropResult};
pub use empty_state::empty_state;
pub use fader::{vertical_fader, FaderConfig};
pub use knob::{rotary_knob, KnobConfig};
pub use mixer_strip::{mixer_channel_strip, MixerStripConfig, MixerStripState};
pub use node_graph::{
    node_graph, ConnectionDef, NodeDef, NodeGraphConfig, NodeGraphResponse, NodeGraphState, NodeId,
    PinDef, PinDirection, PinId, PinShape,
};
pub use property::{inline_property, property_row, LABEL_WIDTH, MIN_PANEL_WIDTH};
pub use search_overlay::{search_overlay, OverlayAction, OverlayEntry};
pub use section::section_header;
pub use tile_grid::{split_label_two_lines, TileGrid, TileLayout, TileState};
pub use toggle::toggle_switch;
pub use tree::{draw_drop_line, tree_drop_zone, tree_row, TreeDropZone, TreeRowConfig, TreeRowResult};
pub use utils::sanitize_f32;
pub use vu_meter::{vu_meter, VuMeterConfig, VuMeterValue};
pub use color_picker::{color_picker_with_hex, ColorMode, ColorPickerConfig};
pub use combobox::enum_combobox;
pub use drop_highlight::paint_drop_highlight;
pub use range_edit::{range_edit, RangeConfig};
pub use rect_edit::rect_edit;
pub use slider::{labeled_slider, SliderConfig};
pub use vector_edit::{quat_edit_euler, vec2_edit, vec3_edit, vec4_edit, VecEditConfig};
pub use accordion::{accordion, AccordionSection};
pub use alert::{alert, AlertKind};
pub use badge::{avatar, badge, h_divider, kbd, v_divider};
pub use breadcrumbs::breadcrumbs;
pub use card::card;
pub use code_block::code_block;
pub use color_wheel::color_wheel;
pub use curve_editor::{curve_editor, CurveEditorConfig, CurveKey};
pub use gradient_editor::{gradient_editor, GradientEditorConfig, GradientStop};
pub use histogram::{histogram, HistogramConfig};
pub use image_viewer::{image_viewer, ImageViewerState};
pub use multi_combobox::multi_combobox;
pub use number_stepper::{number_stepper, NumberStepperConfig};
pub use overlay::{confirm_modal, modal, popover, tooltip};
pub use progress::{progress_bar, skeleton, spinner};
pub use radio_group::{checkbox_group, radio_group};
pub use reorderable_list::reorderable_list;
pub use ruler::{ruler, RulerAxis, RulerConfig};
pub use segmented::segmented_control;
pub use shortcut_recorder::{shortcut_recorder, Shortcut};
pub use split_pane::{split_pane, PaneSplit};
pub use stepper::{stepper, StepperConfig};
pub use swatch_palette::swatch_palette;
pub use table::{table, SortOrder, TableSort};
pub use tabs::{tab_bar, TabDef};
pub use tag_input::tag_input;
pub use timeline::{timeline, TimelineConfig, TrackLane};
pub use virtual_list::virtual_list;
pub use waveform::{waveform, WaveformConfig};
pub use xy_pad::{xy_pad, XyPadConfig};
