//! Shared scene load/save and rehydration — used by both editor and runtime.

use bevy::ecs::world::FilteredEntityRef;
use bevy::prelude::*;
use renzora_core::console_log::*;
use renzora_core::{CurrentProject, DefaultCamera, EditorCamera, HideInHierarchy, MeshColor, MeshInstanceData, MeshPrimitive, PlayModeCamera, PlayModeState, SceneCamera, ShapeRegistry, ViewportRenderTarget};
use renzora_lighting::Sun;
use serde::de::DeserializeSeed;
use std::collections::BTreeSet;
use std::path::Path;

// ============================================================================
// Save
// ============================================================================

/// Save specific entities to a RON file.
pub fn save_scene(world: &mut World, path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let type_registry = world.resource::<AppTypeRegistry>().clone();

    let mut entities: Vec<Entity> = Vec::new();
    let mut query = world.query_filtered::<Entity, (With<Name>, Without<HideInHierarchy>, Without<EditorCamera>, Without<bevy::input::gamepad::Gamepad>)>();
    for entity in query.iter(world) {
        entities.push(entity);
    }

    // Exclude descendants of MeshInstanceData entities — those are spawned GLTF
    // children that get regenerated by rehydration. Only the parent (which holds
    // the model_path) should be saved.
    {
        let mesh_instance_entities: Vec<Entity> = {
            let mut q = world.query_filtered::<Entity, With<MeshInstanceData>>();
            q.iter(world).collect()
        };
        if !mesh_instance_entities.is_empty() {
            let before = entities.len();
            entities.retain(|&entity| {
                // Walk up the parent chain; if we hit a MeshInstanceData entity
                // and it's not *this* entity, exclude it.
                let mut cursor = entity;
                loop {
                    if let Some(child_of) = world.get::<ChildOf>(cursor) {
                        let parent = child_of.parent();
                        if mesh_instance_entities.contains(&parent) {
                            return false; // descendant of a mesh instance — skip
                        }
                        cursor = parent;
                    } else {
                        break;
                    }
                }
                true
            });
            let excluded = before - entities.len();
            if excluded > 0 {
                console_info("Scene", format!(
                    "Excluded {} GLTF descendant entities from save", excluded
                ));
            }
        }
    }

    if entities.is_empty() {
        let content = "(entities: {}, resources: {})";
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, content)?;
        console_info("Scene", format!("Saved empty scene to {}", path.display()));
        info!("Saved empty scene to {}", path.display());
        return Ok(());
    }

    let mut scene = DynamicSceneBuilder::from_world(world)
        .deny_all_resources()
        .deny_component::<Mesh3d>()
        .deny_component::<MeshMaterial3d<StandardMaterial>>()
        .deny_component::<MeshMaterial3d<renzora_shader::material::runtime::GraphMaterial>>()
        .deny_component::<renzora_shader::material::resolver::MaterialResolved>()
        .deny_component::<MeshMaterial3d<renzora_terrain::material::TerrainCheckerboardMaterial>>()
        .deny_component::<Camera3d>()
        .deny_component::<Camera>()
        .deny_component::<GlobalTransform>()
        .deny_component::<Visibility>()
        .deny_component::<InheritedVisibility>()
        .deny_component::<ViewVisibility>()
        .deny_component::<Children>()
        .deny_component::<bevy::transform::components::TransformTreeChanged>()
        .deny_component::<bevy::camera::primitives::Aabb>()
        .deny_component::<bevy::render::sync_world::SyncToRenderWorld>()
        .deny_component::<bevy::input::gamepad::Gamepad>()
        .deny_component::<bevy::input::gamepad::GamepadSettings>()
        // Networking: Lightyear internals should not persist to scene files.
        // Networked/NetworkOwner/NetworkId are runtime-only markers.
        .deny_component::<renzora_network::Networked>()
        .deny_component::<renzora_network::NetworkOwner>()
        .deny_component::<renzora_network::NetworkId>()
        .extract_entities(entities.into_iter())
        .build();

    // Strip components that can't be serialized or are editor-only.
    {
        let registry = type_registry.read();
        for entity in &mut scene.entities {
            entity.components.retain(|component| {
                // Filter editor-only types by name (not available as deps in runtime)
                let type_name = component.reflect_type_path();
                if type_name.starts_with("bevy_mod_outline::") {
                    return false;
                }
                let serializer = bevy::reflect::serde::TypedReflectSerializer::new(
                    component.as_partial_reflect(),
                    &registry,
                );
                // Try serializing to a throwaway RON value
                ron::ser::to_string(&serializer).is_ok()
            });
        }
    }

    let registry = type_registry.read();
    let serialized = scene
        .serialize(&registry)
        .map_err(|e| format!("Scene serialization failed: {e}"))?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, &serialized)?;
    console_info("Scene", format!("Saved scene to {} ({} entities)", path.display(), scene.entities.len()));
    info!("Saved scene to {} ({} entities)", path.display(), scene.entities.len());
    Ok(())
}

/// Serialize scene entities to a RON string (same logic as `save_scene` but returns a string).
pub fn serialize_scene_to_string(world: &mut World) -> Result<String, Box<dyn std::error::Error>> {
    let type_registry = world.resource::<AppTypeRegistry>().clone();

    let mut entities: Vec<Entity> = Vec::new();
    let mut query = world.query_filtered::<Entity, (With<Name>, Without<HideInHierarchy>, Without<EditorCamera>, Without<bevy::input::gamepad::Gamepad>)>();
    for entity in query.iter(world) {
        entities.push(entity);
    }

    // Exclude descendants of MeshInstanceData entities
    {
        let mesh_instance_entities: Vec<Entity> = {
            let mut q = world.query_filtered::<Entity, With<MeshInstanceData>>();
            q.iter(world).collect()
        };
        if !mesh_instance_entities.is_empty() {
            entities.retain(|&entity| {
                let mut cursor = entity;
                loop {
                    if let Some(child_of) = world.get::<ChildOf>(cursor) {
                        let parent = child_of.parent();
                        if mesh_instance_entities.contains(&parent) {
                            return false;
                        }
                        cursor = parent;
                    } else {
                        break;
                    }
                }
                true
            });
        }
    }

    if entities.is_empty() {
        return Ok("(entities: {}, resources: {})".to_string());
    }

    let mut scene = DynamicSceneBuilder::from_world(world)
        .deny_all_resources()
        .deny_component::<Mesh3d>()
        .deny_component::<MeshMaterial3d<StandardMaterial>>()
        .deny_component::<MeshMaterial3d<renzora_shader::material::runtime::GraphMaterial>>()
        .deny_component::<renzora_shader::material::resolver::MaterialResolved>()
        .deny_component::<MeshMaterial3d<renzora_terrain::material::TerrainCheckerboardMaterial>>()
        .deny_component::<Camera3d>()
        .deny_component::<Camera>()
        .deny_component::<GlobalTransform>()
        .deny_component::<Visibility>()
        .deny_component::<InheritedVisibility>()
        .deny_component::<ViewVisibility>()
        .deny_component::<Children>()
        .deny_component::<bevy::transform::components::TransformTreeChanged>()
        .deny_component::<bevy::camera::primitives::Aabb>()
        .deny_component::<bevy::render::sync_world::SyncToRenderWorld>()
        .deny_component::<bevy::input::gamepad::Gamepad>()
        .deny_component::<bevy::input::gamepad::GamepadSettings>()
        .deny_component::<renzora_network::Networked>()
        .deny_component::<renzora_network::NetworkOwner>()
        .deny_component::<renzora_network::NetworkId>()
        .extract_entities(entities.into_iter())
        .build();

    // Strip components that can't be serialized or are editor-only.
    {
        let registry = type_registry.read();
        for entity in &mut scene.entities {
            entity.components.retain(|component| {
                let type_name = component.reflect_type_path();
                if type_name.starts_with("bevy_mod_outline::") {
                    return false;
                }
                let serializer = bevy::reflect::serde::TypedReflectSerializer::new(
                    component.as_partial_reflect(),
                    &registry,
                );
                ron::ser::to_string(&serializer).is_ok()
            });
        }
    }

    let registry = type_registry.read();
    let serialized = scene
        .serialize(&registry)
        .map_err(|e| format!("Scene serialization failed: {e}"))?;

    Ok(serialized)
}

/// Load a scene from a RON string into the world (same logic as `load_scene` but from string).
pub fn load_scene_from_string(world: &mut World, ron: &str) {
    let trimmed = ron.trim();
    if trimmed.is_empty() || trimmed == "(entities: {}, resources: {})" {
        return;
    }

    let scene = {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();

        let scene_deserializer = bevy::scene::serde::SceneDeserializer {
            type_registry: &registry,
        };

        let mut ron_deserializer = match ron::Deserializer::from_str(ron) {
            Ok(d) => d,
            Err(e) => {
                error!("Failed to parse RON string: {}", e);
                return;
            }
        };

        match scene_deserializer.deserialize(&mut ron_deserializer) {
            Ok(s) => s,
            Err(e) => {
                error!("Failed to deserialize scene from string: {}", e);
                return;
            }
        }
    };

    let mut entity_map = bevy::ecs::entity::EntityHashMap::default();
    match scene.write_to_world(world, &mut entity_map) {
        Ok(()) => {
            // Re-insert ChildOf to trigger hierarchy hooks
            let children_with_parents: Vec<(Entity, Entity)> = entity_map
                .values()
                .filter_map(|&entity| {
                    world.get_entity(entity).ok()?.get::<ChildOf>().map(|c| (entity, c.parent()))
                })
                .collect();

            for (child, parent) in children_with_parents {
                world.entity_mut(child).remove::<ChildOf>();
                world.entity_mut(child).insert(ChildOf(parent));
            }
        }
        Err(e) => {
            error!("Failed to write scene from string to world: {}", e);
        }
    }
}

/// Save the current project's main scene.
pub fn save_current_scene(world: &mut World) {
    let Some(project) = world.get_resource::<CurrentProject>() else {
        warn!("No project open — cannot save scene");
        return;
    };
    let path = project.main_scene_path();
    if let Err(e) = save_scene(world, &path) {
        error!("Failed to save scene: {}", e);
    }
}

// ============================================================================
// Load
// ============================================================================

/// Load a scene from a RON file into the world.
///
/// Tries the Vfs (rpak archive) first, then falls back to disk.
pub fn load_scene(world: &mut World, path: &Path) {
    console_info("Scene", format!("=== Loading scene from {} ===", path.display()));

    // Try reading from Vfs (rpak archive) first.
    let content = if let Some(vfs) = world.get_resource::<crate::Vfs>() {
        // Normalize to forward-slash archive-relative path, stripping leading "./" or ".\"
        let path_str = path.to_string_lossy().replace('\\', "/");
        let archive_key = path_str.strip_prefix("./").unwrap_or(&path_str);
        if let Some(s) = vfs.read_string(archive_key) {
            console_info("Scene", format!("Read {} bytes from rpak: {}", s.len(), archive_key));
            Some(s)
        } else {
            None
        }
    } else {
        None
    };

    // Fall back to disk if Vfs didn't have it.
    let content = match content {
        Some(c) => c,
        None => {
            if !path.exists() {
                console_warn("Scene", format!("Scene file does not exist: {}", path.display()));
                info!("Scene file does not exist yet: {}", path.display());
                return;
            }
            match std::fs::read_to_string(path) {
                Ok(c) => {
                    console_info("Scene", format!("Read {} bytes from {}", c.len(), path.display()));
                    c
                }
                Err(e) => {
                    console_error("Scene", format!("Failed to read scene file {}: {}", path.display(), e));
                    error!("Failed to read scene file {}: {}", path.display(), e);
                    return;
                }
            }
        }
    };

    let trimmed = content.trim();
    if trimmed.is_empty() || trimmed == "(entities: {}, resources: {})" {
        console_info("Scene", format!("Scene is empty: {}", path.display()));
        info!("Scene is empty: {}", path.display());
        return;
    }

    let scene = {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();

        let scene_deserializer = bevy::scene::serde::SceneDeserializer {
            type_registry: &registry,
        };

        let mut ron_deserializer = match ron::Deserializer::from_str(&content) {
            Ok(d) => d,
            Err(e) => {
                error!("Failed to parse RON {}: {}", path.display(), e);
                return;
            }
        };

        match scene_deserializer.deserialize(&mut ron_deserializer) {
            Ok(s) => s,
            Err(e) => {
                error!("Failed to deserialize scene {}: {}", path.display(), e);
                return;
            }
        }
    };

    let mut entity_map = bevy::ecs::entity::EntityHashMap::default();
    match scene.write_to_world(world, &mut entity_map) {
        Ok(()) => {
            console_info("Scene", format!(
                "Scene written to world: {} entities mapped from {}",
                entity_map.len(), path.display()
            ));

            // Log each mapped entity
            for (&scene_entity, &world_entity) in &entity_map {
                let name = world.get::<Name>(world_entity)
                    .map(|n| n.to_string())
                    .unwrap_or_else(|| "unnamed".into());
                let has_scene_cam = world.get::<SceneCamera>(world_entity).is_some();
                let has_default = world.get::<DefaultCamera>(world_entity).is_some();
                let mut tags = Vec::new();
                if has_scene_cam { tags.push("SceneCamera"); }
                if has_default { tags.push("DefaultCamera"); }
                let tag_str = if tags.is_empty() { String::new() } else { format!(" [{}]", tags.join(", ")) };
                console_info("Scene", format!(
                    "  scene:{:?} -> world:{:?} \"{}\"{}",
                    scene_entity, world_entity, name, tag_str
                ));
            }

            info!("Loaded scene from {} ({} entities mapped)", path.display(), entity_map.len());

            // Bevy's write_to_world inserts ChildOf via reflection, which may not
            // trigger the on_insert hooks that maintain the parent's Children component.
            // Re-insert ChildOf on each child to force the hooks to fire.
            let children_with_parents: Vec<(Entity, Entity)> = entity_map
                .values()
                .filter_map(|&entity| {
                    world.get_entity(entity).ok()?.get::<ChildOf>().map(|c| (entity, c.parent()))
                })
                .collect();

            console_info("Scene", format!(
                "Re-inserting ChildOf on {} entities to trigger hierarchy hooks",
                children_with_parents.len()
            ));

            for (child, parent) in children_with_parents {
                // Remove and re-insert ChildOf to trigger hooks
                world.entity_mut(child).remove::<ChildOf>();
                world.entity_mut(child).insert(ChildOf(parent));
            }

            console_success("Scene", format!("=== Scene load complete: {} ===", path.display()));
        }
        Err(e) => {
            console_error("Scene", format!("Failed to write scene to world {}: {}", path.display(), e));
            error!("Failed to write scene to world {}: {}", path.display(), e);
        }
    }
}

/// Load the current project's main scene.
///
/// Skipped when [`LifecycleHandlesBoot`](renzora_core::LifecycleHandlesBoot) is present,
/// because the lifecycle graph's `On Game Start` node controls the boot scene.
pub fn load_current_scene(world: &mut World) {
    if world.get_resource::<renzora_core::LifecycleHandlesBoot>().is_some() {
        info!("load_current_scene: skipped (lifecycle handles boot)");
        return;
    }
    let Some(project) = world.get_resource::<CurrentProject>() else {
        warn!("load_current_scene: no CurrentProject resource");
        return;
    };
    let path = project.main_scene_path();
    info!("load_current_scene: loading from {}", path.display());
    load_scene(world, &path);
}

// ============================================================================
// Rehydration
// ============================================================================

/// Rehydrate mesh primitives — spawns `Mesh3d` + `MeshMaterial3d` for entities that have
/// `MeshPrimitive` but no `Mesh3d` yet (e.g. after scene deserialization).
pub fn rehydrate_meshes(
    mut commands: Commands,
    query: Query<(Entity, &MeshPrimitive, Option<&MeshColor>), Without<Mesh3d>>,
    registry: Res<ShapeRegistry>,
    mut meshes: Option<ResMut<Assets<Mesh>>>,
    mut materials: Option<ResMut<Assets<StandardMaterial>>>,
) {
    let (Some(mut meshes), Some(mut materials)) = (meshes, materials) else { return };
    for (entity, primitive, color) in &query {
        let Some(mesh) = registry.create_mesh(&primitive.0, &mut meshes) else {
            warn!("Unknown shape ID '{}' — skipping rehydration", primitive.0);
            continue;
        };

        let base_color = color.map_or(Color::WHITE, |c| c.0);
        let material = materials.add(StandardMaterial {
            base_color,
            ..default()
        });

        commands.entity(entity).try_insert((Mesh3d(mesh), MeshMaterial3d(material)));
    }
}

/// Ensure parent entities have `Visibility` so transform/visibility propagation works.
/// Fixes groups/empty parents that were saved without `Visibility`.
pub fn rehydrate_visibility(
    mut commands: Commands,
    query: Query<Entity, (With<Children>, Without<Visibility>)>,
) {
    for entity in &query {
        commands.entity(entity).try_insert(Visibility::default());
    }
}

/// Rehydrate scene cameras — spawns `Camera3d` for entities that have `SceneCamera` but no `Camera3d`.
///
/// In runtime mode (no editor), the `DefaultCamera` is active; if none is marked,
/// the first scene camera wins. All others are inactive.
/// In editor mode, all scene cameras are inactive (the editor camera renders).
/// In play mode, the default camera becomes the active play mode camera with the
/// viewport render target.
pub fn rehydrate_cameras(
    mut commands: Commands,
    query: Query<(Entity, Option<&DefaultCamera>), (With<SceneCamera>, Without<Camera3d>)>,
    editor_camera: Query<(), With<EditorCamera>>,
    play_mode: Option<Res<PlayModeState>>,
    render_target: Option<Res<ViewportRenderTarget>>,
) {
    if query.is_empty() { return; }

    let in_play_mode = play_mode.as_ref().is_some_and(|pm| pm.is_in_play_mode());
    let is_editor = !editor_camera.is_empty() && !in_play_mode;

    // Find which entity should be the active camera in runtime mode
    let default_entity = query.iter()
        .find(|(_, dc)| dc.is_some())
        .or_else(|| query.iter().next())
        .map(|(e, _)| e);

    for (entity, _) in &query {
        let is_active = !is_editor && default_entity == Some(entity);

        commands.entity(entity).try_insert((
            Camera3d::default(),
            Camera {
                is_active,
                ..default()
            },
        ));

        // During play mode, configure the default camera as the play mode camera
        // with the viewport render target (mirrors what enter_play_mode does).
        if in_play_mode && is_active {
            use renzora_core::console_log::*;
            let name = commands.entity(entity).id();
            console_info("Rehydration", format!(
                "Play mode active — configuring {:?} as play mode camera", name
            ));
            commands.entity(entity).try_insert(PlayModeCamera);
            if let Some(ref img) = render_target.as_ref().and_then(|rt| rt.image.as_ref()) {
                commands.entity(entity).try_insert(
                    bevy::camera::RenderTarget::Image(Handle::<Image>::clone(img).into()),
                );
            }
        }
    }
}

/// Keeps `PlayModeState.active_game_camera` in sync when a scene transition
/// during play mode spawns a new `PlayModeCamera` entity.
pub fn sync_play_mode_camera(
    query: Query<Entity, Added<PlayModeCamera>>,
    play_mode: Option<ResMut<PlayModeState>>,
) {
    let Some(mut play_mode) = play_mode else { return; };
    for entity in &query {
        if play_mode.active_game_camera != Some(entity) {
            renzora_core::console_log::console_info("PlayMode", format!(
                "Play mode camera updated: {:?} -> {:?}", play_mode.active_game_camera, entity
            ));
            play_mode.active_game_camera = Some(entity);
        }
    }
}

/// Ensures only the default scene camera is active in runtime mode.
///
/// Runs every frame (cheap — early-exits if no changes). Handles cameras that
/// were deserialized with `Camera3d` already present (so `rehydrate_cameras` skipped them).
pub fn enforce_single_active_camera(
    mut cameras: Query<(Entity, &mut Camera, Option<&DefaultCamera>), With<SceneCamera>>,
    editor_camera: Query<(), With<EditorCamera>>,
) {
    if !editor_camera.is_empty() { return; }
    if cameras.is_empty() { return; }

    // Find which entity should be active: DefaultCamera > first
    let default_entity = cameras.iter()
        .find(|(_, _, dc)| dc.is_some())
        .or_else(|| cameras.iter().next())
        .map(|(e, _, _)| e);

    for (entity, mut camera, _) in &mut cameras {
        let should_be_active = default_entity == Some(entity);
        if camera.is_active != should_be_active {
            camera.is_active = should_be_active;
        }
    }
}

fn should_sync(type_path: &str) -> bool {
    type_path.ends_with("Settings")
}

/// Tracks the previous sync state so we only log when something changes.
#[derive(Resource, Default)]
struct SceneCameraSyncState {
    prev_src: Option<Entity>,
    prev_synced: BTreeSet<&'static str>,
}

/// Sync post-process (and other reflected) components from the **default**
/// SceneCamera entity to the EditorCamera.
///
/// In editor mode the viewport renders through the EditorCamera, but users attach
/// effects to the SceneCamera entity. This system mirrors those components so they
/// take effect during editing.
///
/// Skipped during play mode (the play-mode camera receives effects via
/// `RenderTarget` + the individual `sync_*` systems).
pub fn sync_scene_camera_to_editor_camera(world: &mut World) {
    // Skip during play mode — effects route through RenderTarget instead.
    let is_playing = world
        .get_resource::<PlayModeState>()
        .is_some_and(|pm| pm.is_in_play_mode());
    if is_playing {
        return;
    }

    // Find the editor camera.
    let mut editor_cam = None;
    let mut q = world.query_filtered::<Entity, With<EditorCamera>>();
    for e in q.iter(world) {
        editor_cam = Some(e);
        break;
    }
    let Some(dst) = editor_cam else {
        return;
    };

    // Find the scene camera — prefer DefaultCamera, fall back to first SceneCamera.
    let mut default_cam = None;
    let mut first_cam = None;
    let mut q = world.query_filtered::<(Entity, Option<&DefaultCamera>), With<SceneCamera>>();
    for (e, dc) in q.iter(world) {
        if dc.is_some() {
            default_cam = Some(e);
            break;
        }
        if first_cam.is_none() {
            first_cam = Some(e);
        }
    }
    let scene_cam = default_cam.or(first_cam);

    // If no scene camera exists, remove all synced components from the editor camera.
    let Some(src) = scene_cam else {
        let type_registry = world.resource::<AppTypeRegistry>().clone();
        let registry = type_registry.read();
        let mut to_remove: Vec<bevy::ecs::reflect::ReflectComponent> = Vec::new();
        let editor_ref = world.entity(dst);
        for reg in registry.iter() {
            let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
                continue;
            };
            let type_path = reg.type_info().type_path();
            if !should_sync(type_path) {
                continue;
            }
            if reflect_component.contains(FilteredEntityRef::from(editor_ref)) {
                to_remove.push(reflect_component.clone());
            }
        }
        drop(registry);
        for reflect_component in &to_remove {
            reflect_component.remove(&mut world.entity_mut(dst));
        }
        return;
    };

    if src == dst {
        return;
    }

    let type_registry = world.resource::<AppTypeRegistry>().clone();
    let registry = type_registry.read();

    // Collect reflected component data from the scene camera.
    let mut components_to_sync: Vec<(
        bevy::ecs::reflect::ReflectComponent,
        Box<dyn Reflect>,
    )> = Vec::new();
    let mut synced_type_paths: Vec<&'static str> = Vec::new();

    let entity_ref = world.entity(src);
    for reg in registry.iter() {
        let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
            continue;
        };
        let type_path = reg.type_info().type_path();
        if !should_sync(type_path) {
            continue;
        }
        if let Some(reflected) = reflect_component.reflect(FilteredEntityRef::from(entity_ref)) {
            if let Ok(cloned) = reflected.reflect_clone() {
                components_to_sync.push((reflect_component.clone(), cloned));
                synced_type_paths.push(type_path);
            }
        }
    }
    drop(registry);

    // Apply collected components to the editor camera.
    {
        let registry = type_registry.read();
        for (reflect_component, value) in &components_to_sync {
            let mut entity_mut = world.entity_mut(dst);
            if reflect_component.contains(entity_mut.as_readonly()) {
                reflect_component.apply(entity_mut, value.as_partial_reflect());
            } else {
                reflect_component.insert(&mut entity_mut, value.as_partial_reflect(), &registry);
            }
        }
    }

    // Remove components from editor camera that were removed from scene camera.
    let registry = type_registry.read();
    let mut to_remove: Vec<(bevy::ecs::reflect::ReflectComponent, &'static str)> = Vec::new();
    let editor_ref = world.entity(dst);
    for reg in registry.iter() {
        let Some(reflect_component) = reg.data::<bevy::ecs::reflect::ReflectComponent>() else {
            continue;
        };
        let type_path = reg.type_info().type_path();
        if !should_sync(type_path) {
            continue;
        }
        if reflect_component.contains(FilteredEntityRef::from(editor_ref))
            && !synced_type_paths.contains(&type_path)
        {
            to_remove.push((reflect_component.clone(), type_path));
        }
    }
    drop(registry);

    // Only log when the source camera or set of synced types actually changes.
    let current_set: BTreeSet<&'static str> = synced_type_paths.iter().copied().collect();
    let removed_paths: Vec<&str> = to_remove.iter().map(|(_, p)| *p).collect();

    let mut state = world
        .remove_resource::<SceneCameraSyncState>()
        .unwrap_or_default();

    let src_changed = state.prev_src != Some(src);
    let set_changed = state.prev_synced != current_set;
    let has_removals = !removed_paths.is_empty();

    if src_changed || set_changed || has_removals {
        crate::debug_log::log_scene_camera_sync(
            Some(src),
            Some(dst),
            &synced_type_paths,
            &removed_paths,
        );
        if src_changed {
            let src_name = world
                .get::<Name>(src)
                .map(|n| n.to_string())
                .unwrap_or_else(|| "unnamed".into());
            let has_default = world.get::<DefaultCamera>(src).is_some();
            renzora_core::console_log::console_info(
                "PostProcess",
                format!(
                    "Sync source camera: {:?} \"{}\" default={}",
                    src, src_name, has_default
                ),
            );
        }
        state.prev_src = Some(src);
        state.prev_synced = current_set;
    }

    world.insert_resource(state);

    for (reflect_component, _) in &to_remove {
        reflect_component.remove(&mut world.entity_mut(dst));
    }
}

/// Rehydrate mesh instances — loads GLTF scenes for entities with `MeshInstanceData`
/// but no children yet (i.e. the GLTF scene hasn't been spawned).
///
/// Triggers on `Added<MeshInstanceData>` (scene load). Skips entities that already
/// have children (e.g. model_drop already spawned the SceneRoot child).
pub fn rehydrate_mesh_instances(
    mut commands: Commands,
    query: Query<(Entity, &MeshInstanceData), (Without<Children>, Without<PendingMeshInstanceRehydrate>, Added<MeshInstanceData>)>,
    asset_server: Res<AssetServer>,
) {
    for (entity, instance) in &query {
        let Some(ref model_path) = instance.model_path else {
            continue;
        };

        let gltf_handle: Handle<Gltf> = asset_server.load(model_path.clone());

        // We need to wait for the GLTF to load before spawning the scene.
        // Insert a pending-load marker so a follow-up system can spawn the scene child.
        commands.entity(entity).try_insert(PendingMeshInstanceRehydrate(gltf_handle));
    }
}

/// Marker: waiting for GLTF to finish loading so we can attach the scene child.
#[derive(Component)]
pub struct PendingMeshInstanceRehydrate(pub Handle<Gltf>);

/// Finishes mesh-instance rehydration once the GLTF asset is ready.
pub fn finish_mesh_instance_rehydrate(
    mut commands: Commands,
    query: Query<(Entity, &PendingMeshInstanceRehydrate)>,
    gltf_assets: Option<Res<Assets<Gltf>>>,
) {
    let Some(gltf_assets) = gltf_assets else { return };
    for (entity, pending) in &query {
        let Some(gltf) = gltf_assets.get(&pending.0) else {
            continue;
        };

        let scene_handle = gltf
            .default_scene
            .clone()
            .or_else(|| gltf.scenes.first().cloned());

        if let Some(scene) = scene_handle {
            commands.spawn((
                Name::new("SceneRoot"),
                bevy::scene::SceneRoot(scene),
                Transform::default(),
                Visibility::default(),
                ChildOf(entity),
            ));
        }

        commands.entity(entity).remove::<PendingMeshInstanceRehydrate>();
    }
}

/// Rehydrate sun entities — syncs `DirectionalLight` + `Transform` from `Sun` on newly added entities.
pub fn rehydrate_suns(
    mut query: Query<(&Sun, &mut DirectionalLight, &mut Transform), Added<Sun>>,
) {
    for (sun, mut light, mut transform) in &mut query {
        light.color = Color::srgb(sun.color.x, sun.color.y, sun.color.z);
        light.illuminance = sun.illuminance;
        light.shadows_enabled = sun.shadows_enabled;
        *transform = Transform::from_rotation(
            Quat::from_rotation_arc(Vec3::NEG_Z, sun.direction()),
        );
    }
}
