//! `abi_hash` — report and verify the Renzora plugin ABI hash.
//!
//! ```text
//! cargo run -p abi_hash -- show      # print the current inputs + hash
//! cargo run -p abi_hash -- verify    # diff current inputs vs committed abi.lock (exit 1 on drift)
//! cargo run -p abi_hash -- update    # (re)write abi.lock from the current inputs
//! ```
//!
//! `verify` is the answer to "what changed": when the hash moves it prints the
//! exact field — bevy version, rustc, or which features were added/removed —
//! rather than just a before/after opaque hash. Wire it into CI / the `renzora`
//! CLI so a hash move is always accompanied by its cause.

use std::path::Path;
use std::process::ExitCode;

use abi_hash::{find_workspace_root, gather, AbiInputs};

const LOCK_NAME: &str = "abi.lock";

fn main() -> ExitCode {
    let cmd = std::env::args().nth(1).unwrap_or_else(|| "show".to_string());

    let cwd = std::env::current_dir().expect("current dir");
    let root = match find_workspace_root(&cwd) {
        Some(r) => r,
        None => {
            eprintln!("error: could not find the engine workspace root (no Cargo.lock + [workspace] Cargo.toml above {})", cwd.display());
            return ExitCode::FAILURE;
        }
    };

    let inputs = match gather(&root) {
        Ok(i) => i,
        Err(e) => {
            eprintln!("error: {e}");
            return ExitCode::FAILURE;
        }
    };
    let lock_path = root.join(LOCK_NAME);

    match cmd.as_str() {
        "show" => {
            print_inputs("current ABI inputs", &inputs);
            ExitCode::SUCCESS
        }
        "update" => {
            if let Err(e) = std::fs::write(&lock_path, render_lock(&inputs)) {
                eprintln!("error: writing {}: {e}", lock_path.display());
                return ExitCode::FAILURE;
            }
            println!("wrote {} (hash {})", lock_path.display(), inputs.hash_hex());
            ExitCode::SUCCESS
        }
        "verify" => verify(&lock_path, &inputs),
        other => {
            eprintln!("unknown command `{other}` (expected: show | verify | update)");
            ExitCode::FAILURE
        }
    }
}

/// Compare current inputs against the committed lock and report the cause of any
/// drift. Exit non-zero on mismatch (or a missing lock) so CI fails loudly.
fn verify(lock_path: &Path, current: &AbiInputs) -> ExitCode {
    let locked = match read_lock(lock_path) {
        Ok(l) => l,
        Err(e) => {
            eprintln!("error: {e}");
            eprintln!("       run `cargo run -p abi_hash -- update` to create it.");
            return ExitCode::FAILURE;
        }
    };

    if locked.hash() == current.hash() {
        println!("ABI hash stable: {} ✓", current.hash_hex());
        return ExitCode::SUCCESS;
    }

    eprintln!("ABI HASH CHANGED");
    eprintln!("  locked:  {}", locked.hash_hex());
    eprintln!("  current: {}", current.hash_hex());
    eprintln!("caused by:");

    if locked.bevy_version != current.bevy_version {
        eprintln!("  • bevy version: {} → {}", locked.bevy_version, current.bevy_version);
    }
    if locked.rustc != current.rustc {
        eprintln!("  • rust toolchain: {} → {}", locked.rustc, current.rustc);
    }
    if locked.features != current.features {
        for added in current.features.iter().filter(|f| !locked.features.contains(f)) {
            eprintln!("  • feature added:   +{added}");
        }
        for removed in locked.features.iter().filter(|f| !current.features.contains(f)) {
            eprintln!("  • feature removed: -{removed}");
        }
    }
    eprintln!();
    eprintln!("If this change is intended, re-pin with:");
    eprintln!("  cargo run -p abi_hash -- update");
    eprintln!("Every existing distribution plugin must then be rebuilt against this engine.");
    ExitCode::FAILURE
}

fn print_inputs(title: &str, inputs: &AbiInputs) {
    println!("{title}:");
    println!("  bevy version : {}", inputs.bevy_version);
    println!("  rust toolchain: {}", inputs.rustc);
    println!("  bevy features ({}):", inputs.features.len());
    for f in &inputs.features {
        println!("    {f}");
    }
    println!("  => ABI hash  : {}", inputs.hash_hex());
}

/// Render `abi.lock` (TOML). The hash is stored for human readability and as the
/// `verify` baseline; the inputs are stored so a drift can be diffed even when
/// the engine source that produced them has moved on.
fn render_lock(inputs: &AbiInputs) -> String {
    let mut s = String::new();
    s.push_str("# Renzora plugin ABI lock — generated by `cargo run -p abi_hash -- update`.\n");
    s.push_str("# The hash gates dlopen'd distribution plugins. It is a function of EXACTLY\n");
    s.push_str("# three inputs and changes only when one of them does:\n");
    s.push_str("#   1. bevy version   2. rust toolchain   3. the curated bevy feature set\n");
    s.push_str("# Do not edit by hand; run `cargo run -p abi_hash -- update` to refresh.\n\n");
    s.push_str(&format!("hash = \"{}\"\n", inputs.hash_hex()));
    s.push_str(&format!("bevy_version = \"{}\"\n", inputs.bevy_version));
    s.push_str(&format!("rustc = \"{}\"\n", inputs.rustc));
    s.push_str("features = [\n");
    for f in &inputs.features {
        s.push_str(&format!("    \"{f}\",\n"));
    }
    s.push_str("]\n");
    s
}

/// Parse a committed `abi.lock` back into its inputs.
fn read_lock(path: &Path) -> Result<AbiInputs, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| format!("reading {}: {e}", path.display()))?;
    let doc: toml::Value =
        toml::from_str(&text).map_err(|e| format!("parsing {}: {e}", path.display()))?;
    let get_str = |k: &str| -> Result<String, String> {
        doc.get(k)
            .and_then(|v| v.as_str())
            .map(str::to_owned)
            .ok_or_else(|| format!("{} missing `{k}`", path.display()))
    };
    let features = doc
        .get("features")
        .and_then(|f| f.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str().map(str::to_owned)).collect::<Vec<_>>())
        .unwrap_or_default();
    Ok(AbiInputs {
        bevy_version: get_str("bevy_version")?,
        rustc: get_str("rustc")?,
        features,
    })
}
